In [11]:
import numpy as np
import pandas as pd
pd.set_option('display.float_format', '{:.4f}'.format)
pd.set_option('display.max_columns', 10000)
pd.set_option('display.max_rows', 1000)

In [4]:
train_mini = pd.read_csv('../data/train_mini.csv')

In [5]:
train_mini

,row_id,timestamp,user_id,content_id,content_type_id,task_container_id,user_answer,answered_correctly,prior_question_elapsed_time,prior_question_had_explanation
0,365541,0,7136928,7900,0,0,2,0,nan,NaN
1,365542,23989,7136928,7876,0,1,0,0,21000.0000,False
2,365543,48079,7136928,175,0,2,3,0,20000.0000,False
3,365544,74835,7136928,1278,0,3,1,0,21000.0000,False
4,365545,192811,7136928,2063,0,4,3,0,20000.0000,False
...,...,...,...,...,...,...,...,...,...,...
26887,101109066,2313772645,2145262856,9106,0,352,1,0,18000.0000,True
26888,101109067,2313888806,2145262856,4506,0,353,0,1,18000.0000,True
26889,101109068,2314051785,2145262856,3854,0,354,0,0,25000.0000,True
26890,101109069,2314404971,2145262856,4405,0,355,3,0,56000.0000,True
26891,101109070,2314786293,2145262856,8954,0,356,3,0,37000.0000,True

In [9]:
user_vitrine = pd.read_csv('../data/user_vitrine.csv')

In [13]:
user_vitrine.head(100)

,id,timestamp,user_id,content_id,answered_correctly,prior_question_elapsed_time,prior_question_had_explanation,question_id,part,kmean_cluster,lag_user,lag_user_part,lag_user_clu,lag,user_sum_answered_correctly,user_count_answered_correctly,user_mean_answered_correctly,user_ema_answered_correctly,user_he_sum_answered_correctly,user_he_count_answered_correctly,user_he_mean_answered_correctly,user_he_ema_answered_correctly,user_sum_prior_question_elapsed_time,user_count_prior_question_elapsed_time,user_mean_prior_question_elapsed_time,user_ema_prior_question_elapsed_time,user_he_sum_prior_question_elapsed_time,user_he_count_prior_question_elapsed_time,user_he_mean_prior_question_elapsed_time,user_he_ema_prior_question_elapsed_time,user_ucount_part,user_ucount_kmean_cluster,user_ucount_part.1,user_ucount_kmean_cluster.1
0,365541,0,7136928,7900,0,nan,False,7900,1,0,nan,nan,nan,nan,nan,0,nan,nan,nan,0,nan,nan,nan,1,nan,nan,nan,1,nan,nan,0,0,0,0
1,365542,23989,7136928,7876,0,21000.0000,False,7876,1,13,0.0000,0.0000,nan,0.0000,0.0000,1,0.0000,0.0000,0.0000,1,0.0000,0.0000,21000.0000,2,10500.0000,21000.0000,21000.0000,2,10500.0000,21000.0000,1,1,1,1
2,365543,48079,7136928,175,0,20000.0000,False,175,1,13,0.0000,0.0000,0.0000,13.0000,0.0000,2,0.0000,0.0000,0.0000,2,0.0000,0.0000,41000.0000,3,13666.6667,20483.3333,41000.0000,3,13666.6667,20483.3333,1,2,1,2
3,365544,74835,7136928,1278,0,21000.0000,False,1278,2,11,0.0000,nan,nan,13.0000,0.0000,3,0.0000,0.0000,0.0000,3,0.0000,0.0000,62000.0000,4,15500.0000,20667.1603,62000.0000,4,15500.0000,20667.1603,1,2,1,2
4,365545,192811,7136928,2063,0,20000.0000,False,2063,3,9,0.0000,nan,nan,11.0000,0.0000,4,0.0000,0.0000,0.0000,4,0.0000,0.0000,82000.0000,5,16400.0000,20483.3333,82000.0000,5,16400.0000,20483.3333,2,3,2,3
5,365546,192811,7136928,2064,0,20000.0000,False,2064,3,9,0.0000,0.0000,0.0000,9.0000,0.0000,5,0.0000,0.0000,0.0000,5,0.0000,0.0000,102000.0000,6,17000.0000,20373.3633,102000.0000,6,17000.0000,20373.3633,3,4,3,4
6,365547,192811,7136928,2065,1,20000.0000,False,2065,3,9,0.0000,0.0000,0.0000,9.0000,0.0000,6,0.0000,0.0000,0.0000,6,0.0000,0.0000,122000.0000,7,17428.5714,20300.3207,122000.0000,7,17428.5714,20300.3207,3,4,3,4
7,365548,290933,7136928,3364,1,38000.0000,False,3364,4,6,1.0000,nan,nan,9.0000,1.0000,7,0.1429,0.1730,1.0000,7,0.1429,0.1730,160000.0000,8,20000.0000,23361.5955,160000.0000,8,20000.0000,23361.5955,3,4,3,4
8,365549,290933,7136928,3365,0,38000.0000,False,3365,4,6,1.0000,1.0000,1.0000,6.0000,2.0000,8,0.2500,0.3020,2.0000,8,0.2500,0.3020,198000.0000,9,22000.0000,25645.7124,198000.0000,9,22000.0000,25645.7124,4,5,4,5
9,365550,290933,7136928,3363,0,38000.0000,False,3363,4,6,0.0000,0.0000,0.0000,6.0000,2.0000,9,0.2222,0.2588,2.0000,9,0.2222,0.2588,236000.0000,10,23600.0000,27411.7936,236000.0000,10,23600.0000,27411.7936,4,5,4,5
10,365551,370847,7136928,2947,0,31333.0000,False,2947,4,6,0.0000,0.0000,0.0000,6.0000,2.0000,10,0.2000,0.2245,2.0000,10,0.2000,0.2245,267333.0000,11,24303.0000,27931.5718,267333.0000,11,24303.0000,27931.5718,4,5,4,5
11,365552,370847,7136928,2948,0,31333.0000,False,2948,4,6,0.0000,0.0000,0.0000,6.0000,2.0000,11,0.1818,0.1967,2.0000,11,0.1818,0.1967,298666.0000,12,24888.8333,28353.7271,298666.0000,12,24888.8333,28353.7271,4,5,4,5
12,365553,370847,7136928,2946,0,31333.0000,False,2946,4,6,0.0000,0.0000,0.0000,6.0000,2.0000,12,0.1667,0.1736,2.0000,12,0.1667,0.1736,329999.0000,13,25384.5385,28702.6916,329999.0000,13,25384.5385,28702.6916,4,5,4,5
13,365554,451200,7136928,2595,0,25666.0000,False,2595,4,6,0.0000,0.0000,0.0000,6.0000,2.0000,13,0.1538,0.1543,2.0000,13,0.1538,0.1543,355665.0000,14,25404.6429,28364.7806,355665.0000,14,25404.6429,28364.7806,4,5,4,5
14,365555,451200,7136928,2593,0,25666.0000,False,2593,4,6,0.0000,0.0000,0.0000,6.0000,2.0000,14,0.1429,0.1379,2.0000,14,0.1429,0.1379,381331.0000,15,25422.0667,28077.8862,381331.0000,15,25422.0667,28077.8862,4,5,4,5
15,365556,451200,7136928,2594,0,25666.0000,False,2594,4,6,0.0000,0.0000,0.0000,6.0000,2.0000,15,0.1333,0.1238,2.0000,15,0.1333,0.1238,406997.0000,16,25437.3125,27831.7749,406997.0000,16,25437.3125,27831.7749,4,5,4,5
16,365557,478945,7136928,4492,0,25666.0000,False,4492,5,1,0.0000,nan,nan,6.0000,2.0000,16,0.1250,0.1116,2.0000,16,0.1250,0.1116,432663.0000,17,25450.7647,27618.7700,432663.0000,17,25450.7647,27618.7700,4,5,4,5
17,365558,510488,7136928,4120,0,25000.0000,False,4120,5,1,0.0000,0.0000,0.0000,1.0000,2.0000,17,0.1176,0.1010,2.0000,17,0.1176,0.1010,457663.0000,18,25425.7222,27369.6420,457663.0000,18,25425.7222,27369.6420,5,6,5,6
18,365559,543527,7136928,4696,0,29000.0000,False,4696,5,1,0.0000,0.0000,0.0000,1.0000,2.0000,18,0.1111,0.0917,2.0000,18,0.1111,0.0917,486663.0000,19,25613.8421,27520.1333,486663.0000,19,25613.8421,27520.1333,5,6,5,6
19,365560,572018,7136928,6116,0,31000.0000,False,6116,5,1,0.0000,0.0000,0.0000,1.0000,2.0000,19,0.1053,0.0835,2.0000,19,0.1053,0.0835,517663.0000,20,25883.1500,27832.6599,517663.0000,20,25883.1500,27832.6599,5,6,5,6
20,365561,621276,7136928,6173,0,26000.0000,False,6173,5,1,0.0000,0.0000,0.0000,1.0000,2.0000,20,0.1000,0.0762,2.0000,20,0.1000,0.0762,543663.0000,21,25888.7143,27672.1293,543663.0000,21,25888.7143,27672.1293,5,6,5,6
21,365562,695703,7136928,6370,0,47000.0000,False,6370,5,1,0.0000,0.0000,0.0000,1.0000,2.0000,21,0.0952,0.0696,2.0000,21,0.0952,0.0696,590663.0000,22,26848.3182,29326.9510,590663.0000,22,26848.3182,29326.9510,5,6,5,6
22,365563,869639,7136928,6879,1,72000.0000,False,6879,6,4,0.0000,nan,nan,1.0000,2.0000,22,0.0909,0.0638,2.0000,22,0.0909,0.0638,662663.0000,23,28811.4348,32905.0441,662663.0000,23,28811.4348,32905.0441,5,6,5,6
23,365564,869639,7136928,6880,0,72000.0000,False,6880,6,4,1.0000,1.0000,1.0000,4.0000,3.0000,23,0.1304,0.1408,3.0000,23,0.1304,0.1408,734663.0000,24,30610.9583,36120.9449,734663.0000,24,30610.9583,36120.9449,6,7,6,7
24,365565,869639,7136928,6877,0,72000.0000,False,6877,6,4,0.0000,0.0000,0.0000,4.0000,3.0000,24,0.1250,0.1294,3.0000,24,0.1250,0.1294,806663.0000,25,32266.5200,39020.8579,806663.0000,25,32266.5200,39020.8579,6,7,6,7
25,365566,869639,7136928,6878,1,72000.0000,False,6878,6,4,0.0000,0.0000,0.0000,4.0000,3.0000,25,0.1200,0.1191,3.0000,25,0.1200,0.1191,878663.0000,26,33794.7308,41643.6131,878663.0000,26,33794.7308,41643.6131,6,7,6,7
26,365567,1381521,7136928,7216,0,42750.0000,False,7216,7,5,1.0000,nan,nan,4.0000,4.0000,26,0.1538,0.1882,4.0000,26,0.1538,0.1882,921413.0000,27,34126.4074,41730.3001,921413.0000,27,34126.4074,41730.3001,6,7,6,7
27,365568,1381521,7136928,7217,1,42750.0000,False,7217,7,5,0.0000,0.0000,0.0000,5.0000,4.0000,27,0.1481,0.1736,4.0000,27,0.1481,0.1736,964163.0000,28,34434.3929,41809.1049,964163.0000,28,34434.3929,41809.1049,7,8,7,8
28,365569,1381521,7136928,7219,0,42750.0000,False,7219,7,5,1.0000,1.0000,1.0000,5.0000,5.0000,28,0.1786,0.2367,5.0000,28,0.1786,0.2367,1006913.0000,29,34721.1379,41880.9028,1006913.0000,29,34721.1379,41880.9028,7,8,7,8
29,365570,1381521,7136928,7218,0,42750.0000,False,7218,7,5,0.0000,0.0000,0.0000,5.0000,5.0000,29,0.1724,0.2188,5.0000,29,0.1724,0.2188,1049663.0000,30,34988.7667,41946.4491,1049663.0000,30,34988.7667,41946.4491,7,8,7,8
30,1060729,0,22318239,3779,1,nan,False,3779,5,1,nan,nan,nan,nan,nan,0,nan,nan,nan,0,nan,nan,nan,1,nan,nan,nan,1,nan,nan,0,0,0,0
31,1060730,23082,22318239,5565,1,12000.0000,False,5565,5,1,1.0000,1.0000,1.0000,1.0000,1.0000,1,1.0000,1.0000,1.0000,1,1.0000,1.0000,12000.0000,2,6000.0000,12000.0000,12000.0000,2,6000.0000,12000.0000,1,1,1,1
32,1060731,37693,22318239,4535,1,19000.0000,False,4535,5,1,1.0000,1.0000,1.0000,1.0000,2.0000,2,1.0000,1.0000,2.0000,2,1.0000,1.0000,31000.0000,3,10333.3333,15675.0000,31000.0000,3,10333.3333,15818.1818,1,1,1,1
33,1060732,50594,22318239,3577,0,12000.0000,False,3577,5,7,1.0000,1.0000,nan,1.0000,3.0000,3,1.0000,1.0000,3.0000,3,1.0000,1.0000,43000.0000,4,10750.0000,14325.5620,43000.0000,4,10750.0000,14307.6923,1,1,1,1
34,1060733,66694,22318239,6435,0,10000.0000,False,6435,5,1,0.0000,0.0000,1.0000,7.0000,3.0000,4,0.7500,0.7113,3.0000,4,0.7500,0.6781,53000.0000,5,10600.0000,13076.8392,53000.0000,5,10600.0000,12921.0134,1,2,1,2
35,1060734,82594,22318239,5580,0,13000.0000,False,5580,5,7,0.0000,0.0000,0.0000,1.0000,3.0000,5,0.6000,0.5393,3.0000,5,0.6000,0.4891,66000.0000,6,11000.0000,13058.2524,66000.0000,6,11000.0000,12943.0230,1,2,1,2
36,1060735,105355,22318239,5708,0,13000.0000,False,5708,5,1,0.0000,0.0000,0.0000,7.0000,3.0000,6,0.5000,0.4255,3.0000,6,0.5000,0.3666,79000.0000,7,11285.7143,13045.9638,79000.0000,7,11285.7143,12957.3008,1,2,1,2
37,1060736,132415,22318239,9693,0,20000.0000,False,9693,5,1,0.0000,0.0000,0.0000,1.0000,3.0000,7,0.4286,0.3450,3.0000,7,0.4286,0.2818,99000.0000,8,12375.0000,14360.7999,99000.0000,8,12375.0000,14585.4785,1,2,1,2
38,1060737,158022,22318239,3684,1,24000.0000,False,3684,5,1,0.0000,0.0000,0.0000,1.0000,3.0000,8,0.3750,0.2854,3.0000,8,0.3750,0.2206,123000.0000,9,13666.6667,16026.9841,123000.0000,9,13666.6667,16630.0727,1,2,1,2
39,1060738,173207,22318239,5254,1,23000.0000,False,5254,5,1,1.0000,1.0000,1.0000,1.0000,4.0000,9,0.4444,0.4000,4.0000,9,0.4444,0.3817,146000.0000,10,14600.0000,17145.4899,146000.0000,10,14600.0000,17946.9461,1,2,1,2
40,1060739,242856,22318239,4388,0,12000.0000,False,4388,5,1,1.0000,1.0000,1.0000,1.0000,5.0000,10,0.5000,0.4904,5.0000,10,0.5000,0.5046,158000.0000,11,14363.6364,16370.6237,158000.0000,11,14363.6364,16764.8778,1,2,1,2
41,1060740,259250,22318239,6426,1,13000.0000,True,6426,5,1,0.0000,0.0000,0.0000,nan,5.0000,11,0.4545,0.4204,nan,0,nan,nan,171000.0000,12,14250.0000,15889.6599,13000.0000,1,13000.0000,13000.0000,1,2,0,0
42,1060741,280241,22318239,6437,1,7000.0000,True,6437,5,1,1.0000,1.0000,1.0000,1.0000,6.0000,12,0.5000,0.4994,1.0000,1,1.0000,1.0000,178000.0000,13,13692.3077,14678.6380,20000.0000,2,10000.0000,9666.6667,1,2,1,1
43,1060742,304518,22318239,9983,0,12000.0000,True,9983,5,7,1.0000,1.0000,0.0000,1.0000,7.0000,13,0.5385,0.5649,2.0000,2,1.0000,1.0000,190000.0000,14,13571.4286,14328.1006,32000.0000,3,10666.6667,10622.9508,1,2,1,1
44,1060743,328545,22318239,8219,1,12000.0000,True,8219,5,1,0.0000,0.0000,1.0000,7.0000,7.0000,14,0.5000,0.4935,2.0000,3,0.6667,0.5902,202000.0000,15,13466.6667,14033.9166,44000.0000,4,11000.0000,11089.4309,1,2,1,2
45,1060744,340741,22318239,5696,1,11000.0000,True,5696,5,1,1.0000,1.0000,1.0000,1.0000,8.0000,15,0.5333,0.5556,3.0000,4,0.7500,0.7290,213000.0000,16,13312.5000,13662.1160,55000.0000,5,11000.0000,11062.8272,1,2,1,2
46,1060745,352699,22318239,5238,1,4000.0000,True,5238,5,1,1.0000,1.0000,1.0000,1.0000,9.0000,16,0.5625,0.6086,4.0000,5,0.8000,0.8096,217000.0000,17,12764.7059,12509.5199,59000.0000,6,9833.3333,9148.4084,1,2,1,2
47,1060746,374622,22318239,9862,0,5000.0000,True,9862,5,1,1.0000,1.0000,1.0000,1.0000,10.0000,17,0.5882,0.6542,5.0000,6,0.8333,0.8612,222000.0000,18,12333.3333,11634.7476,64000.0000,7,9142.8571,8098.5569,1,2,1,2
48,1060747,398692,22318239,6151,0,15000.0000,True,6151,5,1,0.0000,0.0000,0.0000,1.0000,10.0000,18,0.5556,0.5796,5.0000,7,0.7143,0.6433,237000.0000,19,12473.6842,12018.6035,79000.0000,8,9875.0000,9757.1034,1,2,1,2
49,1060748,418433,22318239,5335,0,17000.0000,True,5335,5,1,0.0000,0.0000,0.0000,1.0000,10.0000,19,0.5263,0.5147,5.0000,8,0.6250,0.4887,254000.0000,20,12700.0000,12576.3047,96000.0000,9,10666.6667,11430.2485,1,2,1,2
50,2420428,0,51771056,10733,1,14333.0000,True,10733,4,12,nan,nan,nan,nan,nan,0,nan,nan,nan,0,nan,nan,14333.0000,1,14333.0000,14333.0000,14333.0000,1,14333.0000,14333.0000,0,0,0,0
51,2420429,0,51771056,10732,0,14333.0000,True,10732,4,12,1.0000,1.0000,1.0000,12.0000,1.0000,1,1.0000,1.0000,1.0000,1,1.0000,1.0000,28666.0000,2,14333.0000,14333.0000,28666.0000,2,14333.0000,14333.0000,1,1,1,1
52,2420430,0,51771056,10731,1,14333.0000,True,10731,4,12,0.0000,0.0000,0.0000,12.0000,1.0000,2,0.5000,0.4993,1.0000,2,0.5000,0.4993,42999.0000,3,14333.0000,14333.0000,42999.0000,3,14333.0000,14333.0000,1,1,2,2
53,2420431,147940,51771056,2820,1,14333.0000,True,2820,4,12,1.0000,1.0000,1.0000,12.0000,2.0000,3,0.6667,0.6667,2.0000,3,0.6667,0.6667,57332.0000,4,14333.0000,14333.0000,57332.0000,4,14333.0000,14333.0000,1,1,2,2
54,2420432,147940,51771056,2819,1,14333.0000,True,2819,4,12,1.0000,1.0000,1.0000,12.0000,3.0000,4,0.7500,0.7504,3.0000,4,0.7500,0.7504,71665.0000,5,14333.0000,14333.0000,71665.0000,5,14333.0000,14333.0000,1,1,3,3
55,2420433,147940,51771056,2818,0,14333.0000,True,2818,4,12,1.0000,1.0000,1.0000,12.0000,4.0000,5,0.8000,0.8006,4.0000,5,0.8000,0.8006,85998.0000,6,14333.0000,14333.0000,85998.0000,6,14333.0000,14333.0000,1,1,3,3
56,2420434,301126,51771056,2623,1,24000.0000,True,2623,4,12,0.0000,0.0000,0.0000,12.0000,4.0000,6,0.6667,0.6662,4.0000,6,0.6667,0.6662,109998.0000,7,15714.0000,15725.6158,109998.0000,7,15714.0000,15725.8314,1,1,3,3
57,2420435,301126,51771056,2624,1,24000.0000,True,2624,4,12,1.0000,1.0000,1.0000,12.0000,5.0000,7,0.7143,0.7143,5.0000,7,0.7143,0.7143,133998.0000,8,16749.7500,16770.0681,133998.0000,8,16749.7500,16770.4451,1,1,3,3
58,2420436,301126,51771056,2625,0,24000.0000,True,2625,4,12,1.0000,1.0000,1.0000,12.0000,6.0000,8,0.7500,0.7504,6.0000,8,0.7500,0.7504,157998.0000,9,17555.3333,17582.4114,157998.0000,9,17555.3333,17582.9136,1,1,3,3
59,2420437,468350,51771056,2940,0,22666.0000,True,2940,4,6,0.0000,0.0000,nan,12.0000,6.0000,9,0.6667,0.6660,6.0000,9,0.6667,0.6660,180664.0000,10,18066.4000,18097.1930,180664.0000,10,18066.4000,18097.7637,1,1,3,3
60,2420438,468350,51771056,2942,0,22666.0000,True,2942,4,6,0.0000,0.0000,0.0000,6.0000,6.0000,10,0.6000,0.5986,6.0000,10,0.6000,0.5986,203330.0000,11,18484.5455,18518.3725,203330.0000,11,18484.5455,18518.9990,1,2,4,4
61,2420439,468350,51771056,2941,1,22666.0000,True,2941,4,6,0.0000,0.0000,0.0000,6.0000,6.0000,11,0.5455,0.5434,6.0000,11,0.5455,0.5434,225996.0000,12,18833.0000,18869.3503,225996.0000,12,18833.0000,18870.0232,1,2,4,4
62,2420440,782950,51771056,3228,1,23666.0000,True,3228,4,6,1.0000,1.0000,1.0000,6.0000,7.0000,12,0.5833,0.5821,7.0000,12,0.5833,0.5820,249662.0000,13,19204.7692,19244.5477,249662.0000,13,19204.7692,19245.2838,1,2,4,4
63,2420441,782950,51771056,3229,1,23666.0000,True,3229,4,6,1.0000,1.0000,1.0000,6.0000,8.0000,13,0.6154,0.6147,8.0000,13,0.6154,0.6147,273328.0000,14,19523.4286,19566.1399,273328.0000,14,19523.4286,19566.9300,1,2,0,0
64,2420442,782950,51771056,3230,0,23666.0000,True,3230,4,6,1.0000,1.0000,1.0000,6.0000,9.0000,14,0.6429,0.6428,9.0000,14,0.6429,0.6428,296994.0000,15,19799.6000,19844.8481,296994.0000,15,19799.6000,19845.6848,1,2,1,1
65,2420443,29098393,51771056,10857,0,16666.0000,True,10857,6,4,0.0000,nan,nan,6.0000,9.0000,15,0.6000,0.5991,9.0000,15,0.6000,0.5991,313660.0000,16,19603.7500,19641.9749,313660.0000,16,19603.7500,19642.6799,1,2,1,1
66,2420444,29098393,51771056,10858,0,16666.0000,True,10858,6,4,0.0000,0.0000,0.0000,4.0000,9.0000,16,0.5625,0.5608,9.0000,16,0.5625,0.5608,330326.0000,17,19430.9412,19462.9728,330326.0000,17,19430.9412,19463.5619,2,3,1,1
67,2420445,29098393,51771056,10855,1,16666.0000,True,10855,6,4,0.0000,0.0000,0.0000,4.0000,9.0000,17,0.5294,0.5271,9.0000,17,0.5294,0.5271,346992.0000,18,19277.3333,19303.8634,346992.0000,18,19277.3333,19304.3495,2,3,1,1
68,2420446,29098393,51771056,10856,0,16666.0000,True,10856,6,4,1.0000,1.0000,1.0000,4.0000,10.0000,18,0.5556,0.5540,10.0000,18,0.5556,0.5540,363658.0000,19,19139.8947,19161.5057,363658.0000,19,19139.8947,19161.8997,2,3,1,1
69,2420447,75088427,51771056,10834,1,53250.0000,True,10834,6,4,0.0000,0.0000,0.0000,4.0000,10.0000,19,0.5263,0.5241,10.0000,19,0.5263,0.5241,416908.0000,20,20845.4000,20911.6023,416908.0000,20,20845.4000,20912.8291,2,3,1,1
70,2420448,75088427,51771056,10833,1,53250.0000,True,10833,6,4,1.0000,1.0000,1.0000,4.0000,11.0000,20,0.5500,0.5485,11.0000,20,0.5500,0.5485,470158.0000,21,22388.4762,22494.9818,470158.0000,21,22388.4762,22496.9604,2,3,1,1
71,2420449,75088427,51771056,10831,0,53250.0000,True,10831,6,4,1.0000,1.0000,1.0000,4.0000,12.0000,21,0.5714,0.5706,12.0000,21,0.5714,0.5706,523408.0000,22,23791.2727,23934.3782,523408.0000,22,23791.2727,23937.0388,2,3,1,1
72,2420450,75088427,51771056,10832,1,53250.0000,True,10832,6,4,0.0000,0.0000,0.0000,4.0000,12.0000,22,0.5455,0.5439,12.0000,22,0.5455,0.5439,576658.0000,23,25072.0870,25248.5721,576658.0000,23,25072.0870,25251.8539,2,3,1,1
73,2420451,75377509,51771056,10282,1,32750.0000,True,10282,6,4,1.0000,1.0000,1.0000,4.0000,13.0000,23,0.5652,0.5644,13.0000,23,0.5652,0.5644,609408.0000,24,25392.0000,25571.2889,609408.0000,24,25392.0000,25574.6195,2,3,1,2
74,2420452,75377509,51771056,10281,1,32750.0000,True,10281,6,4,1.0000,1.0000,1.0000,4.0000,14.0000,24,0.5833,0.5831,14.0000,24,0.5833,0.5831,642158.0000,25,25686.3200,25868.1791,642158.0000,25,25686.3200,25871.5542,2,3,1,2
75,2420453,75377509,51771056,10280,1,32750.0000,True,10280,6,4,1.0000,1.0000,1.0000,4.0000,15.0000,25,0.6000,0.6004,15.0000,25,0.6000,0.6004,674908.0000,26,25958.0000,26142.2227,674908.0000,26,25958.0000,26145.6385,2,3,1,2
76,2420454,75377509,51771056,10283,0,32750.0000,True,10283,6,4,1.0000,1.0000,1.0000,4.0000,16.0000,26,0.6154,0.6163,16.0000,26,0.6154,0.6163,707658.0000,27,26209.5556,26395.9581,707658.0000,27,26209.5556,26399.4114,2,3,1,2
77,2420455,76007301,51771056,10272,1,37750.0000,True,10272,6,4,0.0000,0.0000,0.0000,4.0000,16.0000,27,0.5926,0.5926,16.0000,27,0.5926,0.5926,745408.0000,28,26621.7143,26816.9576,745408.0000,28,26621.7143,26820.5732,2,3,1,2
78,2420456,76007301,51771056,10273,0,37750.0000,True,10273,6,4,1.0000,1.0000,1.0000,4.0000,17.0000,28,0.6071,0.6077,17.0000,28,0.6071,0.6077,783158.0000,29,27005.4483,27208.9083,783158.0000,29,27005.4483,27212.6745,2,3,1,2
79,2420457,76007301,51771056,10274,1,37750.0000,True,10274,6,4,0.0000,0.0000,0.0000,4.0000,17.0000,29,0.5862,0.5859,17.0000,29,0.5862,0.5859,820908.0000,30,27363.6000,27574.7151,820908.0000,30,27363.6000,27578.6214,2,3,2,3
80,2420458,76007301,51771056,10275,1,37750.0000,True,10275,6,4,1.0000,1.0000,1.0000,4.0000,18.0000,30,0.6000,0.6003,18.0000,30,0.6000,0.6003,858658.0000,31,27698.6452,27916.9081,858658.0000,31,27698.6452,27920.9449,2,3,2,3
81,2420459,76848953,51771056,6803,0,24500.0000,True,6803,6,4,1.0000,1.0000,1.0000,4.0000,19.0000,31,0.6129,0.6137,19.0000,31,0.6129,0.6138,883158.0000,32,27598.6875,27805.4355,883158.0000,32,27598.6875,27809.2524,2,3,2,3
82,2420460,76848953,51771056,6801,1,24500.0000,True,6801,6,4,0.0000,0.0000,0.0000,4.0000,19.0000,32,0.5938,0.5937,19.0000,32,0.5938,0.5937,907658.0000,33,27504.7879,27700.7232,907658.0000,33,27504.7879,27704.3337,2,3,2,3
83,2420461,76848953,51771056,6804,1,24500.0000,True,6804,6,4,1.0000,1.0000,1.0000,4.0000,20.0000,33,0.6061,0.6066,20.0000,33,0.6061,0.6066,932158.0000,34,27416.4118,27602.1747,932158.0000,34,27416.4118,27605.5910,2,3,2,3
84,2420462,76848953,51771056,6802,1,24500.0000,True,6802,6,4,1.0000,1.0000,1.0000,4.0000,21.0000,34,0.6176,0.6187,21.0000,34,0.6176,0.6187,956658.0000,35,27333.0857,27509.2617,956658.0000,35,27333.0857,27512.4951,2,3,2,3
85,2420463,77565937,51771056,7148,1,66750.0000,True,7148,7,15,1.0000,nan,nan,4.0000,22.0000,35,0.6286,0.6301,22.0000,35,0.6286,0.6302,1023408.0000,36,28428.0000,28653.4843,1023408.0000,36,28428.0000,28657.6429,2,3,2,3
86,2420464,77565937,51771056,7147,0,66750.0000,True,7147,7,15,1.0000,1.0000,1.0000,15.0000,23.0000,36,0.6389,0.6409,23.0000,36,0.6389,0.6409,1090158.0000,37,29463.7297,29735.8062,1090158.0000,37,29463.7297,29740.8382,3,4,2,3
87,2420465,77565937,51771056,7145,1,66750.0000,True,7145,7,15,0.0000,0.0000,0.0000,15.0000,23.0000,37,0.6216,0.6227,23.0000,37,0.6216,0.6227,1156908.0000,38,30444.9474,30761.1143,1156908.0000,38,30444.9474,30766.9718,3,4,2,3
88,2420466,77565937,51771056,7149,1,66750.0000,True,7149,7,15,1.0000,1.0000,1.0000,15.0000,24.0000,38,0.6316,0.6332,24.0000,38,0.6316,0.6332,1223658.0000,39,31375.8462,31733.7943,1223658.0000,39,31375.8462,31740.4331,3,4,2,3