In [107]:
import numpy as np
import pandas as pd
pd.set_option('display.float_format', '{:.4f}'.format)
pd.set_option('display.max_rows', 1000)
pd.set_option('display.max_columns', 1000)

In [61]:
%%time
vitrine = pd.read_csv('../data/vitrine.csv')

CPU times: user 30.7 ms, sys: 9.46 ms, total: 40.2 ms
Wall time: 40 ms

In [62]:
vitrine.head()

,id,timestamp,user_id,content_id,content_type_id,answered_correctly,prior_question_elapsed_time,prior_question_had_explanation,part,concept,intention,solving_question,starter,kmean_cluster
0,365541,0,7136928,7900,0,0,nan,NaN,1,nan,nan,nan,nan,0
1,365542,23989,7136928,7876,0,0,21000.0000,False,1,nan,nan,nan,nan,13
2,365543,48079,7136928,175,0,0,20000.0000,False,1,nan,nan,nan,nan,13
3,365544,74835,7136928,1278,0,0,21000.0000,False,2,nan,nan,nan,nan,11
4,365545,192811,7136928,2063,0,0,20000.0000,False,3,nan,nan,nan,nan,9

In [63]:
vitrine[vitrine.user_id == 7136928]

,id,timestamp,user_id,content_id,content_type_id,answered_correctly,prior_question_elapsed_time,prior_question_had_explanation,part,concept,intention,solving_question,starter,kmean_cluster
0,365541,0,7136928,7900,0,0,nan,NaN,1,nan,nan,nan,nan,0
1,365542,23989,7136928,7876,0,0,21000.0000,False,1,nan,nan,nan,nan,13
2,365543,48079,7136928,175,0,0,20000.0000,False,1,nan,nan,nan,nan,13
3,365544,74835,7136928,1278,0,0,21000.0000,False,2,nan,nan,nan,nan,11
4,365545,192811,7136928,2063,0,0,20000.0000,False,3,nan,nan,nan,nan,9
5,365546,192811,7136928,2064,0,0,20000.0000,False,3,nan,nan,nan,nan,9
6,365547,192811,7136928,2065,0,1,20000.0000,False,3,nan,nan,nan,nan,9
7,365548,290933,7136928,3364,0,1,38000.0000,False,4,nan,nan,nan,nan,6
8,365549,290933,7136928,3365,0,0,38000.0000,False,4,nan,nan,nan,nan,6
9,365550,290933,7136928,3363,0,0,38000.0000,False,4,nan,nan,nan,nan,6
10,365551,370847,7136928,2947,0,0,31333.0000,False,4,nan,nan,nan,nan,6
11,365552,370847,7136928,2948,0,0,31333.0000,False,4,nan,nan,nan,nan,6
12,365553,370847,7136928,2946,0,0,31333.0000,False,4,nan,nan,nan,nan,6
13,365554,451200,7136928,2595,0,0,25666.0000,False,4,nan,nan,nan,nan,6
14,365555,451200,7136928,2593,0,0,25666.0000,False,4,nan,nan,nan,nan,6
15,365556,451200,7136928,2594,0,0,25666.0000,False,4,nan,nan,nan,nan,6
16,365557,478945,7136928,4492,0,0,25666.0000,False,5,nan,nan,nan,nan,1
17,365558,510488,7136928,4120,0,0,25000.0000,False,5,nan,nan,nan,nan,1
18,365559,543527,7136928,4696,0,0,29000.0000,False,5,nan,nan,nan,nan,1
19,365560,572018,7136928,6116,0,0,31000.0000,False,5,nan,nan,nan,nan,1
20,365561,621276,7136928,6173,0,0,26000.0000,False,5,nan,nan,nan,nan,1
21,365562,695703,7136928,6370,0,0,47000.0000,False,5,nan,nan,nan,nan,1
22,365563,869639,7136928,6879,0,1,72000.0000,False,6,nan,nan,nan,nan,4
23,365564,869639,7136928,6880,0,0,72000.0000,False,6,nan,nan,nan,nan,4
24,365565,869639,7136928,6877,0,0,72000.0000,False,6,nan,nan,nan,nan,4
25,365566,869639,7136928,6878,0,1,72000.0000,False,6,nan,nan,nan,nan,4
26,365567,1381521,7136928,7216,0,0,42750.0000,False,7,nan,nan,nan,nan,5
27,365568,1381521,7136928,7217,0,1,42750.0000,False,7,nan,nan,nan,nan,5
28,365569,1381521,7136928,7219,0,0,42750.0000,False,7,nan,nan,nan,nan,5
29,365570,1381521,7136928,7218,0,0,42750.0000,False,7,nan,nan,nan,nan,5

In [67]:
vitrine["lag_timestamp"] = vitrine.groupby(['user_id'])['timestamp'].shift()
vitrine["chng_timestamp_pred"] = (vitrine["timestamp"] - vitrine["lag_timestamp"]) / vitrine["timestamp"]

In [ ]:
def get_timestamp_features(vitrine: pd.DataFrame):
    vitrine["lag_timestamp"] = vitrine.groupby(['user_id'])['timestamp'].shift()
    vitrine["chng_timestamp_pred"] = (vitrine["timestamp"] - vitrine["lag_timestamp"]) / vitrine["timestamp"]
    vitrine.drop(["lag_timestamp"], axis = 1, inplace = True)
    return vitrine

In [68]:
vitrine[vitrine.user_id == 7136928]

,id,timestamp,user_id,content_id,content_type_id,answered_correctly,prior_question_elapsed_time,prior_question_had_explanation,part,concept,intention,solving_question,starter,kmean_cluster,lag_timestamp,chng_timestamp_pred
0,365541,0,7136928,7900,0,0,nan,NaN,1,nan,nan,nan,nan,0,nan,nan
1,365542,23989,7136928,7876,0,0,21000.0000,False,1,nan,nan,nan,nan,13,0.0000,1.0000
2,365543,48079,7136928,175,0,0,20000.0000,False,1,nan,nan,nan,nan,13,23989.0000,0.5011
3,365544,74835,7136928,1278,0,0,21000.0000,False,2,nan,nan,nan,nan,11,48079.0000,0.3575
4,365545,192811,7136928,2063,0,0,20000.0000,False,3,nan,nan,nan,nan,9,74835.0000,0.6119
5,365546,192811,7136928,2064,0,0,20000.0000,False,3,nan,nan,nan,nan,9,192811.0000,0.0000
6,365547,192811,7136928,2065,0,1,20000.0000,False,3,nan,nan,nan,nan,9,192811.0000,0.0000
7,365548,290933,7136928,3364,0,1,38000.0000,False,4,nan,nan,nan,nan,6,192811.0000,0.3373
8,365549,290933,7136928,3365,0,0,38000.0000,False,4,nan,nan,nan,nan,6,290933.0000,0.0000
9,365550,290933,7136928,3363,0,0,38000.0000,False,4,nan,nan,nan,nan,6,290933.0000,0.0000
10,365551,370847,7136928,2947,0,0,31333.0000,False,4,nan,nan,nan,nan,6,290933.0000,0.2155
11,365552,370847,7136928,2948,0,0,31333.0000,False,4,nan,nan,nan,nan,6,370847.0000,0.0000
12,365553,370847,7136928,2946,0,0,31333.0000,False,4,nan,nan,nan,nan,6,370847.0000,0.0000
13,365554,451200,7136928,2595,0,0,25666.0000,False,4,nan,nan,nan,nan,6,370847.0000,0.1781
14,365555,451200,7136928,2593,0,0,25666.0000,False,4,nan,nan,nan,nan,6,451200.0000,0.0000
15,365556,451200,7136928,2594,0,0,25666.0000,False,4,nan,nan,nan,nan,6,451200.0000,0.0000
16,365557,478945,7136928,4492,0,0,25666.0000,False,5,nan,nan,nan,nan,1,451200.0000,0.0579
17,365558,510488,7136928,4120,0,0,25000.0000,False,5,nan,nan,nan,nan,1,478945.0000,0.0618
18,365559,543527,7136928,4696,0,0,29000.0000,False,5,nan,nan,nan,nan,1,510488.0000,0.0608
19,365560,572018,7136928,6116,0,0,31000.0000,False,5,nan,nan,nan,nan,1,543527.0000,0.0498
20,365561,621276,7136928,6173,0,0,26000.0000,False,5,nan,nan,nan,nan,1,572018.0000,0.0793
21,365562,695703,7136928,6370,0,0,47000.0000,False,5,nan,nan,nan,nan,1,621276.0000,0.1070
22,365563,869639,7136928,6879,0,1,72000.0000,False,6,nan,nan,nan,nan,4,695703.0000,0.2000
23,365564,869639,7136928,6880,0,0,72000.0000,False,6,nan,nan,nan,nan,4,869639.0000,0.0000
24,365565,869639,7136928,6877,0,0,72000.0000,False,6,nan,nan,nan,nan,4,869639.0000,0.0000
25,365566,869639,7136928,6878,0,1,72000.0000,False,6,nan,nan,nan,nan,4,869639.0000,0.0000
26,365567,1381521,7136928,7216,0,0,42750.0000,False,7,nan,nan,nan,nan,5,869639.0000,0.3705
27,365568,1381521,7136928,7217,0,1,42750.0000,False,7,nan,nan,nan,nan,5,1381521.0000,0.0000
28,365569,1381521,7136928,7219,0,0,42750.0000,False,7,nan,nan,nan,nan,5,1381521.0000,0.0000
29,365570,1381521,7136928,7218,0,0,42750.0000,False,7,nan,nan,nan,nan,5,1381521.0000,0.0000

In [58]:
vitrine.shape

(26892, 14)

In [29]:
%%time
for_train = pd.read_csv('../data/for_train.csv')

CPU times: user 5 ms, sys: 829 µs, total: 5.82 ms
Wall time: 6.88 ms

In [30]:
for_train.head()

       id  target  user_id
0  365548       1  7136928
1  365549       0  7136928
2  365550       0  7136928
3  365551       0  7136928
4  365552       0  7136928

In [50]:
lect_features = pd.read_csv('../data/lect_features.csv')

In [51]:
lect_features.head()

,id,lect_user_part,lect_user_kmean_cluster,lect_user,lect_user_part_concept,lect_user_kmean_cluster_concept,lect_user_concept,lect_user_part_intention,lect_user_kmean_cluster_intention,lect_user_intention,lect_user_part_solving_question,lect_user_kmean_cluster_solving_question,lect_user_solving_question,lect_user_part_starter,lect_user_kmean_cluster_starter,lect_user_starter
0,365548,0,0,0,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000
1,365549,0,0,0,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000
2,365550,0,0,0,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000
3,365551,0,0,0,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000
4,365552,0,0,0,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000

In [12]:
lect_features[lect_features.user_id == 7136928].content_type_id.value_counts()

0    23
Name: content_type_id, dtype: int64

In [14]:
vitrine[vitrine.user_id == 7136928]

,id,timestamp,user_id,content_id,content_type_id,answered_correctly,prior_question_elapsed_time,prior_question_had_explanation,part,concept,intention,solving_question,starter,kmean_cluster
0,365541,0,7136928,7900,0,0,nan,NaN,1,nan,nan,nan,nan,0
1,365542,23989,7136928,7876,0,0,21000.0000,False,1,nan,nan,nan,nan,13
2,365543,48079,7136928,175,0,0,20000.0000,False,1,nan,nan,nan,nan,13
3,365544,74835,7136928,1278,0,0,21000.0000,False,2,nan,nan,nan,nan,11
4,365545,192811,7136928,2063,0,0,20000.0000,False,3,nan,nan,nan,nan,9
5,365546,192811,7136928,2064,0,0,20000.0000,False,3,nan,nan,nan,nan,9
6,365547,192811,7136928,2065,0,1,20000.0000,False,3,nan,nan,nan,nan,9
7,365548,290933,7136928,3364,0,1,38000.0000,False,4,nan,nan,nan,nan,6
8,365549,290933,7136928,3365,0,0,38000.0000,False,4,nan,nan,nan,nan,6
9,365550,290933,7136928,3363,0,0,38000.0000,False,4,nan,nan,nan,nan,6
10,365551,370847,7136928,2947,0,0,31333.0000,False,4,nan,nan,nan,nan,6
11,365552,370847,7136928,2948,0,0,31333.0000,False,4,nan,nan,nan,nan,6
12,365553,370847,7136928,2946,0,0,31333.0000,False,4,nan,nan,nan,nan,6
13,365554,451200,7136928,2595,0,0,25666.0000,False,4,nan,nan,nan,nan,6
14,365555,451200,7136928,2593,0,0,25666.0000,False,4,nan,nan,nan,nan,6
15,365556,451200,7136928,2594,0,0,25666.0000,False,4,nan,nan,nan,nan,6
16,365557,478945,7136928,4492,0,0,25666.0000,False,5,nan,nan,nan,nan,1
17,365558,510488,7136928,4120,0,0,25000.0000,False,5,nan,nan,nan,nan,1
18,365559,543527,7136928,4696,0,0,29000.0000,False,5,nan,nan,nan,nan,1
19,365560,572018,7136928,6116,0,0,31000.0000,False,5,nan,nan,nan,nan,1
20,365561,621276,7136928,6173,0,0,26000.0000,False,5,nan,nan,nan,nan,1
21,365562,695703,7136928,6370,0,0,47000.0000,False,5,nan,nan,nan,nan,1
22,365563,869639,7136928,6879,0,1,72000.0000,False,6,nan,nan,nan,nan,4
23,365564,869639,7136928,6880,0,0,72000.0000,False,6,nan,nan,nan,nan,4
24,365565,869639,7136928,6877,0,0,72000.0000,False,6,nan,nan,nan,nan,4
25,365566,869639,7136928,6878,0,1,72000.0000,False,6,nan,nan,nan,nan,4
26,365567,1381521,7136928,7216,0,0,42750.0000,False,7,nan,nan,nan,nan,5
27,365568,1381521,7136928,7217,0,1,42750.0000,False,7,nan,nan,nan,nan,5
28,365569,1381521,7136928,7219,0,0,42750.0000,False,7,nan,nan,nan,nan,5
29,365570,1381521,7136928,7218,0,0,42750.0000,False,7,nan,nan,nan,nan,5

In [16]:
for_train[for_train.user_id == 7136928]

        id  target  user_id
0   365548       1  7136928
1   365549       0  7136928
2   365550       0  7136928
3   365551       0  7136928
4   365552       0  7136928
5   365553       0  7136928
6   365554       0  7136928
7   365555       0  7136928
8   365556       0  7136928
9   365557       0  7136928
10  365558       0  7136928
11  365559       0  7136928
12  365560       0  7136928
13  365561       0  7136928
14  365562       0  7136928
15  365563       1  7136928
16  365564       0  7136928
17  365565       0  7136928
18  365566       1  7136928
19  365567       0  7136928
20  365568       1  7136928
21  365569       0  7136928
22  365570       0  7136928

In [13]:
lect_features[lect_features.user_id == 7136928]

,id,timestamp,user_id,content_id,content_type_id,answered_correctly,prior_question_elapsed_time,prior_question_had_explanation,part,concept,intention,solving_question,starter,kmean_cluster,lect_user_part,lect_user_kmean_cluster,lect_user,lect_user_part_concept,lect_user_kmean_cluster_concept,lect_user_concept,lect_user_part_intention,lect_user_kmean_cluster_intention,lect_user_intention,lect_user_part_solving_question,lect_user_kmean_cluster_solving_question,lect_user_solving_question,lect_user_part_starter,lect_user_kmean_cluster_starter,lect_user_starter
0,365548,290933,7136928,3364,0,1,38000.0000,False,4,nan,nan,nan,nan,6,0,0,0,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000
1,365549,290933,7136928,3365,0,0,38000.0000,False,4,nan,nan,nan,nan,6,0,0,0,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000
2,365550,290933,7136928,3363,0,0,38000.0000,False,4,nan,nan,nan,nan,6,0,0,0,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000
3,365551,370847,7136928,2947,0,0,31333.0000,False,4,nan,nan,nan,nan,6,0,0,0,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000
4,365552,370847,7136928,2948,0,0,31333.0000,False,4,nan,nan,nan,nan,6,0,0,0,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000
5,365553,370847,7136928,2946,0,0,31333.0000,False,4,nan,nan,nan,nan,6,0,0,0,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000
6,365554,451200,7136928,2595,0,0,25666.0000,False,4,nan,nan,nan,nan,6,0,0,0,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000
7,365555,451200,7136928,2593,0,0,25666.0000,False,4,nan,nan,nan,nan,6,0,0,0,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000
8,365556,451200,7136928,2594,0,0,25666.0000,False,4,nan,nan,nan,nan,6,0,0,0,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000
9,365557,478945,7136928,4492,0,0,25666.0000,False,5,nan,nan,nan,nan,1,0,0,0,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000
10,365558,510488,7136928,4120,0,0,25000.0000,False,5,nan,nan,nan,nan,1,0,0,0,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000
11,365559,543527,7136928,4696,0,0,29000.0000,False,5,nan,nan,nan,nan,1,0,0,0,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000
12,365560,572018,7136928,6116,0,0,31000.0000,False,5,nan,nan,nan,nan,1,0,0,0,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000
13,365561,621276,7136928,6173,0,0,26000.0000,False,5,nan,nan,nan,nan,1,0,0,0,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000
14,365562,695703,7136928,6370,0,0,47000.0000,False,5,nan,nan,nan,nan,1,0,0,0,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000
15,365563,869639,7136928,6879,0,1,72000.0000,False,6,nan,nan,nan,nan,4,0,0,0,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000
16,365564,869639,7136928,6880,0,0,72000.0000,False,6,nan,nan,nan,nan,4,0,0,0,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000
17,365565,869639,7136928,6877,0,0,72000.0000,False,6,nan,nan,nan,nan,4,0,0,0,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000
18,365566,869639,7136928,6878,0,1,72000.0000,False,6,nan,nan,nan,nan,4,0,0,0,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000
19,365567,1381521,7136928,7216,0,0,42750.0000,False,7,nan,nan,nan,nan,5,0,0,0,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000
20,365568,1381521,7136928,7217,0,1,42750.0000,False,7,nan,nan,nan,nan,5,0,0,0,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000
21,365569,1381521,7136928,7219,0,0,42750.0000,False,7,nan,nan,nan,nan,5,0,0,0,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000
22,365570,1381521,7136928,7218,0,0,42750.0000,False,7,nan,nan,nan,nan,5,0,0,0,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000

In [17]:
lect_features.user_id.unique()

array([   7136928,   22318239,   51771056,   53424674,   64764301,
         82977466,   94999086,  106324700,  108822628,  137817081,
        141264833,  217412465,  235233876,  235832844,  237524996,
        252941168,  269060757,  337576619,  348461215,  367840615,
        373598450,  406901956,  409019335,  468048049,  515668244,
        519744118,  550366047,  562186265,  584872865,  616161602,
        616580486,  624222398,  634891095,  658520354,  736371818,
        751871997,  761021960,  761800801,  789631718,  845636456,
        854863946,  878817883,  891642780,  900124353,  946026077,
        951606580,  957818828, 1014937471, 1054103172, 1058520883,
       1071312962, 1102511752, 1138522179, 1143715769, 1154226251,
       1165196379, 1191572932, 1223491298, 1247503470, 1258176764,
       1269589690, 1300608200, 1314342162, 1319452599, 1327647142,
       1420344126, 1443598919, 1462950044, 1485450502, 1490239788,
       1501524575, 1588132322, 1614228863, 1623215417, 1677852077,
       1692505119, 1709810594, 1769609168, 1779147493, 1795317519,
       1807858704, 1866437135, 1875150524, 1920216032, 1923451244,
       1924325164, 1929611621, 1944412002, 1953421360, 1962284087,
       1962993593, 1983836548, 2047398903, 2064777409, 2084988339,
       2088893187, 2099100705, 2100847337, 2143636986, 2145262856])

In [24]:
lect_features[lect_features.lect_user_part > 0]

,id,timestamp,user_id,content_id,content_type_id,answered_correctly,prior_question_elapsed_time,prior_question_had_explanation,part,concept,intention,solving_question,starter,kmean_cluster,lect_user_part,lect_user_kmean_cluster,lect_user,lect_user_part_concept,lect_user_kmean_cluster_concept,lect_user_concept,lect_user_part_intention,lect_user_kmean_cluster_intention,lect_user_intention,lect_user_part_solving_question,lect_user_kmean_cluster_solving_question,lect_user_solving_question,lect_user_part_starter,lect_user_kmean_cluster_starter,lect_user_starter
43,2421137,662286187,51771056,10104,0,1,26250.0000,True,6,nan,nan,nan,nan,4,7,7,17,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000
44,2421138,662286187,51771056,10105,0,1,26250.0000,True,6,nan,nan,nan,nan,4,7,7,17,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000
45,2421139,662286187,51771056,10102,0,1,26250.0000,True,6,nan,nan,nan,nan,4,7,7,17,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000
51,2421145,662714048,51771056,4,0,1,45200.0000,True,1,nan,nan,nan,nan,0,2,2,17,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000
52,2421146,662747442,51771056,1114,0,0,23000.0000,True,2,nan,nan,nan,nan,3,2,2,17,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000
53,2421147,662786619,51771056,1359,0,1,18000.0000,True,2,nan,nan,nan,nan,3,2,2,17,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000
54,2421148,662819608,51771056,904,0,1,16000.0000,True,2,nan,nan,nan,nan,11,2,0,17,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000
55,2421149,662850485,51771056,185,0,1,16000.0000,True,1,nan,nan,nan,nan,0,2,2,17,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000
56,2421151,724467886,51771056,4528,0,1,23000.0000,True,5,nan,nan,nan,nan,1,4,4,18,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000
57,2421152,724498188,51771056,13339,0,0,7000.0000,True,5,nan,nan,nan,nan,1,4,4,18,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000
58,2421153,724510334,51771056,5155,0,1,13000.0000,True,5,nan,nan,nan,nan,1,4,4,18,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000
59,2421154,724521165,51771056,5666,0,1,3000.0000,True,5,nan,nan,nan,nan,1,4,4,18,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000
60,2421155,724538237,51771056,4027,0,0,3000.0000,True,5,nan,nan,nan,nan,1,4,4,18,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000
61,2421156,1112916830,51771056,13359,0,1,8000.0000,True,5,nan,nan,nan,nan,7,4,0,18,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000
62,2421157,1112936481,51771056,8528,0,0,9000.0000,True,5,nan,nan,nan,nan,1,4,4,18,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000
63,2421158,1112954329,51771056,4142,0,0,7000.0000,True,5,nan,nan,nan,nan,1,4,4,18,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000
64,2421159,1497011984,51771056,4137,0,1,4000.0000,True,5,nan,nan,nan,nan,1,4,4,18,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000
65,2421160,1497032674,51771056,13328,0,0,6000.0000,True,5,nan,nan,nan,nan,1,4,4,18,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000
105,3877263,252545880,82977466,5606,0,1,10000.0000,True,5,nan,nan,nan,nan,1,1,1,1,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000
106,3877264,252558349,82977466,6466,0,1,3000.0000,True,5,nan,nan,nan,nan,1,1,1,1,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000
107,3877265,252593872,82977466,6138,0,1,5000.0000,True,5,nan,nan,nan,nan,1,1,1,1,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000
108,3877266,252635841,82977466,6425,0,0,28000.0000,True,5,nan,nan,nan,nan,1,1,1,1,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000
109,3877267,252663832,82977466,8775,0,0,30000.0000,True,5,nan,nan,nan,nan,1,1,1,1,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000
120,3877278,507904546,82977466,5029,0,1,18000.0000,True,5,nan,nan,nan,nan,1,1,1,1,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000
121,3877279,507955703,82977466,6070,0,1,13000.0000,True,5,nan,nan,nan,nan,1,1,1,1,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000
122,3877280,507992277,82977466,4852,0,1,20000.0000,True,5,nan,nan,nan,nan,1,1,1,1,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000
123,3877281,508016033,82977466,9861,0,0,10000.0000,True,5,nan,nan,nan,nan,1,1,1,1,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000
124,3877282,508047286,82977466,4292,0,0,14000.0000,True,5,nan,nan,nan,nan,1,1,1,1,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000
125,4495041,42587452838,94999086,11932,0,1,16000.0000,True,2,nan,nan,nan,nan,11,8,0,18,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000
126,4495042,42587482058,94999086,1124,0,1,15000.0000,True,2,nan,nan,nan,nan,11,8,0,18,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000
127,4495043,42587503319,94999086,783,0,1,16000.0000,True,2,nan,nan,nan,nan,3,8,8,18,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000
128,4495044,42587525377,94999086,781,0,1,15000.0000,True,2,nan,nan,nan,nan,3,8,8,18,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000
129,4495045,42587549993,94999086,11975,0,1,15000.0000,True,2,nan,nan,nan,nan,3,8,8,18,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000
130,4495046,42587578595,94999086,240,0,0,19000.0000,True,2,nan,nan,nan,nan,3,8,8,18,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000
131,4495047,42587604264,94999086,1118,0,0,20000.0000,True,2,nan,nan,nan,nan,3,8,8,18,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000
132,4495048,42587723253,94999086,756,0,0,15000.0000,True,2,nan,nan,nan,nan,11,8,0,18,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000
133,4495050,42587817771,94999086,1112,0,0,16000.0000,True,2,nan,nan,nan,nan,3,9,9,19,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000
134,4495051,42587838892,94999086,240,0,1,19000.0000,True,2,nan,nan,nan,nan,3,9,9,19,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000
135,4495052,42587862104,94999086,11917,0,1,14000.0000,True,2,nan,nan,nan,nan,9,9,0,19,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000
136,4495053,42587928197,94999086,11227,0,0,16000.0000,True,5,nan,nan,nan,nan,1,9,8,19,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000
137,4495054,42587952005,94999086,4985,0,1,15000.0000,True,5,nan,nan,nan,nan,1,9,8,19,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000
138,4495055,42587970983,94999086,9083,0,0,5000.0000,True,5,nan,nan,nan,nan,1,9,8,19,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000
139,4495056,42587987103,94999086,13478,0,1,7000.0000,True,5,nan,nan,nan,nan,1,9,8,19,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000
140,4495057,42588009146,94999086,4727,0,0,5000.0000,True,5,nan,nan,nan,nan,1,9,8,19,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000
141,4495058,42588022398,94999086,5180,0,1,11000.0000,True,5,nan,nan,nan,nan,1,9,8,19,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000
142,4495059,42588061801,94999086,5671,0,0,7000.0000,True,5,nan,nan,nan,nan,1,9,8,19,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000
143,4495061,42588278800,94999086,3944,0,1,30000.0000,True,5,nan,nan,nan,nan,1,10,9,20,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000
144,4495062,42588288117,94999086,5671,0,1,3000.0000,True,5,nan,nan,nan,nan,1,10,9,20,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000
145,4495063,42588310882,94999086,13273,0,0,3000.0000,True,5,nan,nan,nan,nan,1,10,9,20,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000
146,4495064,42588323469,94999086,4421,0,1,18000.0000,True,5,nan,nan,nan,nan,1,10,9,20,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000
147,4495065,42588335770,94999086,9018,0,1,6000.0000,True,5,nan,nan,nan,nan,1,10,9,20,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000
199,6492259,2591264929,141264833,810,0,1,16000.0000,False,2,nan,nan,nan,nan,10,1,0,4,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000
200,6492260,2591285099,141264833,717,0,1,19000.0000,True,2,nan,nan,nan,nan,10,1,0,4,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000
201,6492261,2591325043,141264833,4755,0,1,12000.0000,True,5,nan,nan,nan,nan,1,3,2,4,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000
202,6492262,2591336632,141264833,4497,0,0,10000.0000,True,5,nan,nan,nan,nan,1,3,2,4,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000
203,6492263,2591360502,141264833,8898,0,1,5000.0000,True,5,nan,nan,nan,nan,7,3,1,4,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000
204,6492264,2591383033,141264833,4031,0,0,17000.0000,True,5,nan,nan,nan,nan,1,3,2,4,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000
205,6492265,2591415189,141264833,3855,0,0,15000.0000,True,5,nan,nan,nan,nan,1,3,2,4,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000
206,6492266,2591429493,141264833,4984,0,0,26000.0000,True,5,nan,nan,nan,nan,1,3,2,4,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000
207,6492267,2591445945,141264833,9947,0,0,8000.0000,True,5,nan,nan,nan,nan,1,3,2,4,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000
208,6492268,2591457597,141264833,4700,0,1,10000.0000,True,5,nan,nan,nan,nan,1,3,2,4,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000
209,6492269,2591466345,141264833,5350,0,0,4000.0000,True,5,nan,nan,nan,nan,1,3,2,4,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000
210,6492270,2591490963,141264833,6669,0,0,3000.0000,True,5,nan,nan,nan,nan,1,3,2,4,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000
211,6492271,2591504854,141264833,4800,0,1,7000.0000,True,5,nan,nan,nan,nan,1,3,2,4,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000
212,6492272,2591540569,141264833,6073,0,1,7000.0000,True,5,nan,nan,nan,nan,1,3,2,4,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000
213,6492273,2591579327,141264833,8929,0,0,9000.0000,True,5,nan,nan,nan,nan,16,3,0,4,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000
214,6492274,2591610808,141264833,6005,0,0,32000.0000,True,5,nan,nan,nan,nan,1,3,2,4,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000
215,6492275,2591630418,141264833,4412,0,1,25000.0000,True,5,nan,nan,nan,nan,1,3,2,4,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000
216,6492276,2591655780,141264833,4213,0,0,10000.0000,True,5,nan,nan,nan,nan,16,3,0,4,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000
217,6492277,2591688428,141264833,8800,0,0,18000.0000,True,5,nan,nan,nan,nan,1,3,2,4,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000
218,6492278,3061822169,141264833,4446,0,0,12000.0000,True,5,nan,nan,nan,nan,1,3,2,4,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000
219,6492279,3061852907,141264833,3688,0,1,6000.0000,True,5,nan,nan,nan,nan,1,3,2,4,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000
220,6492280,3061866483,141264833,4110,0,0,24000.0000,True,5,nan,nan,nan,nan,1,3,2,4,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000
221,6492281,3061877473,141264833,8428,0,0,7000.0000,True,5,nan,nan,nan,nan,16,3,0,4,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000
244,10803510,1113495279,235233876,5348,0,1,28000.0000,True,5,nan,nan,nan,nan,1,4,4,6,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000
245,10803511,1113525918,235233876,8518,0,1,11000.0000,True,5,nan,nan,nan,nan,1,4,4,6,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000
246,10803512,1113542036,235233876,3841,0,1,9000.0000,True,5,nan,nan,nan,nan,1,4,4,6,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000
247,10803513,1113577436,235233876,3610,0,1,6000.0000,True,5,nan,nan,nan,nan,1,4,4,6,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000
248,10803514,1113629254,235233876,4457,0,0,14000.0000,True,5,nan,nan,nan,nan,1,4,4,6,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000
249,10803515,1113751008,235233876,9429,0,1,8000.0000,True,5,nan,nan,nan,nan,7,4,0,6,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000
250,10803516,1217722676,235233876,4597,0,0,28000.0000,True,5,nan,nan,nan,nan,1,4,4,6,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000
251,10803517,1217781559,235233876,5445,0,1,11000.0000,True,5,nan,nan,nan,nan,1,4,4,6,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000
252,10803518,1217844534,235233876,4740,0,1,10000.0000,True,5,nan,nan,nan,nan,1,4,4,6,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000
253,10803519,1217873604,235233876,9592,0,1,18000.0000,True,5,nan,nan,nan,nan,16,4,0,6,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000
254,10803520,1217925785,235233876,5287,0,1,13000.0000,True,5,nan,nan,nan,nan,1,4,4,6,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000
255,10803521,1217997618,235233876,5266,0,1,21000.0000,True,5,nan,nan,nan,nan,1,4,4,6,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000
256,10803522,1218041751,235233876,9259,0,1,24000.0000,True,5,nan,nan,nan,nan,1,4,4,6,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000
257,10803523,1353113391,235233876,824,0,1,16000.0000,False,2,nan,nan,nan,nan,11,2,0,6,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000
258,10803524,1353174674,235233876,665,0,0,19000.0000,True,2,nan,nan,nan,nan,11,2,0,6,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000
259,10803525,1353224277,235233876,1192,0,0,18000.0000,True,2,nan,nan,nan,nan,3,2,2,6,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000
260,10803527,1353321117,235233876,1192,0,1,17000.0000,True,2,nan,nan,nan,nan,3,3,3,7,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000
261,10803528,1353361680,235233876,951,0,1,21000.0000,True,2,nan,nan,nan,nan,11,3,0,7,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000
262,10803529,1353399414,235233876,886,0,1,16000.0000,True,2,nan,nan,nan,nan,9,3,0,7,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000
263,10803530,1353452333,235233876,258,0,1,18000.0000,True,2,nan,nan,nan,nan,11,3,0,7,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000
264,10803531,1353504435,235233876,1114,0,1,15000.0000,True,2,nan,nan,nan,nan,3,3,3,7,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000
265,10803532,1353540322,235233876,809,0,1,16000.0000,True,2,nan,nan,nan,nan,3,3,3,7,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000
266,10803533,1353560665,235233876,967,0,1,22000.0000,True,2,nan,nan,nan,nan,9,3,0,7,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000
323,12353716,5034170197,269060757,4982,0,1,85000.0000,True,5,nan,nan,nan,nan,1,1,1,1,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000
324,12353717,5041017780,269060757,9941,0,1,70000.0000,True,5,nan,nan,nan,nan,1,1,1,1,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000
325,12353718,5865713500,269060757,5999,0,0,30000.0000,True,5,nan,nan,nan,nan,1,1,1,1,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000
326,12353719,5935088471,269060757,3854,0,0,36000.0000,True,5,nan,nan,nan,nan,1,1,1,1,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000
327,12353720,5935195001,269060757,4212,0,1,24000.0000,True,5,nan,nan,nan,nan,1,1,1,1,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000
328,12353721,5935332907,269060757,9775,0,0,40000.0000,True,5,nan,nan,nan,nan,1,1,1,1,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000
329,12353722,5976284538,269060757,5906,0,0,76000.0000,True,5,nan,nan,nan,nan,1,1,1,1,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000
330,12353723,6017154666,269060757,3757,0,1,79000.0000,True,5,nan,nan,nan,nan,1,1,1,1,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000
331,12353724,6017280771,269060757,6155,0,0,29000.0000,True,5,nan,nan,nan,nan,1,1,1,1,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000
332,12353725,6017385039,269060757,9018,0,0,88000.0000,True,5,nan,nan,nan,nan,1,1,1,1,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000
333,12353726,6017479685,269060757,3951,0,1,51000.0000,True,5,nan,nan,nan,nan,1,1,1,1,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000
334,12353727,6017553671,269060757,6184,0,0,61000.0000,True,5,nan,nan,nan,nan,1,1,1,1,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000
335,12353728,6237023348,269060757,6116,0,0,46000.0000,True,5,nan,nan,nan,nan,1,1,1,1,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000
336,12353729,6400900001,269060757,8795,0,1,42000.0000,True,5,nan,nan,nan,nan,1,1,1,1,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000
337,12353730,6401098424,269060757,6061,0,0,49000.0000,True,5,nan,nan,nan,nan,1,1,1,1,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000
338,12353731,6528530696,269060757,6668,0,0,41000.0000,True,5,nan,nan,nan,nan,1,1,1,1,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000
339,12353732,6655870329,269060757,9306,0,1,28000.0000,True,5,nan,nan,nan,nan,1,1,1,1,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000
340,12353733,6656057554,269060757,8432,0,0,34000.0000,True,5,nan,nan,nan,nan,1,1,1,1,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000

In [36]:
lect_features[lect_features.user_id == 51771056]

,id,timestamp,user_id,content_id,content_type_id,answered_correctly,prior_question_elapsed_time,prior_question_had_explanation,part,concept,intention,solving_question,starter,kmean_cluster,lect_user_part,lect_user_kmean_cluster,lect_user,lect_user_part_concept,lect_user_kmean_cluster_concept,lect_user_concept,lect_user_part_intention,lect_user_kmean_cluster_intention,lect_user_intention,lect_user_part_solving_question,lect_user_kmean_cluster_solving_question,lect_user_solving_question,lect_user_part_starter,lect_user_kmean_cluster_starter,lect_user_starter
43,2421137,662286187,51771056,10104,0,1,26250.0000,True,6,nan,nan,nan,nan,4,7,7,17,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000
44,2421138,662286187,51771056,10105,0,1,26250.0000,True,6,nan,nan,nan,nan,4,7,7,17,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000
45,2421139,662286187,51771056,10102,0,1,26250.0000,True,6,nan,nan,nan,nan,4,7,7,17,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000
46,2421140,662626800,51771056,6962,0,1,11500.0000,True,7,nan,nan,nan,nan,15,0,0,17,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000
47,2421141,662626800,51771056,6965,0,1,11500.0000,True,7,nan,nan,nan,nan,15,0,0,17,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000
48,2421142,662626800,51771056,6963,0,1,11500.0000,True,7,nan,nan,nan,nan,15,0,0,17,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000
49,2421143,662626800,51771056,6964,0,1,11500.0000,True,7,nan,nan,nan,nan,15,0,0,17,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000
50,2421144,662626800,51771056,6961,0,0,11500.0000,True,7,nan,nan,nan,nan,15,0,0,17,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000
51,2421145,662714048,51771056,4,0,1,45200.0000,True,1,nan,nan,nan,nan,0,2,2,17,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000
52,2421146,662747442,51771056,1114,0,0,23000.0000,True,2,nan,nan,nan,nan,3,2,2,17,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000
53,2421147,662786619,51771056,1359,0,1,18000.0000,True,2,nan,nan,nan,nan,3,2,2,17,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000
54,2421148,662819608,51771056,904,0,1,16000.0000,True,2,nan,nan,nan,nan,11,2,0,17,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000
55,2421149,662850485,51771056,185,0,1,16000.0000,True,1,nan,nan,nan,nan,0,2,2,17,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000
56,2421151,724467886,51771056,4528,0,1,23000.0000,True,5,nan,nan,nan,nan,1,4,4,18,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000
57,2421152,724498188,51771056,13339,0,0,7000.0000,True,5,nan,nan,nan,nan,1,4,4,18,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000
58,2421153,724510334,51771056,5155,0,1,13000.0000,True,5,nan,nan,nan,nan,1,4,4,18,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000
59,2421154,724521165,51771056,5666,0,1,3000.0000,True,5,nan,nan,nan,nan,1,4,4,18,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000
60,2421155,724538237,51771056,4027,0,0,3000.0000,True,5,nan,nan,nan,nan,1,4,4,18,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000
61,2421156,1112916830,51771056,13359,0,1,8000.0000,True,5,nan,nan,nan,nan,7,4,0,18,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000
62,2421157,1112936481,51771056,8528,0,0,9000.0000,True,5,nan,nan,nan,nan,1,4,4,18,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000
63,2421158,1112954329,51771056,4142,0,0,7000.0000,True,5,nan,nan,nan,nan,1,4,4,18,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000
64,2421159,1497011984,51771056,4137,0,1,4000.0000,True,5,nan,nan,nan,nan,1,4,4,18,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000
65,2421160,1497032674,51771056,13328,0,0,6000.0000,True,5,nan,nan,nan,nan,1,4,4,18,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000

In [39]:
lect_features[lect_features.user_id == 51771056]

,id,timestamp,user_id,content_id,content_type_id,answered_correctly,prior_question_elapsed_time,prior_question_had_explanation,part,concept,intention,solving_question,starter,kmean_cluster,lect_user_part,lect_user_kmean_cluster,lect_user,lect_user_part_concept,lect_user_kmean_cluster_concept,lect_user_concept,lect_user_part_intention,lect_user_kmean_cluster_intention,lect_user_intention,lect_user_part_solving_question,lect_user_kmean_cluster_solving_question,lect_user_solving_question,lect_user_part_starter,lect_user_kmean_cluster_starter,lect_user_starter
50,2420428,0,51771056,10733,0,1,14333.0000,True,4,nan,nan,nan,nan,12,0,0,0,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000
51,2420429,0,51771056,10732,0,0,14333.0000,True,4,nan,nan,nan,nan,12,0,0,0,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000
52,2420430,0,51771056,10731,0,1,14333.0000,True,4,nan,nan,nan,nan,12,0,0,0,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000
53,2420431,147940,51771056,2820,0,1,14333.0000,True,4,nan,nan,nan,nan,12,0,0,0,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000
54,2420432,147940,51771056,2819,0,1,14333.0000,True,4,nan,nan,nan,nan,12,0,0,0,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000
55,2420433,147940,51771056,2818,0,0,14333.0000,True,4,nan,nan,nan,nan,12,0,0,0,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000
56,2420434,301126,51771056,2623,0,1,24000.0000,True,4,nan,nan,nan,nan,12,0,0,0,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000
57,2420435,301126,51771056,2624,0,1,24000.0000,True,4,nan,nan,nan,nan,12,0,0,0,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000
58,2420436,301126,51771056,2625,0,0,24000.0000,True,4,nan,nan,nan,nan,12,0,0,0,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000
59,2420437,468350,51771056,2940,0,0,22666.0000,True,4,nan,nan,nan,nan,6,0,0,0,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000
60,2420438,468350,51771056,2942,0,0,22666.0000,True,4,nan,nan,nan,nan,6,0,0,0,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000
61,2420439,468350,51771056,2941,0,1,22666.0000,True,4,nan,nan,nan,nan,6,0,0,0,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000
62,2420440,782950,51771056,3228,0,1,23666.0000,True,4,nan,nan,nan,nan,6,0,0,0,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000
63,2420441,782950,51771056,3229,0,1,23666.0000,True,4,nan,nan,nan,nan,6,0,0,0,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000
64,2420442,782950,51771056,3230,0,0,23666.0000,True,4,nan,nan,nan,nan,6,0,0,0,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000
65,2420443,29098393,51771056,10857,0,0,16666.0000,True,6,nan,nan,nan,nan,4,0,0,0,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000
66,2420444,29098393,51771056,10858,0,0,16666.0000,True,6,nan,nan,nan,nan,4,0,0,0,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000
67,2420445,29098393,51771056,10855,0,1,16666.0000,True,6,nan,nan,nan,nan,4,0,0,0,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000
68,2420446,29098393,51771056,10856,0,0,16666.0000,True,6,nan,nan,nan,nan,4,0,0,0,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000
69,2420447,75088427,51771056,10834,0,1,53250.0000,True,6,nan,nan,nan,nan,4,0,0,0,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000
70,2420448,75088427,51771056,10833,0,1,53250.0000,True,6,nan,nan,nan,nan,4,0,0,0,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000
71,2420449,75088427,51771056,10831,0,0,53250.0000,True,6,nan,nan,nan,nan,4,0,0,0,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000
72,2420450,75088427,51771056,10832,0,1,53250.0000,True,6,nan,nan,nan,nan,4,0,0,0,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000
73,2420451,75377509,51771056,10282,0,1,32750.0000,True,6,nan,nan,nan,nan,4,0,0,0,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000
74,2420452,75377509,51771056,10281,0,1,32750.0000,True,6,nan,nan,nan,nan,4,0,0,0,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000
75,2420453,75377509,51771056,10280,0,1,32750.0000,True,6,nan,nan,nan,nan,4,0,0,0,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000
76,2420454,75377509,51771056,10283,0,0,32750.0000,True,6,nan,nan,nan,nan,4,0,0,0,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000
77,2420455,76007301,51771056,10272,0,1,37750.0000,True,6,nan,nan,nan,nan,4,0,0,0,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000
78,2420456,76007301,51771056,10273,0,0,37750.0000,True,6,nan,nan,nan,nan,4,0,0,0,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000
79,2420457,76007301,51771056,10274,0,1,37750.0000,True,6,nan,nan,nan,nan,4,0,0,0,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000
80,2420458,76007301,51771056,10275,0,1,37750.0000,True,6,nan,nan,nan,nan,4,0,0,0,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000
81,2420459,76848953,51771056,6803,0,0,24500.0000,True,6,nan,nan,nan,nan,4,0,0,0,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000
82,2420460,76848953,51771056,6801,0,1,24500.0000,True,6,nan,nan,nan,nan,4,0,0,0,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000
83,2420461,76848953,51771056,6804,0,1,24500.0000,True,6,nan,nan,nan,nan,4,0,0,0,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000
84,2420462,76848953,51771056,6802,0,1,24500.0000,True,6,nan,nan,nan,nan,4,0,0,0,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000
85,2420463,77565937,51771056,7148,0,1,66750.0000,True,7,nan,nan,nan,nan,15,0,0,0,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000
86,2420464,77565937,51771056,7147,0,0,66750.0000,True,7,nan,nan,nan,nan,15,0,0,0,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000
87,2420465,77565937,51771056,7145,0,1,66750.0000,True,7,nan,nan,nan,nan,15,0,0,0,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000
88,2420466,77565937,51771056,7149,0,1,66750.0000,True,7,nan,nan,nan,nan,15,0,0,0,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000
89,2420467,77565937,51771056,7146,0,0,66750.0000,True,7,nan,nan,nan,nan,15,0,0,0,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000
90,2420468,78463792,51771056,6962,0,1,87400.0000,True,7,nan,nan,nan,nan,15,0,0,0,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000
91,2420469,78463792,51771056,6963,0,1,87400.0000,True,7,nan,nan,nan,nan,15,0,0,0,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000
92,2420470,78463792,51771056,6964,0,1,87400.0000,True,7,nan,nan,nan,nan,15,0,0,0,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000
93,2420471,78463792,51771056,6961,0,0,87400.0000,True,7,nan,nan,nan,nan,15,0,0,0,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000
94,2420472,78463792,51771056,6965,0,1,87400.0000,True,7,nan,nan,nan,nan,15,0,0,0,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000
95,2420473,79487416,51771056,7390,0,0,105400.0000,True,7,nan,nan,nan,nan,15,0,0,0,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000
96,2420474,79487416,51771056,7388,0,0,105400.0000,True,7,nan,nan,nan,nan,15,0,0,0,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000
97,2420475,79487416,51771056,7389,0,1,105400.0000,True,7,nan,nan,nan,nan,15,0,0,0,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000
98,2420476,79487416,51771056,7386,0,0,105400.0000,True,7,nan,nan,nan,nan,15,0,0,0,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000
99,2420477,79487416,51771056,7387,0,1,105400.0000,True,7,nan,nan,nan,nan,15,0,0,0,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000
100,2420478,85453640,51771056,22711,1,-1,nan,False,6,1.0000,0.0000,0.0000,0.0000,4,1,1,1,1.0000,1.0000,1.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000
101,2420479,85527879,51771056,7981,0,1,123000.0000,True,1,nan,nan,nan,nan,13,0,0,1,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000
102,2420480,85593707,51771056,6,0,0,24000.0000,True,1,nan,nan,nan,nan,13,0,0,1,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000
103,2420481,85664366,51771056,10415,0,1,25000.0000,True,1,nan,nan,nan,nan,0,0,0,1,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000
104,2420482,85710815,51771056,199,0,1,26000.0000,True,2,nan,nan,nan,nan,3,0,0,1,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000
105,2420483,85752474,51771056,1103,0,1,16000.0000,True,2,nan,nan,nan,nan,3,0,0,1,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000
106,2420484,85812854,51771056,981,0,1,19000.0000,True,2,nan,nan,nan,nan,11,0,0,1,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000
107,2420485,85861409,51771056,279,0,1,20000.0000,True,2,nan,nan,nan,nan,11,0,0,1,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000
108,2420486,85904659,51771056,1310,0,1,18000.0000,True,2,nan,nan,nan,nan,3,0,0,1,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000
109,2420487,85944038,51771056,242,0,1,17000.0000,True,2,nan,nan,nan,nan,3,0,0,1,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000
110,2420488,86035097,51771056,10733,0,1,18000.0000,True,4,nan,nan,nan,nan,12,0,0,1,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000
111,2420489,86035097,51771056,10732,0,1,18000.0000,True,4,nan,nan,nan,nan,12,0,0,1,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000
112,2420490,86035097,51771056,10731,0,1,18000.0000,True,4,nan,nan,nan,nan,12,0,0,1,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000
113,2420491,86132187,51771056,2819,0,0,25333.0000,True,4,nan,nan,nan,nan,12,0,0,1,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000
114,2420492,86132187,51771056,2818,0,1,25333.0000,True,4,nan,nan,nan,nan,12,0,0,1,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000
115,2420493,86132187,51771056,2820,0,1,25333.0000,True,4,nan,nan,nan,nan,12,0,0,1,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000
116,2420494,149614692,51771056,1941,0,1,20666.0000,True,3,nan,nan,nan,nan,9,0,0,1,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000
117,2420495,149614692,51771056,1942,0,1,20666.0000,True,3,nan,nan,nan,nan,9,0,0,1,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000
118,2420496,149614692,51771056,1940,0,0,20666.0000,True,3,nan,nan,nan,nan,9,0,0,1,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000
119,2420497,149810235,51771056,2044,0,0,14667.0000,True,3,nan,nan,nan,nan,8,0,0,1,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000
120,2420498,149810235,51771056,2043,0,1,14667.0000,True,3,nan,nan,nan,nan,8,0,0,1,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000
121,2420499,149810235,51771056,2042,0,1,14667.0000,True,3,nan,nan,nan,nan,8,0,0,1,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000
122,2420500,150020296,51771056,2119,0,0,22667.0000,True,3,nan,nan,nan,nan,2,0,0,1,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000
123,2420501,150020296,51771056,2118,0,0,22667.0000,True,3,nan,nan,nan,nan,2,0,0,1,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000
124,2420502,150020296,51771056,2117,0,0,22667.0000,True,3,nan,nan,nan,nan,2,0,0,1,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000
125,2420503,150184468,51771056,2258,0,1,29333.0000,True,3,nan,nan,nan,nan,2,0,0,1,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000
126,2420504,150184468,51771056,2257,0,0,29333.0000,True,3,nan,nan,nan,nan,2,0,0,1,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000
127,2420505,150184468,51771056,2259,0,0,29333.0000,True,3,nan,nan,nan,nan,2,0,0,1,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000
128,2420506,150435720,51771056,1876,0,0,24333.0000,True,3,nan,nan,nan,nan,2,0,0,1,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000
129,2420507,150435720,51771056,1874,0,0,24333.0000,True,3,nan,nan,nan,nan,2,0,0,1,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000
130,2420508,150435720,51771056,1875,0,0,24333.0000,True,3,nan,nan,nan,nan,2,0,0,1,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000
131,2420509,150817666,51771056,23815,1,-1,nan,False,3,1.0000,0.0000,0.0000,0.0000,2,1,1,2,1.0000,1.0000,2.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000
132,2420510,153633437,51771056,7185,0,1,43667.0000,True,7,nan,nan,nan,nan,5,0,0,2,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000
133,2420511,153633437,51771056,7186,0,1,43667.0000,True,7,nan,nan,nan,nan,5,0,0,2,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000
134,2420512,153633437,51771056,7184,0,1,43667.0000,True,7,nan,nan,nan,nan,5,0,0,2,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000
135,2420513,154513160,51771056,7712,0,1,63333.0000,True,7,nan,nan,nan,nan,15,0,0,2,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000
136,2420514,154513160,51771056,7709,0,1,63333.0000,True,7,nan,nan,nan,nan,15,0,0,2,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000
137,2420515,154513160,51771056,7710,0,0,63333.0000,True,7,nan,nan,nan,nan,15,0,0,2,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000
138,2420516,154513160,51771056,7711,0,1,63333.0000,True,7,nan,nan,nan,nan,15,0,0,2,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000
139,2420517,154513160,51771056,7713,0,1,63333.0000,True,7,nan,nan,nan,nan,15,0,0,2,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000
140,2420518,155070820,51771056,7823,0,0,56600.0000,True,7,nan,nan,nan,nan,5,0,0,2,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000
141,2420519,155070820,51771056,7821,0,0,56600.0000,True,7,nan,nan,nan,nan,5,0,0,2,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000
142,2420520,155070820,51771056,7822,0,1,56600.0000,True,7,nan,nan,nan,nan,5,0,0,2,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000
143,2420521,155070820,51771056,7820,0,0,56600.0000,True,7,nan,nan,nan,nan,5,0,0,2,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000
144,2420522,202159396,51771056,1980,0,0,92750.0000,True,3,nan,nan,nan,nan,2,1,1,2,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000
145,2420523,202159396,51771056,1979,0,1,92750.0000,True,3,nan,nan,nan,nan,2,1,1,2,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000
146,2420524,202159396,51771056,1981,0,1,92750.0000,True,3,nan,nan,nan,nan,2,1,1,2,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000
147,2420525,202278675,51771056,1605,0,1,29333.0000,True,3,nan,nan,nan,nan,2,1,1,2,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000
148,2420526,202278675,51771056,1606,0,1,29333.0000,True,3,nan,nan,nan,nan,2,1,1,2,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000
149,2420527,202278675,51771056,1604,0,0,29333.0000,True,3,nan,nan,nan,nan,2,1,1,2,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000
150,2420528,202414052,51771056,1879,0,1,22666.0000,True,3,nan,nan,nan,nan,2,1,1,2,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000
151,2420529,202414052,51771056,1877,0,1,22666.0000,True,3,nan,nan,nan,nan,2,1,1,2,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000
152,2420530,202414052,51771056,1878,0,1,22666.0000,True,3,nan,nan,nan,nan,2,1,1,2,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000
153,2420531,202584924,51771056,2484,0,0,25333.0000,True,3,nan,nan,nan,nan,2,1,1,2,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000
154,2420532,202584924,51771056,2482,0,0,25333.0000,True,3,nan,nan,nan,nan,2,1,1,2,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000
155,2420533,202584924,51771056,2483,0,1,25333.0000,True,3,nan,nan,nan,nan,2,1,1,2,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000
156,2420534,202721519,51771056,2087,0,1,26000.0000,True,3,nan,nan,nan,nan,2,1,1,2,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000
157,2420535,202721519,51771056,2088,0,1,26000.0000,True,3,nan,nan,nan,nan,2,1,1,2,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000
158,2420536,202721519,51771056,2089,0,1,26000.0000,True,3,nan,nan,nan,nan,2,1,1,2,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000
159,2420537,203030959,51771056,10081,0,1,23000.0000,True,6,nan,nan,nan,nan,4,1,1,2,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000
160,2420538,203030959,51771056,10079,0,0,23000.0000,True,6,nan,nan,nan,nan,4,1,1,2,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000
161,2420539,203030959,51771056,10080,0,1,23000.0000,True,6,nan,nan,nan,nan,4,1,1,2,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000
162,2420540,203030959,51771056,10078,0,1,23000.0000,True,6,nan,nan,nan,nan,4,1,1,2,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000
163,2420541,203378000,51771056,6519,0,0,39750.0000,True,6,nan,nan,nan,nan,4,1,1,2,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000
164,2420542,203378000,51771056,6520,0,0,39750.0000,True,6,nan,nan,nan,nan,4,1,1,2,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000
165,2420543,203378000,51771056,6517,0,1,39750.0000,True,6,nan,nan,nan,nan,4,1,1,2,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000
166,2420544,203378000,51771056,6518,0,1,39750.0000,True,6,nan,nan,nan,nan,4,1,1,2,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000

In [52]:
lect_features[lect_features.id.isin([2421137 + i for i in range(24)])]

,id,lect_user_part,lect_user_kmean_cluster,lect_user,lect_user_part_concept,lect_user_kmean_cluster_concept,lect_user_concept,lect_user_part_intention,lect_user_kmean_cluster_intention,lect_user_intention,lect_user_part_solving_question,lect_user_kmean_cluster_solving_question,lect_user_solving_question,lect_user_part_starter,lect_user_kmean_cluster_starter,lect_user_starter
43,2421137,7,7,17,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000
44,2421138,7,7,17,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000
45,2421139,7,7,17,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000
46,2421140,0,0,17,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000
47,2421141,0,0,17,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000
48,2421142,0,0,17,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000
49,2421143,0,0,17,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000
50,2421144,0,0,17,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000
51,2421145,2,2,17,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000
52,2421146,2,2,17,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000
53,2421147,2,2,17,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000
54,2421148,2,0,17,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000
55,2421149,2,2,17,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000
56,2421151,4,4,18,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000
57,2421152,4,4,18,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000
58,2421153,4,4,18,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000
59,2421154,4,4,18,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000
60,2421155,4,4,18,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000
61,2421156,4,0,18,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000
62,2421157,4,4,18,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000
63,2421158,4,4,18,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000
64,2421159,4,4,18,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000
65,2421160,4,4,18,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000

In [26]:
vitrine[vitrine.user_id == 51771056]

,id,timestamp,user_id,content_id,content_type_id,answered_correctly,prior_question_elapsed_time,prior_question_had_explanation,part,concept,intention,solving_question,starter,kmean_cluster
50,2420428,0,51771056,10733,0,1,14333.0000,True,4,nan,nan,nan,nan,12
51,2420429,0,51771056,10732,0,0,14333.0000,True,4,nan,nan,nan,nan,12
52,2420430,0,51771056,10731,0,1,14333.0000,True,4,nan,nan,nan,nan,12
53,2420431,147940,51771056,2820,0,1,14333.0000,True,4,nan,nan,nan,nan,12
54,2420432,147940,51771056,2819,0,1,14333.0000,True,4,nan,nan,nan,nan,12
55,2420433,147940,51771056,2818,0,0,14333.0000,True,4,nan,nan,nan,nan,12
56,2420434,301126,51771056,2623,0,1,24000.0000,True,4,nan,nan,nan,nan,12
57,2420435,301126,51771056,2624,0,1,24000.0000,True,4,nan,nan,nan,nan,12
58,2420436,301126,51771056,2625,0,0,24000.0000,True,4,nan,nan,nan,nan,12
59,2420437,468350,51771056,2940,0,0,22666.0000,True,4,nan,nan,nan,nan,6
60,2420438,468350,51771056,2942,0,0,22666.0000,True,4,nan,nan,nan,nan,6
61,2420439,468350,51771056,2941,0,1,22666.0000,True,4,nan,nan,nan,nan,6
62,2420440,782950,51771056,3228,0,1,23666.0000,True,4,nan,nan,nan,nan,6
63,2420441,782950,51771056,3229,0,1,23666.0000,True,4,nan,nan,nan,nan,6
64,2420442,782950,51771056,3230,0,0,23666.0000,True,4,nan,nan,nan,nan,6
65,2420443,29098393,51771056,10857,0,0,16666.0000,True,6,nan,nan,nan,nan,4
66,2420444,29098393,51771056,10858,0,0,16666.0000,True,6,nan,nan,nan,nan,4
67,2420445,29098393,51771056,10855,0,1,16666.0000,True,6,nan,nan,nan,nan,4
68,2420446,29098393,51771056,10856,0,0,16666.0000,True,6,nan,nan,nan,nan,4
69,2420447,75088427,51771056,10834,0,1,53250.0000,True,6,nan,nan,nan,nan,4
70,2420448,75088427,51771056,10833,0,1,53250.0000,True,6,nan,nan,nan,nan,4
71,2420449,75088427,51771056,10831,0,0,53250.0000,True,6,nan,nan,nan,nan,4
72,2420450,75088427,51771056,10832,0,1,53250.0000,True,6,nan,nan,nan,nan,4
73,2420451,75377509,51771056,10282,0,1,32750.0000,True,6,nan,nan,nan,nan,4
74,2420452,75377509,51771056,10281,0,1,32750.0000,True,6,nan,nan,nan,nan,4
75,2420453,75377509,51771056,10280,0,1,32750.0000,True,6,nan,nan,nan,nan,4
76,2420454,75377509,51771056,10283,0,0,32750.0000,True,6,nan,nan,nan,nan,4
77,2420455,76007301,51771056,10272,0,1,37750.0000,True,6,nan,nan,nan,nan,4
78,2420456,76007301,51771056,10273,0,0,37750.0000,True,6,nan,nan,nan,nan,4
79,2420457,76007301,51771056,10274,0,1,37750.0000,True,6,nan,nan,nan,nan,4
80,2420458,76007301,51771056,10275,0,1,37750.0000,True,6,nan,nan,nan,nan,4
81,2420459,76848953,51771056,6803,0,0,24500.0000,True,6,nan,nan,nan,nan,4
82,2420460,76848953,51771056,6801,0,1,24500.0000,True,6,nan,nan,nan,nan,4
83,2420461,76848953,51771056,6804,0,1,24500.0000,True,6,nan,nan,nan,nan,4
84,2420462,76848953,51771056,6802,0,1,24500.0000,True,6,nan,nan,nan,nan,4
85,2420463,77565937,51771056,7148,0,1,66750.0000,True,7,nan,nan,nan,nan,15
86,2420464,77565937,51771056,7147,0,0,66750.0000,True,7,nan,nan,nan,nan,15
87,2420465,77565937,51771056,7145,0,1,66750.0000,True,7,nan,nan,nan,nan,15
88,2420466,77565937,51771056,7149,0,1,66750.0000,True,7,nan,nan,nan,nan,15
89,2420467,77565937,51771056,7146,0,0,66750.0000,True,7,nan,nan,nan,nan,15
90,2420468,78463792,51771056,6962,0,1,87400.0000,True,7,nan,nan,nan,nan,15
91,2420469,78463792,51771056,6963,0,1,87400.0000,True,7,nan,nan,nan,nan,15
92,2420470,78463792,51771056,6964,0,1,87400.0000,True,7,nan,nan,nan,nan,15
93,2420471,78463792,51771056,6961,0,0,87400.0000,True,7,nan,nan,nan,nan,15
94,2420472,78463792,51771056,6965,0,1,87400.0000,True,7,nan,nan,nan,nan,15
95,2420473,79487416,51771056,7390,0,0,105400.0000,True,7,nan,nan,nan,nan,15
96,2420474,79487416,51771056,7388,0,0,105400.0000,True,7,nan,nan,nan,nan,15
97,2420475,79487416,51771056,7389,0,1,105400.0000,True,7,nan,nan,nan,nan,15
98,2420476,79487416,51771056,7386,0,0,105400.0000,True,7,nan,nan,nan,nan,15
99,2420477,79487416,51771056,7387,0,1,105400.0000,True,7,nan,nan,nan,nan,15
100,2420478,85453640,51771056,22711,1,-1,nan,False,6,1.0000,0.0000,0.0000,0.0000,4
101,2420479,85527879,51771056,7981,0,1,123000.0000,True,1,nan,nan,nan,nan,13
102,2420480,85593707,51771056,6,0,0,24000.0000,True,1,nan,nan,nan,nan,13
103,2420481,85664366,51771056,10415,0,1,25000.0000,True,1,nan,nan,nan,nan,0
104,2420482,85710815,51771056,199,0,1,26000.0000,True,2,nan,nan,nan,nan,3
105,2420483,85752474,51771056,1103,0,1,16000.0000,True,2,nan,nan,nan,nan,3
106,2420484,85812854,51771056,981,0,1,19000.0000,True,2,nan,nan,nan,nan,11
107,2420485,85861409,51771056,279,0,1,20000.0000,True,2,nan,nan,nan,nan,11
108,2420486,85904659,51771056,1310,0,1,18000.0000,True,2,nan,nan,nan,nan,3
109,2420487,85944038,51771056,242,0,1,17000.0000,True,2,nan,nan,nan,nan,3
110,2420488,86035097,51771056,10733,0,1,18000.0000,True,4,nan,nan,nan,nan,12
111,2420489,86035097,51771056,10732,0,1,18000.0000,True,4,nan,nan,nan,nan,12
112,2420490,86035097,51771056,10731,0,1,18000.0000,True,4,nan,nan,nan,nan,12
113,2420491,86132187,51771056,2819,0,0,25333.0000,True,4,nan,nan,nan,nan,12
114,2420492,86132187,51771056,2818,0,1,25333.0000,True,4,nan,nan,nan,nan,12
115,2420493,86132187,51771056,2820,0,1,25333.0000,True,4,nan,nan,nan,nan,12
116,2420494,149614692,51771056,1941,0,1,20666.0000,True,3,nan,nan,nan,nan,9
117,2420495,149614692,51771056,1942,0,1,20666.0000,True,3,nan,nan,nan,nan,9
118,2420496,149614692,51771056,1940,0,0,20666.0000,True,3,nan,nan,nan,nan,9
119,2420497,149810235,51771056,2044,0,0,14667.0000,True,3,nan,nan,nan,nan,8
120,2420498,149810235,51771056,2043,0,1,14667.0000,True,3,nan,nan,nan,nan,8
121,2420499,149810235,51771056,2042,0,1,14667.0000,True,3,nan,nan,nan,nan,8
122,2420500,150020296,51771056,2119,0,0,22667.0000,True,3,nan,nan,nan,nan,2
123,2420501,150020296,51771056,2118,0,0,22667.0000,True,3,nan,nan,nan,nan,2
124,2420502,150020296,51771056,2117,0,0,22667.0000,True,3,nan,nan,nan,nan,2
125,2420503,150184468,51771056,2258,0,1,29333.0000,True,3,nan,nan,nan,nan,2
126,2420504,150184468,51771056,2257,0,0,29333.0000,True,3,nan,nan,nan,nan,2
127,2420505,150184468,51771056,2259,0,0,29333.0000,True,3,nan,nan,nan,nan,2
128,2420506,150435720,51771056,1876,0,0,24333.0000,True,3,nan,nan,nan,nan,2
129,2420507,150435720,51771056,1874,0,0,24333.0000,True,3,nan,nan,nan,nan,2
130,2420508,150435720,51771056,1875,0,0,24333.0000,True,3,nan,nan,nan,nan,2
131,2420509,150817666,51771056,23815,1,-1,nan,False,3,1.0000,0.0000,0.0000,0.0000,2
132,2420510,153633437,51771056,7185,0,1,43667.0000,True,7,nan,nan,nan,nan,5
133,2420511,153633437,51771056,7186,0,1,43667.0000,True,7,nan,nan,nan,nan,5
134,2420512,153633437,51771056,7184,0,1,43667.0000,True,7,nan,nan,nan,nan,5
135,2420513,154513160,51771056,7712,0,1,63333.0000,True,7,nan,nan,nan,nan,15
136,2420514,154513160,51771056,7709,0,1,63333.0000,True,7,nan,nan,nan,nan,15
137,2420515,154513160,51771056,7710,0,0,63333.0000,True,7,nan,nan,nan,nan,15
138,2420516,154513160,51771056,7711,0,1,63333.0000,True,7,nan,nan,nan,nan,15
139,2420517,154513160,51771056,7713,0,1,63333.0000,True,7,nan,nan,nan,nan,15
140,2420518,155070820,51771056,7823,0,0,56600.0000,True,7,nan,nan,nan,nan,5
141,2420519,155070820,51771056,7821,0,0,56600.0000,True,7,nan,nan,nan,nan,5
142,2420520,155070820,51771056,7822,0,1,56600.0000,True,7,nan,nan,nan,nan,5
143,2420521,155070820,51771056,7820,0,0,56600.0000,True,7,nan,nan,nan,nan,5
144,2420522,202159396,51771056,1980,0,0,92750.0000,True,3,nan,nan,nan,nan,2
145,2420523,202159396,51771056,1979,0,1,92750.0000,True,3,nan,nan,nan,nan,2
146,2420524,202159396,51771056,1981,0,1,92750.0000,True,3,nan,nan,nan,nan,2
147,2420525,202278675,51771056,1605,0,1,29333.0000,True,3,nan,nan,nan,nan,2
148,2420526,202278675,51771056,1606,0,1,29333.0000,True,3,nan,nan,nan,nan,2
149,2420527,202278675,51771056,1604,0,0,29333.0000,True,3,nan,nan,nan,nan,2
150,2420528,202414052,51771056,1879,0,1,22666.0000,True,3,nan,nan,nan,nan,2
151,2420529,202414052,51771056,1877,0,1,22666.0000,True,3,nan,nan,nan,nan,2
152,2420530,202414052,51771056,1878,0,1,22666.0000,True,3,nan,nan,nan,nan,2
153,2420531,202584924,51771056,2484,0,0,25333.0000,True,3,nan,nan,nan,nan,2
154,2420532,202584924,51771056,2482,0,0,25333.0000,True,3,nan,nan,nan,nan,2
155,2420533,202584924,51771056,2483,0,1,25333.0000,True,3,nan,nan,nan,nan,2
156,2420534,202721519,51771056,2087,0,1,26000.0000,True,3,nan,nan,nan,nan,2
157,2420535,202721519,51771056,2088,0,1,26000.0000,True,3,nan,nan,nan,nan,2
158,2420536,202721519,51771056,2089,0,1,26000.0000,True,3,nan,nan,nan,nan,2
159,2420537,203030959,51771056,10081,0,1,23000.0000,True,6,nan,nan,nan,nan,4
160,2420538,203030959,51771056,10079,0,0,23000.0000,True,6,nan,nan,nan,nan,4
161,2420539,203030959,51771056,10080,0,1,23000.0000,True,6,nan,nan,nan,nan,4
162,2420540,203030959,51771056,10078,0,1,23000.0000,True,6,nan,nan,nan,nan,4
163,2420541,203378000,51771056,6519,0,0,39750.0000,True,6,nan,nan,nan,nan,4
164,2420542,203378000,51771056,6520,0,0,39750.0000,True,6,nan,nan,nan,nan,4
165,2420543,203378000,51771056,6517,0,1,39750.0000,True,6,nan,nan,nan,nan,4
166,2420544,203378000,51771056,6518,0,1,39750.0000,True,6,nan,nan,nan,nan,4
167,2420545,203648168,51771056,11174,0,1,30250.0000,True,6,nan,nan,nan,nan,4
168,2420546,203648168,51771056,11172,0,1,30250.0000,True,6,nan,nan,nan,nan,4
169,2420547,203648168,51771056,11173,0,0,30250.0000,True,6,nan,nan,nan,nan,4
170,2420548,203648168,51771056,11171,0,1,30250.0000,True,6,nan,nan,nan,nan,4
171,2420549,203839649,51771056,10069,0,1,26000.0000,True,6,nan,nan,nan,nan,4
172,2420550,203839649,51771056,10067,0,0,26000.0000,True,6,nan,nan,nan,nan,4
173,2420551,203839649,51771056,10066,0,1,26000.0000,True,6,nan,nan,nan,nan,4
174,2420552,203839649,51771056,10068,0,1,26000.0000,True,6,nan,nan,nan,nan,4
175,2420553,204130046,51771056,32570,1,-1,nan,False,3,0.0000,0.0000,1.0000,0.0000,2
176,2420554,204767306,51771056,9495,0,0,26250.0000,True,5,nan,nan,nan,nan,1
177,2420555,204862856,51771056,5178,0,1,21000.0000,True,5,nan,nan,nan,nan,1
178,2420556,204896107,51771056,6476,0,1,28000.0000,True,5,nan,nan,nan,nan,1
179,2420557,204920867,51771056,5593,0,1,7000.0000,True,5,nan,nan,nan,nan,1
180,2420558,204950525,51771056,9489,0,1,16000.0000,True,5,nan,nan,nan,nan,1
181,2420559,204973982,51771056,4260,0,1,20000.0000,True,5,nan,nan,nan,nan,1
182,2420560,205003162,51771056,8619,0,1,15000.0000,True,5,nan,nan,nan,nan,1
183,2420561,205038458,51771056,4585,0,1,14000.0000,True,5,nan,nan,nan,nan,1
184,2420562,205100442,51771056,9438,0,1,13000.0000,True,5,nan,nan,nan,nan,1
185,2420563,205138475,51771056,4664,0,1,35000.0000,True,5,nan,nan,nan,nan,1
186,2420564,205175334,51771056,3871,0,1,10000.0000,True,5,nan,nan,nan,nan,1
187,2420565,205205179,51771056,8719,0,1,11000.0000,True,5,nan,nan,nan,nan,1
188,2420566,205256107,51771056,3966,0,0,8000.0000,True,5,nan,nan,nan,nan,1
189,2420567,205337398,51771056,8641,0,1,26000.0000,True,5,nan,nan,nan,nan,1
190,2420568,205386250,51771056,5466,0,1,33000.0000,True,5,nan,nan,nan,nan,1
191,2420569,205410949,51771056,9098,0,1,10000.0000,True,5,nan,nan,nan,nan,1
192,2420570,205439790,51771056,5168,0,1,12000.0000,True,5,nan,nan,nan,nan,1
193,2420571,205460885,51771056,8653,0,1,17000.0000,True,5,nan,nan,nan,nan,1
194,2420572,205492912,51771056,8471,0,1,9000.0000,True,5,nan,nan,nan,nan,1
195,2420573,205551122,51771056,9779,0,1,21000.0000,True,5,nan,nan,nan,nan,1
196,2420574,205678246,51771056,8616,0,1,16000.0000,True,5,nan,nan,nan,nan,1
197,2420575,205713862,51771056,11531,0,1,14000.0000,True,5,nan,nan,nan,nan,1
198,2420576,205741642,51771056,4534,0,1,20000.0000,True,5,nan,nan,nan,nan,1
199,2420577,205769591,51771056,6664,0,1,12000.0000,True,5,nan,nan,nan,nan,1
200,2420578,205798879,51771056,6339,0,1,14000.0000,True,5,nan,nan,nan,nan,1
201,2420579,205864580,51771056,8262,0,0,7000.0000,True,5,nan,nan,nan,nan,1
202,2420580,206264042,51771056,6183,0,1,31000.0000,True,5,nan,nan,nan,nan,1
203,2420581,206319391,51771056,5676,0,0,5000.0000,True,5,nan,nan,nan,nan,1
204,2420582,206421546,51771056,6118,0,0,26000.0000,True,5,nan,nan,nan,nan,1
205,2420583,206505826,51771056,9234,0,1,35000.0000,True,5,nan,nan,nan,nan,1
206,2420584,206536555,51771056,5674,0,1,27000.0000,True,5,nan,nan,nan,nan,1
207,2420585,206583283,51771056,11479,0,1,7000.0000,True,5,nan,nan,nan,nan,1
208,2420586,206658079,51771056,4495,0,1,17000.0000,True,5,nan,nan,nan,nan,1
209,2420587,206724526,51771056,4416,0,0,15000.0000,True,5,nan,nan,nan,nan,1
210,2420588,206776505,51771056,6056,0,1,15000.0000,True,5,nan,nan,nan,nan,1
211,2420589,206861603,51771056,9254,0,0,18000.0000,True,5,nan,nan,nan,nan,1
212,2420590,206920346,51771056,5856,0,1,23000.0000,True,5,nan,nan,nan,nan,1
213,2420591,280367093,51771056,10231,0,1,9000.0000,True,6,nan,nan,nan,nan,4
214,2420592,280367093,51771056,10229,0,0,9000.0000,True,6,nan,nan,nan,nan,4
215,2420593,280367093,51771056,10228,0,1,9000.0000,True,6,nan,nan,nan,nan,4
216,2420594,280367093,51771056,10230,0,0,9000.0000,True,6,nan,nan,nan,nan,4
217,2420595,281539660,51771056,10148,0,1,41500.0000,True,6,nan,nan,nan,nan,4
218,2420596,281539660,51771056,10150,0,0,41500.0000,True,6,nan,nan,nan,nan,4
219,2420597,281539660,51771056,10149,0,1,41500.0000,True,6,nan,nan,nan,nan,4
220,2420598,281539660,51771056,10151,0,1,41500.0000,True,6,nan,nan,nan,nan,4
221,2420599,282638604,51771056,10071,0,1,26500.0000,True,6,nan,nan,nan,nan,4
222,2420600,282638604,51771056,10073,0,0,26500.0000,True,6,nan,nan,nan,nan,4
223,2420601,282638604,51771056,10072,0,1,26500.0000,True,6,nan,nan,nan,nan,4
224,2420602,282638604,51771056,10070,0,0,26500.0000,True,6,nan,nan,nan,nan,4
225,2420603,282950400,51771056,6867,0,1,23500.0000,True,6,nan,nan,nan,nan,4
226,2420604,282950400,51771056,6868,0,0,23500.0000,True,6,nan,nan,nan,nan,4
227,2420605,282950400,51771056,6865,0,0,23500.0000,True,6,nan,nan,nan,nan,4
228,2420606,282950400,51771056,6866,0,1,23500.0000,True,6,nan,nan,nan,nan,4
229,2420607,283146278,51771056,12354,1,-1,nan,False,6,1.0000,0.0000,0.0000,0.0000,4
230,2420608,286177331,51771056,7949,1,-1,nan,False,5,1.0000,0.0000,0.0000,0.0000,1
231,2420609,286302450,51771056,9254,0,0,27250.0000,True,5,nan,nan,nan,nan,1
232,2420610,286370013,51771056,3966,0,1,77000.0000,True,5,nan,nan,nan,nan,1
233,2420611,286408472,51771056,3599,0,1,10000.0000,True,5,nan,nan,nan,nan,1
234,2420612,402788047,51771056,834,0,1,21000.0000,False,2,nan,nan,nan,nan,3
235,2420613,402976713,51771056,6766,0,1,17000.0000,True,6,nan,nan,nan,nan,4
236,2420614,402976713,51771056,6765,0,1,17000.0000,True,6,nan,nan,nan,nan,4
237,2420615,402976713,51771056,6768,0,1,17000.0000,True,6,nan,nan,nan,nan,4
238,2420616,402976713,51771056,6767,0,1,17000.0000,True,6,nan,nan,nan,nan,4
239,2420617,403174070,51771056,10840,0,1,32250.0000,True,6,nan,nan,nan,nan,4
240,2420618,403174070,51771056,10842,0,1,32250.0000,True,6,nan,nan,nan,nan,4
241,2420619,403174070,51771056,10841,0,1,32250.0000,True,6,nan,nan,nan,nan,4
242,2420620,403174070,51771056,10839,0,0,32250.0000,True,6,nan,nan,nan,nan,4
243,2420621,403351006,51771056,6878,0,1,28750.0000,True,6,nan,nan,nan,nan,4
244,2420622,403351006,51771056,6879,0,0,28750.0000,True,6,nan,nan,nan,nan,4
245,2420623,403351006,51771056,6877,0,1,28750.0000,True,6,nan,nan,nan,nan,4
246,2420624,403351006,51771056,6880,0,1,28750.0000,True,6,nan,nan,nan,nan,4
247,2420625,406525042,51771056,13550,1,-1,nan,False,6,1.0000,0.0000,0.0000,0.0000,4
248,2420626,406574702,51771056,11929,0,1,21750.0000,True,2,nan,nan,nan,nan,11
249,2420627,407503932,51771056,1359,0,0,17000.0000,True,2,nan,nan,nan,nan,3
250,2420628,408438229,51771056,1236,0,0,17000.0000,True,2,nan,nan,nan,nan,3
251,2420629,408471581,51771056,923,0,1,21000.0000,True,2,nan,nan,nan,nan,3
252,2420630,408507858,51771056,11943,0,0,18000.0000,True,2,nan,nan,nan,nan,3
253,2420631,408540073,51771056,1147,0,1,17000.0000,True,2,nan,nan,nan,nan,3
254,2420632,408579825,51771056,239,0,0,14000.0000,True,2,nan,nan,nan,nan,3
255,2420633,408630185,51771056,488,0,1,22000.0000,True,2,nan,nan,nan,nan,11
256,2420634,408668004,51771056,12159,0,1,22000.0000,True,2,nan,nan,nan,nan,9
257,2420635,408708084,51771056,375,0,0,16000.0000,True,2,nan,nan,nan,nan,3
258,2420636,408783271,51771056,1362,0,0,19000.0000,True,2,nan,nan,nan,nan,10
259,2420637,408829402,51771056,784,0,0,17000.0000,True,2,nan,nan,nan,nan,3
260,2420638,408859031,51771056,11962,0,1,19000.0000,True,2,nan,nan,nan,nan,11
261,2420639,408891381,51771056,589,0,1,17000.0000,True,2,nan,nan,nan,nan,11
262,2420640,408931594,51771056,296,0,1,19000.0000,True,2,nan,nan,nan,nan,9
263,2420641,408973082,51771056,904,0,0,17000.0000,True,2,nan,nan,nan,nan,11
264,2420642,409003765,51771056,11946,0,1,17000.0000,True,2,nan,nan,nan,nan,3
265,2420643,409029381,51771056,762,0,0,18000.0000,True,2,nan,nan,nan,nan,9
266,2420644,409059982,51771056,704,0,1,16000.0000,True,2,nan,nan,nan,nan,11
267,2420645,409209093,51771056,738,0,0,20000.0000,True,2,nan,nan,nan,nan,11
268,2420646,409243093,51771056,3153,1,-1,nan,False,2,0.0000,1.0000,0.0000,0.0000,3
269,2420647,409273363,51771056,738,0,0,17000.0000,True,2,nan,nan,nan,nan,11
270,2420648,409310872,51771056,762,0,1,17000.0000,True,2,nan,nan,nan,nan,9
271,2420649,409373565,51771056,11967,0,1,18000.0000,True,2,nan,nan,nan,nan,11
272,2420650,409429992,51771056,549,0,1,17000.0000,True,2,nan,nan,nan,nan,3
273,2420651,409498881,51771056,1362,0,1,22000.0000,True,2,nan,nan,nan,nan,10
274,2420652,409514401,51771056,254,0,0,15000.0000,True,2,nan,nan,nan,nan,10
275,2420653,409538323,51771056,254,0,1,23000.0000,True,2,nan,nan,nan,nan,10
276,2420654,409582691,51771056,1111,0,1,18000.0000,True,2,nan,nan,nan,nan,3
277,2420655,409613756,51771056,12191,0,1,16000.0000,True,2,nan,nan,nan,nan,3
278,2420656,409644408,51771056,1028,0,1,16000.0000,True,2,nan,nan,nan,nan,10
279,2420657,409683860,51771056,217,0,1,14000.0000,True,2,nan,nan,nan,nan,3
280,2420658,409860664,51771056,853,0,0,18000.0000,True,2,nan,nan,nan,nan,3
281,2420659,409930199,51771056,29544,1,-1,nan,False,2,1.0000,0.0000,0.0000,0.0000,3
282,2420660,409951204,51771056,738,0,1,18000.0000,True,2,nan,nan,nan,nan,11
283,2420661,409985177,51771056,853,0,0,16000.0000,True,2,nan,nan,nan,nan,3
284,2420662,410074310,51771056,9489,0,0,19000.0000,True,5,nan,nan,nan,nan,1
285,2420663,410131604,51771056,4465,0,0,17000.0000,True,5,nan,nan,nan,nan,1
286,2420664,410182243,51771056,704,0,1,26000.0000,True,2,nan,nan,nan,nan,11
287,2420665,410347558,51771056,10855,0,0,19000.0000,True,6,nan,nan,nan,nan,4
288,2420666,410347558,51771056,10856,0,0,19000.0000,True,6,nan,nan,nan,nan,4
289,2420667,410347558,51771056,10858,0,1,19000.0000,True,6,nan,nan,nan,nan,4
290,2420668,410347558,51771056,10857,0,1,19000.0000,True,6,nan,nan,nan,nan,4
291,2420669,410413834,51771056,5178,0,1,32000.0000,True,5,nan,nan,nan,nan,1
292,2420670,410451017,51771056,407,0,1,27000.0000,True,2,nan,nan,nan,nan,10
293,2420671,410483442,51771056,8471,0,1,17000.0000,True,5,nan,nan,nan,nan,1
294,2420672,410511892,51771056,423,0,1,16000.0000,True,2,nan,nan,nan,nan,3
295,2420673,410541023,51771056,11479,0,1,16000.0000,True,5,nan,nan,nan,nan,1
296,2420674,410560441,51771056,5626,0,1,8000.0000,True,5,nan,nan,nan,nan,1
297,2420675,410592045,51771056,5593,0,1,8000.0000,True,5,nan,nan,nan,nan,1
298,2420676,410626652,51771056,7981,0,1,17000.0000,True,1,nan,nan,nan,nan,13
299,2420677,410734901,51771056,2257,0,1,24000.0000,True,3,nan,nan,nan,nan,2
300,2420678,410734901,51771056,2258,0,1,24000.0000,True,3,nan,nan,nan,nan,2
301,2420679,410734901,51771056,2259,0,0,24000.0000,True,3,nan,nan,nan,nan,2
302,2420680,410802231,51771056,549,0,1,23666.0000,True,2,nan,nan,nan,nan,3
303,2420681,410843931,51771056,8516,0,1,21000.0000,True,5,nan,nan,nan,nan,1
304,2420682,410869405,51771056,4416,0,1,13000.0000,True,5,nan,nan,nan,nan,1
305,2420683,410905753,51771056,12081,0,1,4000.0000,True,2,nan,nan,nan,nan,9
306,2420684,411746459,51771056,13447,0,1,20000.0000,True,5,nan,nan,nan,nan,1
307,2420685,413120860,51771056,7492,0,1,9000.0000,True,7,nan,nan,nan,nan,15
308,2420686,413120860,51771056,7493,0,1,9000.0000,True,7,nan,nan,nan,nan,15
309,2420687,413120860,51771056,7489,0,1,9000.0000,True,7,nan,nan,nan,nan,15

In [108]:
user_vitrine = pd.read_csv('../data/experiment_1/user_vitrine.csv')

In [109]:
user_vitrine

,id,timestamp,prior_question_elapsed_time,prior_question_had_explanation,part,kmean_cluster,lect_user_part,lect_user_kmean_cluster,lect_user,lect_user_part_concept,lect_user_kmean_cluster_concept,lect_user_concept,lect_user_part_intention,lect_user_kmean_cluster_intention,lect_user_intention,lect_user_part_solving_question,lect_user_kmean_cluster_solving_question,lect_user_solving_question,lect_user_part_starter,lect_user_kmean_cluster_starter,lect_user_starter,user_sum_answered_correctly,user_count_answered_correctly,user_mean_answered_correctly,user_ema_answered_correctly,user_he_sum_answered_correctly,user_he_count_answered_correctly,user_he_mean_answered_correctly,user_he_ema_answered_correctly,user_sum_prior_question_elapsed_time,user_count_prior_question_elapsed_time,user_mean_prior_question_elapsed_time,user_ema_prior_question_elapsed_time,user_he_sum_prior_question_elapsed_time,user_he_count_prior_question_elapsed_time,user_he_mean_prior_question_elapsed_time,user_he_ema_prior_question_elapsed_time,user_ucount_part,user_ucount_kmean_cluster,user_he_ucount_part,user_he_ucount_kmean_cluster,abs_chng_timestamp,rel_chng_timestamp,rel_user_he_mean_answ,rel_user_he_ema_answ,rel_user_he_mean_pqet,rel_user_he_ema_pqet,trend_user_mean_answ,trend_user_he_mean_answ,trend_user_mean_pqet,trend_user_he_mean_pqet
0,365548.0000,290933.0000,38000.0000,0,4.0000,6.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,1.0000,7.0000,0.1429,0.1730,1.0000,7.0000,0.1429,0.1730,160000.0000,8.0000,20000.0000,23361.5955,160000.0000,8.0000,20000.0000,23361.5955,3.0000,4.0000,3.0000,4.0000,98122.0000,0.3373,1.0000,1.0000,1.0000,1.0000,1.2107,1.2107,1.1681,1.1681
1,365549.0000,290933.0000,38000.0000,0,4.0000,6.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,2.0000,8.0000,0.2500,0.3020,2.0000,8.0000,0.2500,0.3020,198000.0000,9.0000,22000.0000,25645.7124,198000.0000,9.0000,22000.0000,25645.7124,4.0000,5.0000,4.0000,5.0000,0.0000,0.0000,1.0000,1.0000,1.0000,1.0000,1.2080,1.2080,1.1657,1.1657
2,365550.0000,290933.0000,38000.0000,0,4.0000,6.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,2.0000,9.0000,0.2222,0.2588,2.0000,9.0000,0.2222,0.2588,236000.0000,10.0000,23600.0000,27411.7936,236000.0000,10.0000,23600.0000,27411.7936,4.0000,5.0000,4.0000,5.0000,0.0000,0.0000,1.0000,1.0000,1.0000,1.0000,1.1647,1.1647,1.1615,1.1615
3,365551.0000,370847.0000,31333.0000,0,4.0000,6.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,2.0000,10.0000,0.2000,0.2245,2.0000,10.0000,0.2000,0.2245,267333.0000,11.0000,24303.0000,27931.5718,267333.0000,11.0000,24303.0000,27931.5718,4.0000,5.0000,4.0000,5.0000,79914.0000,0.2155,1.0000,1.0000,1.0000,1.0000,1.1226,1.1226,1.1493,1.1493
4,365552.0000,370847.0000,31333.0000,0,4.0000,6.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,2.0000,11.0000,0.1818,0.1967,2.0000,11.0000,0.1818,0.1967,298666.0000,12.0000,24888.8333,28353.7271,298666.0000,12.0000,24888.8333,28353.7271,4.0000,5.0000,4.0000,5.0000,0.0000,0.0000,1.0000,1.0000,1.0000,1.0000,1.0816,1.0816,1.1392,1.1392
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2151,101109066.0000,2313772645.0000,18000.0000,1,5.0000,1.0000,9.0000,9.0000,13.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,236.0000,353.0000,0.6686,0.6580,222.0000,322.0000,0.6894,0.6618,8164078.0000,354.0000,23062.3672,22352.6808,7345000.0000,323.0000,22739.9381,22154.6701,7.0000,12.0000,2.0000,7.0000,105581.0000,0.0000,1.0312,1.0058,0.9860,0.9911,0.9843,0.9599,0.9692,0.9743
2152,101109067.0000,2313888806.0000,18000.0000,1,5.0000,16.0000,9.0000,0.0000,13.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,236.0000,354.0000,0.6667,0.6538,222.0000,323.0000,0.6873,0.6571,8182078.0000,355.0000,23048.1070,22324.5370,7363000.0000,324.0000,22725.3086,22125.2865,7.0000,12.0000,2.0000,7.0000,116161.0000,0.0001,1.0310,1.0051,0.9860,0.9911,0.9807,0.9561,0.9686,0.9736
2153,101109068.0000,2314051785.0000,25000.0000,1,5.0000,1.0000,9.0000,9.0000,13.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,237.0000,355.0000,0.6676,0.6560,223.0000,324.0000,0.6883,0.6596,8207078.0000,356.0000,23053.5899,22341.8207,7388000.0000,325.0000,22732.3077,22145.5979,7.0000,12.0000,2.0000,7.0000,162979.0000,0.0001,1.0310,1.0054,0.9861,0.9912,0.9826,0.9583,0.9691,0.9742
2154,101109069.0000,2314404971.0000,56000.0000,1,5.0000,1.0000,9.0000,9.0000,13.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,237.0000,356.0000,0.6657,0.6518,223.0000,325.0000,0.6862,0.6549,8263078.0000,357.0000,23145.8768,22559.0621,7444000.0000,326.0000,22834.3558,22384.5662,7.0000,12.0000,2.0000,7.0000,353186.0000,0.0002,1.0307,1.0048,0.9865,0.9923,0.9790,0.9545,0.9746,0.9803
2155,101109070.0000,2314786293.0000,37000.0000,1,5.0000,1.0000,9.0000,9.0000,13.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,237.0000,357.0000,0.6639,0.6476,223.0000,326.0000,0.6840,0.6503,8300078.0000,358.0000,23184.5754,22652.1866,7481000.0000,327.0000,22877.6758,22487.6333,7.0000,12.0000,2.0000,7.0000,381322.0000,0.0002,1.0304,1.0042,0.9868,0.9927,0.9755,0.9506,0.9770,0.9830

In [110]:
user_vitrine.shape

(2156, 51)

In [111]:
user_vitrine.isna().sum(axis = 0).sum()

0