In [1]:
import numpy as np
import pandas as pd
pd.set_option('display.float_format', '{:.4f}'.format)
pd.set_option('display.max_rows', 1000)
pd.set_option('display.max_columns', 1000)

In [58]:
%%time
train_mini = pd.read_csv('../data/train_mini.csv')

CPU times: user 25.3 ms, sys: 6.69 ms, total: 32 ms
Wall time: 32.4 ms

In [2]:
%%time
vitrine = pd.read_csv('../data/vitrine.csv')

CPU times: user 30.5 ms, sys: 11.4 ms, total: 41.9 ms
Wall time: 83.5 ms

In [60]:
train_mini.shape, vitrine.shape

((26892, 10), (26892, 14))

In [61]:
train_mini.head()

,row_id,timestamp,user_id,content_id,content_type_id,task_container_id,user_answer,answered_correctly,prior_question_elapsed_time,prior_question_had_explanation
0,365541,0,7136928,7900,0,0,2,0,nan,NaN
1,365542,23989,7136928,7876,0,1,0,0,21000.0000,False
2,365543,48079,7136928,175,0,2,3,0,20000.0000,False
3,365544,74835,7136928,1278,0,3,1,0,21000.0000,False
4,365545,192811,7136928,2063,0,4,3,0,20000.0000,False

In [3]:
vitrine.head()

,id,timestamp,user_id,content_id,content_type_id,answered_correctly,prior_question_elapsed_time,prior_question_had_explanation,part,concept,intention,solving_question,starter,kmean_cluster
0,365541,0,7136928,7900,0,0,nan,NaN,1,nan,nan,nan,nan,0
1,365542,23989,7136928,7876,0,0,21000.0000,False,1,nan,nan,nan,nan,13
2,365543,48079,7136928,175,0,0,20000.0000,False,1,nan,nan,nan,nan,13
3,365544,74835,7136928,1278,0,0,21000.0000,False,2,nan,nan,nan,nan,11
4,365545,192811,7136928,2063,0,0,20000.0000,False,3,nan,nan,nan,nan,9

In [63]:
train_mini[train_mini.user_id == 7136928]

,row_id,timestamp,user_id,content_id,content_type_id,task_container_id,user_answer,answered_correctly,prior_question_elapsed_time,prior_question_had_explanation
0,365541,0,7136928,7900,0,0,2,0,nan,NaN
1,365542,23989,7136928,7876,0,1,0,0,21000.0000,False
2,365543,48079,7136928,175,0,2,3,0,20000.0000,False
3,365544,74835,7136928,1278,0,3,1,0,21000.0000,False
4,365545,192811,7136928,2063,0,4,3,0,20000.0000,False
5,365546,192811,7136928,2064,0,4,2,0,20000.0000,False
6,365547,192811,7136928,2065,0,4,2,1,20000.0000,False
7,365548,290933,7136928,3364,0,5,1,1,38000.0000,False
8,365549,290933,7136928,3365,0,5,3,0,38000.0000,False
9,365550,290933,7136928,3363,0,5,1,0,38000.0000,False
10,365551,370847,7136928,2947,0,6,0,0,31333.0000,False
11,365552,370847,7136928,2948,0,6,3,0,31333.0000,False
12,365553,370847,7136928,2946,0,6,2,0,31333.0000,False
13,365554,451200,7136928,2595,0,7,1,0,25666.0000,False
14,365555,451200,7136928,2593,0,7,1,0,25666.0000,False
15,365556,451200,7136928,2594,0,7,3,0,25666.0000,False
16,365557,478945,7136928,4492,0,8,1,0,25666.0000,False
17,365558,510488,7136928,4120,0,9,3,0,25000.0000,False
18,365559,543527,7136928,4696,0,10,1,0,29000.0000,False
19,365560,572018,7136928,6116,0,11,0,0,31000.0000,False
20,365561,621276,7136928,6173,0,12,0,0,26000.0000,False
21,365562,695703,7136928,6370,0,13,0,0,47000.0000,False
22,365563,869639,7136928,6879,0,14,2,1,72000.0000,False
23,365564,869639,7136928,6880,0,14,1,0,72000.0000,False
24,365565,869639,7136928,6877,0,14,1,0,72000.0000,False
25,365566,869639,7136928,6878,0,14,1,1,72000.0000,False
26,365567,1381521,7136928,7216,0,15,2,0,42750.0000,False
27,365568,1381521,7136928,7217,0,15,2,1,42750.0000,False
28,365569,1381521,7136928,7219,0,15,3,0,42750.0000,False
29,365570,1381521,7136928,7218,0,15,0,0,42750.0000,False

In [64]:
vitrine[vitrine.user_id == 7136928]

,id,timestamp,user_id,content_id,content_type_id,answered_correctly,prior_question_elapsed_time,prior_question_had_explanation,part,concept,intention,solving_question,starter,kmean_cluster
0,365541,0,7136928,7900,0,0,nan,NaN,1,nan,nan,nan,nan,0
1,365542,23989,7136928,7876,0,0,21000.0000,False,1,nan,nan,nan,nan,13
2,365543,48079,7136928,175,0,0,20000.0000,False,1,nan,nan,nan,nan,13
3,365544,74835,7136928,1278,0,0,21000.0000,False,2,nan,nan,nan,nan,11
4,365545,192811,7136928,2063,0,0,20000.0000,False,3,nan,nan,nan,nan,9
5,365546,192811,7136928,2064,0,0,20000.0000,False,3,nan,nan,nan,nan,9
6,365547,192811,7136928,2065,0,1,20000.0000,False,3,nan,nan,nan,nan,9
7,365548,290933,7136928,3364,0,1,38000.0000,False,4,nan,nan,nan,nan,6
8,365549,290933,7136928,3365,0,0,38000.0000,False,4,nan,nan,nan,nan,6
9,365550,290933,7136928,3363,0,0,38000.0000,False,4,nan,nan,nan,nan,6
10,365551,370847,7136928,2947,0,0,31333.0000,False,4,nan,nan,nan,nan,6
11,365552,370847,7136928,2948,0,0,31333.0000,False,4,nan,nan,nan,nan,6
12,365553,370847,7136928,2946,0,0,31333.0000,False,4,nan,nan,nan,nan,6
13,365554,451200,7136928,2595,0,0,25666.0000,False,4,nan,nan,nan,nan,6
14,365555,451200,7136928,2593,0,0,25666.0000,False,4,nan,nan,nan,nan,6
15,365556,451200,7136928,2594,0,0,25666.0000,False,4,nan,nan,nan,nan,6
16,365557,478945,7136928,4492,0,0,25666.0000,False,5,nan,nan,nan,nan,1
17,365558,510488,7136928,4120,0,0,25000.0000,False,5,nan,nan,nan,nan,1
18,365559,543527,7136928,4696,0,0,29000.0000,False,5,nan,nan,nan,nan,1
19,365560,572018,7136928,6116,0,0,31000.0000,False,5,nan,nan,nan,nan,1
20,365561,621276,7136928,6173,0,0,26000.0000,False,5,nan,nan,nan,nan,1
21,365562,695703,7136928,6370,0,0,47000.0000,False,5,nan,nan,nan,nan,1
22,365563,869639,7136928,6879,0,1,72000.0000,False,6,nan,nan,nan,nan,4
23,365564,869639,7136928,6880,0,0,72000.0000,False,6,nan,nan,nan,nan,4
24,365565,869639,7136928,6877,0,0,72000.0000,False,6,nan,nan,nan,nan,4
25,365566,869639,7136928,6878,0,1,72000.0000,False,6,nan,nan,nan,nan,4
26,365567,1381521,7136928,7216,0,0,42750.0000,False,7,nan,nan,nan,nan,5
27,365568,1381521,7136928,7217,0,1,42750.0000,False,7,nan,nan,nan,nan,5
28,365569,1381521,7136928,7219,0,0,42750.0000,False,7,nan,nan,nan,nan,5
29,365570,1381521,7136928,7218,0,0,42750.0000,False,7,nan,nan,nan,nan,5

In [65]:
vitrine[vitrine.content_type_id == 1]

,id,timestamp,user_id,content_id,content_type_id,answered_correctly,prior_question_elapsed_time,prior_question_had_explanation,part,concept,intention,solving_question,starter,kmean_cluster
100,2420478,85453640,51771056,22711,1,-1,nan,False,6,1.0000,0.0000,0.0000,0.0000,4
131,2420509,150817666,51771056,23815,1,-1,nan,False,3,1.0000,0.0000,0.0000,0.0000,2
175,2420553,204130046,51771056,32570,1,-1,nan,False,3,0.0000,0.0000,1.0000,0.0000,2
229,2420607,283146278,51771056,12354,1,-1,nan,False,6,1.0000,0.0000,0.0000,0.0000,4
230,2420608,286177331,51771056,7949,1,-1,nan,False,5,1.0000,0.0000,0.0000,0.0000,1
247,2420625,406525042,51771056,13550,1,-1,nan,False,6,1.0000,0.0000,0.0000,0.0000,4
268,2420646,409243093,51771056,3153,1,-1,nan,False,2,0.0000,1.0000,0.0000,0.0000,3
281,2420659,409930199,51771056,29544,1,-1,nan,False,2,1.0000,0.0000,0.0000,0.0000,3
320,2420698,413707888,51771056,20307,1,-1,nan,False,6,1.0000,0.0000,0.0000,0.0000,4
421,2420799,505963837,51771056,16363,1,-1,nan,False,6,1.0000,0.0000,0.0000,0.0000,4
451,2420829,519706895,51771056,18239,1,-1,nan,False,5,1.0000,0.0000,0.0000,0.0000,1
550,2420928,539054953,51771056,10354,1,-1,nan,False,6,1.0000,0.0000,0.0000,0.0000,4
560,2420938,539974509,51771056,1144,1,-1,nan,False,5,1.0000,0.0000,0.0000,0.0000,1
582,2420960,545318824,51771056,24402,1,-1,nan,False,1,1.0000,0.0000,0.0000,0.0000,0
586,2420964,545470129,51771056,10540,1,-1,nan,False,1,1.0000,0.0000,0.0000,0.0000,0
615,2420993,546964369,51771056,5588,1,-1,nan,False,6,1.0000,0.0000,0.0000,0.0000,4
695,2421073,630338878,51771056,24985,1,-1,nan,False,5,1.0000,0.0000,0.0000,0.0000,1
772,2421150,664065775,51771056,3937,1,-1,nan,False,6,1.0000,0.0000,0.0000,0.0000,4
886,3877262,252538006,82977466,7477,1,-1,nan,False,5,1.0000,0.0000,0.0000,0.0000,1
1005,4494548,40255146657,94999086,3153,1,-1,nan,False,2,0.0000,1.0000,0.0000,0.0000,3
1023,4494566,40600823024,94999086,15430,1,-1,nan,False,2,1.0000,0.0000,0.0000,0.0000,3
1028,4494571,40601271345,94999086,26516,1,-1,nan,False,5,1.0000,0.0000,0.0000,0.0000,1
1048,4494591,40686481437,94999086,19744,1,-1,nan,False,2,1.0000,0.0000,0.0000,0.0000,3
1057,4494600,40686722361,94999086,27115,1,-1,nan,False,5,1.0000,0.0000,0.0000,0.0000,7
1061,4494604,40686971149,94999086,14443,1,-1,nan,False,5,1.0000,0.0000,0.0000,0.0000,1
1068,4494611,40855492312,94999086,14325,1,-1,nan,False,2,0.0000,1.0000,0.0000,0.0000,3
1182,4494725,41292898024,94999086,27507,1,-1,nan,False,5,0.0000,0.0000,1.0000,0.0000,1
1199,4494742,41378533140,94999086,13605,1,-1,nan,False,5,1.0000,0.0000,0.0000,0.0000,1
1219,4494762,41463835218,94999086,18307,1,-1,nan,False,2,0.0000,0.0000,1.0000,0.0000,3
1224,4494767,41463963531,94999086,9554,1,-1,nan,False,2,0.0000,1.0000,0.0000,0.0000,3
1238,4494781,41464725244,94999086,27022,1,-1,nan,False,5,1.0000,0.0000,0.0000,0.0000,1
1342,4494885,42068725245,94999086,17914,1,-1,nan,False,5,1.0000,0.0000,0.0000,0.0000,1
1351,4494894,42068889050,94999086,27845,1,-1,nan,False,5,1.0000,0.0000,0.0000,0.0000,1
1376,4494919,42157074987,94999086,22034,1,-1,nan,False,5,1.0000,0.0000,0.0000,0.0000,1
1391,4494934,42157693823,94999086,5694,1,-1,nan,False,2,1.0000,0.0000,0.0000,0.0000,3
1461,4495004,42414298198,94999086,21411,1,-1,nan,False,2,0.0000,0.0000,1.0000,0.0000,3
1486,4495029,42500933732,94999086,100,1,-1,nan,False,1,1.0000,0.0000,0.0000,0.0000,13
1506,4495049,42587794496,94999086,335,1,-1,nan,False,2,1.0000,0.0000,0.0000,0.0000,3
1517,4495060,42588272430,94999086,8708,1,-1,nan,False,5,1.0000,0.0000,0.0000,0.0000,1
1607,6492075,120231854,141264833,27115,1,-1,nan,False,5,1.0000,0.0000,0.0000,0.0000,7
1716,6492184,1497135430,141264833,6797,1,-1,nan,False,2,1.0000,0.0000,0.0000,0.0000,3
1723,6492191,1497351970,141264833,13605,1,-1,nan,False,5,1.0000,0.0000,0.0000,0.0000,1
1783,6492251,1942209741,141264833,31657,1,-1,nan,False,5,1.0000,0.0000,0.0000,0.0000,1
1890,10803389,253207007,235233876,14325,1,-1,nan,False,2,0.0000,1.0000,0.0000,0.0000,3
1907,10803406,253891123,235233876,3255,1,-1,nan,False,5,1.0000,0.0000,0.0000,0.0000,1
1931,10803430,327456355,235233876,26921,1,-1,nan,False,5,1.0000,0.0000,0.0000,0.0000,1
1983,10803482,832785906,235233876,5694,1,-1,nan,False,2,1.0000,0.0000,0.0000,0.0000,3
1993,10803492,835009330,235233876,21597,1,-1,nan,False,5,1.0000,0.0000,0.0000,0.0000,1
2000,10803499,933574248,235233876,10852,1,-1,nan,False,5,1.0000,0.0000,0.0000,0.0000,1
2027,10803526,1353296002,235233876,5752,1,-1,nan,False,2,0.0000,1.0000,0.0000,0.0000,3
2311,12353705,4974112019,269060757,27339,1,-1,nan,False,5,1.0000,0.0000,0.0000,0.0000,1
2358,15709436,777696,337576619,10540,1,-1,nan,False,1,1.0000,0.0000,0.0000,0.0000,0
2528,15709606,546532400,337576619,7477,1,-1,nan,False,5,1.0000,0.0000,0.0000,0.0000,1
2781,18932869,2759392,406901956,3113,1,-1,nan,False,5,1.0000,0.0000,0.0000,0.0000,1
2795,18932883,118159617,406901956,5694,1,-1,nan,False,2,1.0000,0.0000,0.0000,0.0000,3
2886,19038586,662469133,409019335,6797,1,-1,nan,False,2,1.0000,0.0000,0.0000,0.0000,3
2898,19038598,663334546,409019335,3153,1,-1,nan,False,2,0.0000,1.0000,0.0000,0.0000,3
2910,19038610,664997491,409019335,14325,1,-1,nan,False,2,0.0000,1.0000,0.0000,0.0000,3
2955,19038655,677279348,409019335,19744,1,-1,nan,False,2,1.0000,0.0000,0.0000,0.0000,3
2972,19038672,779053231,409019335,335,1,-1,nan,False,2,1.0000,0.0000,0.0000,0.0000,3
3019,19038719,847745276,409019335,21887,1,-1,nan,False,2,1.0000,0.0000,0.0000,0.0000,3
3026,19038726,849326288,409019335,7926,1,-1,nan,False,5,1.0000,0.0000,0.0000,0.0000,1
3116,19038816,1443119903,409019335,25401,1,-1,nan,False,5,1.0000,0.0000,0.0000,0.0000,1
3139,19038839,1527568953,409019335,22034,1,-1,nan,False,5,1.0000,0.0000,0.0000,0.0000,1
3182,19038882,1705907918,409019335,5752,1,-1,nan,False,2,0.0000,1.0000,0.0000,0.0000,3
3200,19038900,1780580389,409019335,9554,1,-1,nan,False,2,0.0000,1.0000,0.0000,0.0000,3
3221,19038921,1800335153,409019335,18862,1,-1,nan,False,5,1.0000,0.0000,0.0000,0.0000,1
3257,19038957,1960644460,409019335,18101,1,-1,nan,False,2,0.0000,0.0000,1.0000,0.0000,3
3299,19038999,2127764703,409019335,15430,1,-1,nan,False,2,1.0000,0.0000,0.0000,0.0000,3
3322,19039022,2245700396,409019335,9896,1,-1,nan,False,5,1.0000,0.0000,0.0000,0.0000,1
3329,19039029,2246405582,409019335,3697,1,-1,nan,False,2,0.0000,0.0000,1.0000,0.0000,3
3401,19039101,2560298879,409019335,18307,1,-1,nan,False,2,0.0000,0.0000,1.0000,0.0000,3
3431,19039131,2651087701,409019335,13942,1,-1,nan,False,2,0.0000,0.0000,1.0000,0.0000,3
3455,19039155,2735183020,409019335,27463,1,-1,nan,False,2,0.0000,0.0000,1.0000,0.0000,3
3490,19039190,2825866755,409019335,3123,1,-1,nan,False,5,1.0000,0.0000,0.0000,0.0000,1
3493,19039193,2826493427,409019335,14443,1,-1,nan,False,5,1.0000,0.0000,0.0000,0.0000,1
3496,19039196,2870424156,409019335,31657,1,-1,nan,False,5,1.0000,0.0000,0.0000,0.0000,1
3499,19039199,2874217108,409019335,27022,1,-1,nan,False,5,1.0000,0.0000,0.0000,0.0000,1
3502,19039202,2874787184,409019335,12638,1,-1,nan,False,5,1.0000,0.0000,0.0000,0.0000,1
3535,19039235,3023254980,409019335,30207,1,-1,nan,False,5,1.0000,0.0000,0.0000,0.0000,1
3548,19039248,3042315558,409019335,8976,1,-1,nan,False,2,0.0000,1.0000,0.0000,0.0000,3
3591,19039291,3166594447,409019335,29544,1,-1,nan,False,2,1.0000,0.0000,0.0000,0.0000,3
3624,19039324,3557473297,409019335,6808,1,-1,nan,False,2,0.0000,1.0000,0.0000,0.0000,3
3627,19039327,3557935726,409019335,21852,1,-1,nan,False,2,1.0000,0.0000,0.0000,0.0000,3
3708,19039408,3859423551,409019335,32023,1,-1,nan,False,2,0.0000,0.0000,1.0000,0.0000,3
3711,19039411,3859967100,409019335,7877,1,-1,nan,False,2,0.0000,0.0000,1.0000,0.0000,3
3737,19039437,3872117460,409019335,11151,1,-1,nan,False,2,0.0000,0.0000,1.0000,0.0000,3
3771,19039471,4059011294,409019335,25089,1,-1,nan,False,2,0.0000,0.0000,1.0000,0.0000,3
3786,19039486,4060873517,409019335,32625,1,-1,nan,False,2,1.0000,0.0000,0.0000,0.0000,3
3793,19039493,4062516477,409019335,28122,1,-1,nan,False,2,0.0000,0.0000,1.0000,0.0000,3
3796,19039496,4063548915,409019335,15888,1,-1,nan,False,5,1.0000,0.0000,0.0000,0.0000,1
3829,19039529,4159372675,409019335,6481,1,-1,nan,False,5,1.0000,0.0000,0.0000,0.0000,1
3927,19039627,4588447741,409019335,27699,1,-1,nan,False,2,0.0000,1.0000,0.0000,0.0000,3
3960,19039660,4687812819,409019335,26516,1,-1,nan,False,5,1.0000,0.0000,0.0000,0.0000,1
3963,19039663,4688296670,409019335,9835,1,-1,nan,False,5,0.0000,0.0000,1.0000,0.0000,1
3966,19039666,4688588029,409019335,22836,1,-1,nan,False,5,0.0000,0.0000,1.0000,0.0000,1
3976,19039676,4721095030,409019335,21152,1,-1,nan,False,2,0.0000,0.0000,1.0000,0.0000,3
4012,19039712,4859511192,409019335,3113,1,-1,nan,False,5,1.0000,0.0000,0.0000,0.0000,1
4015,19039715,4860176097,409019335,4057,1,-1,nan,False,5,1.0000,0.0000,0.0000,0.0000,1
4018,19039718,4910900587,409019335,28921,1,-1,nan,False,5,1.0000,0.0000,0.0000,0.0000,1
4045,19039745,4917833867,409019335,23336,1,-1,nan,False,5,1.0000,0.0000,0.0000,0.0000,1
4079,19039779,5104544358,409019335,13660,1,-1,nan,False,5,1.0000,0.0000,0.0000,0.0000,1
4082,19039782,5104847918,409019335,1604,1,-1,nan,False,5,0.0000,0.0000,1.0000,0.0000,1
4085,19039785,5104968138,409019335,7477,1,-1,nan,False,5,1.0000,0.0000,0.0000,0.0000,1
4133,19039833,5250220402,409019335,20474,1,-1,nan,False,5,1.0000,0.0000,0.0000,0.0000,1
4136,19039836,5250365299,409019335,484,1,-1,nan,False,5,1.0000,0.0000,0.0000,0.0000,1
4139,19039839,5250648531,409019335,31440,1,-1,nan,False,5,0.0000,0.0000,1.0000,0.0000,1
4143,19039843,5284157799,409019335,30159,1,-1,nan,False,2,0.0000,0.0000,1.0000,0.0000,3
4154,19039854,5285777372,409019335,4441,1,-1,nan,False,2,0.0000,0.0000,1.0000,0.0000,3
4158,19039858,5286334371,409019335,21411,1,-1,nan,False,2,0.0000,0.0000,1.0000,0.0000,3
4261,19039961,5675294930,409019335,6137,1,-1,nan,False,5,1.0000,0.0000,0.0000,0.0000,1
4264,19039964,5675710797,409019335,30284,1,-1,nan,False,5,0.0000,0.0000,1.0000,0.0000,1
4267,19039967,5676086544,409019335,8708,1,-1,nan,False,5,1.0000,0.0000,0.0000,0.0000,1
4320,19040020,5955312309,409019335,1105,1,-1,nan,False,5,1.0000,0.0000,0.0000,0.0000,1
4378,19040078,6194097632,409019335,14654,1,-1,nan,False,2,0.0000,0.0000,1.0000,0.0000,3
4381,19040081,6194452540,409019335,24758,1,-1,nan,False,2,0.0000,0.0000,1.0000,0.0000,3
4394,19040094,6196329951,409019335,20534,1,-1,nan,False,2,0.0000,0.0000,1.0000,0.0000,3
4768,24110948,1512927,515668244,10852,1,-1,nan,False,5,1.0000,0.0000,0.0000,0.0000,1
4802,24110982,88761260,515668244,1501,1,-1,nan,False,5,1.0000,0.0000,0.0000,0.0000,1
4837,24111017,175093339,515668244,7926,1,-1,nan,False,5,1.0000,0.0000,0.0000,0.0000,1
4856,24111036,1086933420,515668244,31657,1,-1,nan,False,5,1.0000,0.0000,0.0000,0.0000,1
4901,24111081,1767404043,515668244,27845,1,-1,nan,False,5,1.0000,0.0000,0.0000,0.0000,1
5139,28850503,17464048404,616580486,25401,1,-1,nan,False,5,1.0000,0.0000,0.0000,0.0000,1
5142,28850506,17464545108,616580486,14443,1,-1,nan,False,5,1.0000,0.0000,0.0000,0.0000,1
5155,28850519,17466624045,616580486,28455,1,-1,nan,False,5,1.0000,0.0000,0.0000,0.0000,1
5158,28850522,17468992678,616580486,22362,1,-1,nan,False,5,1.0000,0.0000,0.0000,0.0000,16
5171,28850535,17819075687,616580486,13379,1,-1,nan,False,5,1.0000,0.0000,0.0000,0.0000,1
5174,28850538,17819450094,616580486,24250,1,-1,nan,False,5,1.0000,0.0000,0.0000,0.0000,1
5177,28850541,17819918503,616580486,1105,1,-1,nan,False,5,1.0000,0.0000,0.0000,0.0000,1
5190,28850554,17886190344,616580486,28621,1,-1,nan,False,5,1.0000,0.0000,0.0000,0.0000,1
5193,28850557,17886418715,616580486,8330,1,-1,nan,False,5,1.0000,0.0000,0.0000,0.0000,1
5206,28850570,17888330866,616580486,24985,1,-1,nan,False,5,1.0000,0.0000,0.0000,0.0000,1
5229,28850593,18423922582,616580486,24697,1,-1,nan,False,5,1.0000,0.0000,0.0000,0.0000,1
5252,28850616,18510552864,616580486,22089,1,-1,nan,False,5,1.0000,0.0000,0.0000,0.0000,1
5259,28850623,18510742345,616580486,14287,1,-1,nan,False,5,0.0000,0.0000,1.0000,0.0000,1
5282,28850646,18679487590,616580486,16034,1,-1,nan,False,5,1.0000,0.0000,0.0000,0.0000,1
5285,28850649,18679744090,616580486,26921,1,-1,nan,False,5,1.0000,0.0000,0.0000,0.0000,1
5288,28850652,18679938974,616580486,22034,1,-1,nan,False,5,1.0000,0.0000,0.0000,0.0000,1
5355,28850719,19720274165,616580486,12007,1,-1,nan,False,5,1.0000,0.0000,0.0000,0.0000,1
5383,28850747,19891011837,616580486,10540,1,-1,nan,False,1,1.0000,0.0000,0.0000,0.0000,0
5385,28850749,19940669121,616580486,30207,1,-1,nan,False,5,1.0000,0.0000,0.0000,0.0000,1
5438,28850802,21782802496,616580486,29695,1,-1,nan,False,6,1.0000,0.0000,0.0000,0.0000,4
5484,28850848,22129215933,616580486,32625,1,-1,nan,False,2,1.0000,0.0000,0.0000,0.0000,3
5491,28850855,22129653895,616580486,3153,1,-1,nan,False,2,0.0000,1.0000,0.0000,0.0000,3
5628,28850992,22222945007,616580486,23855,1,-1,nan,False,4,1.0000,0.0000,0.0000,0.0000,6
5632,28850996,22223279011,616580486,32168,1,-1,nan,False,4,1.0000,0.0000,0.0000,0.0000,6
5681,28851045,22286115492,616580486,19184,1,-1,nan,False,4,1.0000,0.0000,0.0000,0.0000,6
5739,28851103,22630557050,616580486,89,1,-1,nan,False,5,1.0000,0.0000,0.0000,0.0000,1
5742,28851106,22630855470,616580486,27845,1,-1,nan,False,5,1.0000,0.0000,0.0000,0.0000,1
5745,28851109,22631364385,616580486,30284,1,-1,nan,False,5,0.0000,0.0000,1.0000,0.0000,1
5748,28851112,22642509320,616580486,8708,1,-1,nan,False,5,1.0000,0.0000,0.0000,0.0000,1
5755,28851119,22644050372,616580486,18545,1,-1,nan,False,5,1.0000,0.0000,0.0000,0.0000,1
5805,28851169,22739165290,616580486,12655,1,-1,nan,False,5,0.0000,0.0000,1.0000,0.0000,1
5828,28851192,22741591931,616580486,32135,1,-1,nan,False,5,0.0000,0.0000,1.0000,0.0000,1
5831,28851195,22742373745,616580486,23165,1,-1,nan,False,5,1.0000,0.0000,0.0000,0.0000,1
5864,28851228,22914914715,616580486,7949,1,-1,nan,False,5,1.0000,0.0000,0.0000,0.0000,1
5867,28851231,22916229939,616580486,7477,1,-1,nan,False,5,1.0000,0.0000,0.0000,0.0000,1
5885,28851249,22985624220,616580486,18186,1,-1,nan,False,4,1.0000,0.0000,0.0000,0.0000,6
5954,28851318,23435525703,616580486,20804,1,-1,nan,False,5,0.0000,0.0000,1.0000,0.0000,1
6036,28851400,23864246050,616580486,12811,1,-1,nan,False,5,1.0000,0.0000,0.0000,0.0000,1
6039,28851403,23864512143,616580486,7926,1,-1,nan,False,5,1.0000,0.0000,0.0000,0.0000,1
6042,28851406,23864791459,616580486,13471,1,-1,nan,False,5,0.0000,0.0000,1.0000,0.0000,1
6045,28851409,23865180462,616580486,1907,1,-1,nan,False,6,1.0000,0.0000,0.0000,0.0000,4
6050,28851414,23865591959,616580486,17807,1,-1,nan,False,6,1.0000,0.0000,0.0000,0.0000,4
6055,28851419,23866155462,616580486,17326,1,-1,nan,False,6,1.0000,0.0000,0.0000,0.0000,4
6060,28851424,23866726815,616580486,24908,1,-1,nan,False,6,0.0000,0.0000,1.0000,0.0000,4
6071,28851435,23867620909,616580486,8317,1,-1,nan,False,1,1.0000,0.0000,0.0000,0.0000,13
6100,28851464,23934081437,616580486,14931,1,-1,nan,False,6,0.0000,0.0000,1.0000,0.0000,4
6105,28851469,23934557407,616580486,18704,1,-1,nan,False,6,1.0000,0.0000,0.0000,0.0000,4
6140,28851504,23942778482,616580486,28034,1,-1,nan,False,4,0.0000,0.0000,1.0000,0.0000,6
6196,28851560,24035390437,616580486,28511,1,-1,nan,False,5,1.0000,0.0000,0.0000,0.0000,1
6207,28851571,24040244595,616580486,12472,1,-1,nan,False,5,1.0000,0.0000,0.0000,0.0000,1
6210,28851574,24040461789,616580486,2918,1,-1,nan,False,5,1.0000,0.0000,0.0000,0.0000,1
6243,28851607,24123585783,616580486,3852,1,-1,nan,False,4,0.0000,0.0000,1.0000,0.0000,6
6247,28851611,24124335311,616580486,13256,1,-1,nan,False,4,0.0000,0.0000,1.0000,0.0000,6
6261,28851625,24199029027,616580486,12469,1,-1,nan,False,1,0.0000,0.0000,1.0000,0.0000,13
6353,28851717,24640689350,616580486,14942,1,-1,nan,False,5,1.0000,0.0000,0.0000,0.0000,1
6356,28851720,24641830358,616580486,484,1,-1,nan,False,5,1.0000,0.0000,0.0000,0.0000,1
6359,28851723,24642151666,616580486,9896,1,-1,nan,False,5,1.0000,0.0000,0.0000,0.0000,1
6429,28851793,24808070396,616580486,1501,1,-1,nan,False,5,1.0000,0.0000,0.0000,0.0000,1
6431,28851795,24808521835,616580486,14811,1,-1,nan,False,5,0.0000,0.0000,1.0000,0.0000,1
6457,28851821,24818124113,616580486,10852,1,-1,nan,False,5,1.0000,0.0000,0.0000,0.0000,1
6460,28851824,24818539467,616580486,17124,1,-1,nan,False,5,1.0000,0.0000,0.0000,0.0000,1
6468,28851832,25068027649,616580486,26335,1,-1,nan,False,5,1.0000,0.0000,0.0000,0.0000,1
6471,28851835,25071199460,616580486,27339,1,-1,nan,False,5,1.0000,0.0000,0.0000,0.0000,1
6474,28851838,25071458910,616580486,17914,1,-1,nan,False,5,1.0000,0.0000,0.0000,0.0000,1
6527,28851891,28095480688,616580486,21411,1,-1,nan,False,2,0.0000,0.0000,1.0000,0.0000,3
6570,28851934,28267552313,616580486,24758,1,-1,nan,False,2,0.0000,0.0000,1.0000,0.0000,3
6592,28851956,28272605503,616580486,18467,1,-1,nan,False,1,0.0000,0.0000,1.0000,0.0000,13
6632,28851996,28353137907,616580486,31613,1,-1,nan,False,3,1.0000,0.0000,0.0000,0.0000,2
6654,28852018,28358371176,616580486,20843,1,-1,nan,False,3,0.0000,0.0000,1.0000,0.0000,2
6707,28852071,28705729724,616580486,10688,1,-1,nan,False,7,1.0000,0.0000,0.0000,0.0000,5
6734,28852098,28786364878,616580486,8693,1,-1,nan,False,2,0.0000,0.0000,1.0000,0.0000,3
6735,28852099,28787569428,616580486,26852,1,-1,nan,False,2,1.0000,0.0000,0.0000,0.0000,3
6777,28852141,28866815202,616580486,10217,1,-1,nan,False,7,1.0000,0.0000,0.0000,0.0000,5
6791,28852155,28876296069,616580486,17519,1,-1,nan,False,7,1.0000,0.0000,0.0000,0.0000,5
6845,28852209,28960275116,616580486,21094,1,-1,nan,False,3,0.0000,0.0000,1.0000,0.0000,2
6861,28852225,28964057691,616580486,10052,1,-1,nan,False,7,1.0000,0.0000,0.0000,0.0000,5
6887,28852251,29051494871,616580486,22792,1,-1,nan,False,4,0.0000,0.0000,1.0000,0.0000,6
6933,28852297,29311020745,616580486,32146,1,-1,nan,False,7,0.0000,0.0000,1.0000,0.0000,5
6963,28852327,29395343552,616580486,1003,1,-1,nan,False,7,1.0000,0.0000,0.0000,0.0000,5
6994,28852358,29474283176,616580486,20590,1,-1,nan,False,7,1.0000,0.0000,0.0000,0.0000,5
7011,28852375,29557943618,616580486,7385,1,-1,nan,False,7,1.0000,0.0000,0.0000,0.0000,5
7042,28852406,29650516817,616580486,32095,1,-1,nan,False,7,0.0000,0.0000,1.0000,0.0000,5
7067,28852431,30084806810,616580486,5990,1,-1,nan,False,4,1.0000,0.0000,0.0000,0.0000,6
7112,28852476,30174651536,616580486,9212,1,-1,nan,False,4,1.0000,0.0000,0.0000,0.0000,6
7126,28852490,30248268842,616580486,12831,1,-1,nan,False,4,1.0000,0.0000,0.0000,0.0000,6
7392,34398679,580104592,736371818,1105,1,-1,nan,False,5,1.0000,0.0000,0.0000,0.0000,1
7490,35676792,854108,761800801,13379,1,-1,nan,False,5,1.0000,0.0000,0.0000,0.0000,1
7601,39750622,576695,845636456,2918,1,-1,nan,False,5,1.0000,0.0000,0.0000,0.0000,1
7645,39750666,2081043882,845636456,1501,1,-1,nan,False,5,1.0000,0.0000,0.0000,0.0000,1
7656,39750677,2081354636,845636456,27845,1,-1,nan,False,5,1.0000,0.0000,0.0000,0.0000,1
7673,39750694,2284530838,845636456,17326,1,-1,nan,False,6,1.0000,0.0000,0.0000,0.0000,4
7788,39750809,3127373389,845636456,26921,1,-1,nan,False,5,1.0000,0.0000,0.0000,0.0000,1
7791,39750812,3127500272,845636456,28621,1,-1,nan,False,5,1.0000,0.0000,0.0000,0.0000,1
7810,39750831,3128061579,845636456,29695,1,-1,nan,False,6,1.0000,0.0000,0.0000,0.0000,4
7852,39750873,6003941086,845636456,6808,1,-1,nan,False,2,0.0000,1.0000,0.0000,0.0000,3
7860,39750881,6004181660,845636456,27699,1,-1,nan,False,2,0.0000,1.0000,0.0000,0.0000,3
7883,39750904,6301776874,845636456,19744,1,-1,nan,False,2,1.0000,0.0000,0.0000,0.0000,3
8031,41392056,1136707186,878817883,2278,1,-1,nan,False,5,1.0000,0.0000,0.0000,0.0000,1
8038,41392063,1138005623,878817883,28621,1,-1,nan,False,5,1.0000,0.0000,0.0000,0.0000,1
8188,42460306,271440001,900124353,31613,1,-1,nan,False,3,1.0000,0.0000,0.0000,0.0000,2
8378,44974565,1581253309,951606580,26852,1,-1,nan,False,2,1.0000,0.0000,0.0000,0.0000,3
8379,44974566,1673509414,951606580,8317,1,-1,nan,False,1,1.0000,0.0000,0.0000,0.0000,13
8386,44974573,1844670149,951606580,12469,1,-1,nan,False,1,0.0000,0.0000,1.0000,0.0000,13
8393,44974580,1923086668,951606580,18467,1,-1,nan,False,1,0.0000,0.0000,1.0000,0.0000,13

In [66]:
train_mini[train_mini.user_id == 51771056]

,row_id,timestamp,user_id,content_id,content_type_id,task_container_id,user_answer,answered_correctly,prior_question_elapsed_time,prior_question_had_explanation
50,2420428,0,51771056,10733,0,0,1,1,14333.0000,True
51,2420429,0,51771056,10732,0,0,2,0,14333.0000,True
52,2420430,0,51771056,10731,0,0,3,1,14333.0000,True
53,2420431,147940,51771056,2820,0,1,1,1,14333.0000,True
54,2420432,147940,51771056,2819,0,1,0,1,14333.0000,True
55,2420433,147940,51771056,2818,0,1,0,0,14333.0000,True
56,2420434,301126,51771056,2623,0,2,2,1,24000.0000,True
57,2420435,301126,51771056,2624,0,2,0,1,24000.0000,True
58,2420436,301126,51771056,2625,0,2,3,0,24000.0000,True
59,2420437,468350,51771056,2940,0,3,2,0,22666.0000,True
60,2420438,468350,51771056,2942,0,3,0,0,22666.0000,True
61,2420439,468350,51771056,2941,0,3,1,1,22666.0000,True
62,2420440,782950,51771056,3228,0,4,3,1,23666.0000,True
63,2420441,782950,51771056,3229,0,4,2,1,23666.0000,True
64,2420442,782950,51771056,3230,0,4,0,0,23666.0000,True
65,2420443,29098393,51771056,10857,0,5,0,0,16666.0000,True
66,2420444,29098393,51771056,10858,0,5,3,0,16666.0000,True
67,2420445,29098393,51771056,10855,0,5,3,1,16666.0000,True
68,2420446,29098393,51771056,10856,0,5,1,0,16666.0000,True
69,2420447,75088427,51771056,10834,0,6,0,1,53250.0000,True
70,2420448,75088427,51771056,10833,0,6,0,1,53250.0000,True
71,2420449,75088427,51771056,10831,0,6,2,0,53250.0000,True
72,2420450,75088427,51771056,10832,0,6,1,1,53250.0000,True
73,2420451,75377509,51771056,10282,0,7,0,1,32750.0000,True
74,2420452,75377509,51771056,10281,0,7,2,1,32750.0000,True
75,2420453,75377509,51771056,10280,0,7,0,1,32750.0000,True
76,2420454,75377509,51771056,10283,0,7,0,0,32750.0000,True
77,2420455,76007301,51771056,10272,0,8,3,1,37750.0000,True
78,2420456,76007301,51771056,10273,0,8,3,0,37750.0000,True
79,2420457,76007301,51771056,10274,0,8,3,1,37750.0000,True
80,2420458,76007301,51771056,10275,0,8,0,1,37750.0000,True
81,2420459,76848953,51771056,6803,0,9,2,0,24500.0000,True
82,2420460,76848953,51771056,6801,0,9,2,1,24500.0000,True
83,2420461,76848953,51771056,6804,0,9,1,1,24500.0000,True
84,2420462,76848953,51771056,6802,0,9,0,1,24500.0000,True
85,2420463,77565937,51771056,7148,0,10,1,1,66750.0000,True
86,2420464,77565937,51771056,7147,0,10,0,0,66750.0000,True
87,2420465,77565937,51771056,7145,0,10,2,1,66750.0000,True
88,2420466,77565937,51771056,7149,0,10,0,1,66750.0000,True
89,2420467,77565937,51771056,7146,0,10,2,0,66750.0000,True
90,2420468,78463792,51771056,6962,0,11,0,1,87400.0000,True
91,2420469,78463792,51771056,6963,0,11,2,1,87400.0000,True
92,2420470,78463792,51771056,6964,0,11,3,1,87400.0000,True
93,2420471,78463792,51771056,6961,0,11,2,0,87400.0000,True
94,2420472,78463792,51771056,6965,0,11,1,1,87400.0000,True
95,2420473,79487416,51771056,7390,0,12,3,0,105400.0000,True
96,2420474,79487416,51771056,7388,0,12,1,0,105400.0000,True
97,2420475,79487416,51771056,7389,0,12,0,1,105400.0000,True
98,2420476,79487416,51771056,7386,0,12,1,0,105400.0000,True
99,2420477,79487416,51771056,7387,0,12,3,1,105400.0000,True
100,2420478,85453640,51771056,22711,1,13,-1,-1,nan,False
101,2420479,85527879,51771056,7981,0,14,1,1,123000.0000,True
102,2420480,85593707,51771056,6,0,15,3,0,24000.0000,True
103,2420481,85664366,51771056,10415,0,16,1,1,25000.0000,True
104,2420482,85710815,51771056,199,0,17,3,1,26000.0000,True
105,2420483,85752474,51771056,1103,0,18,1,1,16000.0000,True
106,2420484,85812854,51771056,981,0,19,3,1,19000.0000,True
107,2420485,85861409,51771056,279,0,20,0,1,20000.0000,True
108,2420486,85904659,51771056,1310,0,21,3,1,18000.0000,True
109,2420487,85944038,51771056,242,0,22,3,1,17000.0000,True
110,2420488,86035097,51771056,10733,0,23,1,1,18000.0000,True
111,2420489,86035097,51771056,10732,0,23,1,1,18000.0000,True
112,2420490,86035097,51771056,10731,0,23,3,1,18000.0000,True
113,2420491,86132187,51771056,2819,0,24,1,0,25333.0000,True
114,2420492,86132187,51771056,2818,0,24,1,1,25333.0000,True
115,2420493,86132187,51771056,2820,0,24,1,1,25333.0000,True
116,2420494,149614692,51771056,1941,0,25,2,1,20666.0000,True
117,2420495,149614692,51771056,1942,0,25,1,1,20666.0000,True
118,2420496,149614692,51771056,1940,0,25,2,0,20666.0000,True
119,2420497,149810235,51771056,2044,0,26,0,0,14667.0000,True
120,2420498,149810235,51771056,2043,0,26,0,1,14667.0000,True
121,2420499,149810235,51771056,2042,0,26,1,1,14667.0000,True
122,2420500,150020296,51771056,2119,0,27,0,0,22667.0000,True
123,2420501,150020296,51771056,2118,0,27,3,0,22667.0000,True
124,2420502,150020296,51771056,2117,0,27,3,0,22667.0000,True
125,2420503,150184468,51771056,2258,0,28,3,1,29333.0000,True
126,2420504,150184468,51771056,2257,0,28,3,0,29333.0000,True
127,2420505,150184468,51771056,2259,0,28,3,0,29333.0000,True
128,2420506,150435720,51771056,1876,0,29,0,0,24333.0000,True
129,2420507,150435720,51771056,1874,0,29,0,0,24333.0000,True
130,2420508,150435720,51771056,1875,0,29,3,0,24333.0000,True
131,2420509,150817666,51771056,23815,1,30,-1,-1,nan,False
132,2420510,153633437,51771056,7185,0,31,1,1,43667.0000,True
133,2420511,153633437,51771056,7186,0,31,0,1,43667.0000,True
134,2420512,153633437,51771056,7184,0,31,0,1,43667.0000,True
135,2420513,154513160,51771056,7712,0,32,2,1,63333.0000,True
136,2420514,154513160,51771056,7709,0,32,0,1,63333.0000,True
137,2420515,154513160,51771056,7710,0,32,1,0,63333.0000,True
138,2420516,154513160,51771056,7711,0,32,1,1,63333.0000,True
139,2420517,154513160,51771056,7713,0,32,2,1,63333.0000,True
140,2420518,155070820,51771056,7823,0,33,3,0,56600.0000,True
141,2420519,155070820,51771056,7821,0,33,3,0,56600.0000,True
142,2420520,155070820,51771056,7822,0,33,1,1,56600.0000,True
143,2420521,155070820,51771056,7820,0,33,2,0,56600.0000,True
144,2420522,202159396,51771056,1980,0,34,3,0,92750.0000,True
145,2420523,202159396,51771056,1979,0,34,2,1,92750.0000,True
146,2420524,202159396,51771056,1981,0,34,1,1,92750.0000,True
147,2420525,202278675,51771056,1605,0,35,1,1,29333.0000,True
148,2420526,202278675,51771056,1606,0,35,3,1,29333.0000,True
149,2420527,202278675,51771056,1604,0,35,3,0,29333.0000,True
150,2420528,202414052,51771056,1879,0,36,2,1,22666.0000,True
151,2420529,202414052,51771056,1877,0,36,2,1,22666.0000,True
152,2420530,202414052,51771056,1878,0,36,1,1,22666.0000,True
153,2420531,202584924,51771056,2484,0,37,3,0,25333.0000,True
154,2420532,202584924,51771056,2482,0,37,3,0,25333.0000,True
155,2420533,202584924,51771056,2483,0,37,2,1,25333.0000,True
156,2420534,202721519,51771056,2087,0,38,3,1,26000.0000,True
157,2420535,202721519,51771056,2088,0,38,3,1,26000.0000,True
158,2420536,202721519,51771056,2089,0,38,1,1,26000.0000,True
159,2420537,203030959,51771056,10081,0,39,2,1,23000.0000,True
160,2420538,203030959,51771056,10079,0,39,0,0,23000.0000,True
161,2420539,203030959,51771056,10080,0,39,1,1,23000.0000,True
162,2420540,203030959,51771056,10078,0,39,0,1,23000.0000,True
163,2420541,203378000,51771056,6519,0,40,3,0,39750.0000,True
164,2420542,203378000,51771056,6520,0,40,3,0,39750.0000,True
165,2420543,203378000,51771056,6517,0,40,3,1,39750.0000,True
166,2420544,203378000,51771056,6518,0,40,0,1,39750.0000,True
167,2420545,203648168,51771056,11174,0,41,2,1,30250.0000,True
168,2420546,203648168,51771056,11172,0,41,0,1,30250.0000,True
169,2420547,203648168,51771056,11173,0,41,2,0,30250.0000,True
170,2420548,203648168,51771056,11171,0,41,0,1,30250.0000,True
171,2420549,203839649,51771056,10069,0,42,2,1,26000.0000,True
172,2420550,203839649,51771056,10067,0,42,1,0,26000.0000,True
173,2420551,203839649,51771056,10066,0,42,1,1,26000.0000,True
174,2420552,203839649,51771056,10068,0,42,0,1,26000.0000,True
175,2420553,204130046,51771056,32570,1,43,-1,-1,nan,False
176,2420554,204767306,51771056,9495,0,45,1,0,26250.0000,True
177,2420555,204862856,51771056,5178,0,46,1,1,21000.0000,True
178,2420556,204896107,51771056,6476,0,47,1,1,28000.0000,True
179,2420557,204920867,51771056,5593,0,48,0,1,7000.0000,True
180,2420558,204950525,51771056,9489,0,49,1,1,16000.0000,True
181,2420559,204973982,51771056,4260,0,50,0,1,20000.0000,True
182,2420560,205003162,51771056,8619,0,51,1,1,15000.0000,True
183,2420561,205038458,51771056,4585,0,52,0,1,14000.0000,True
184,2420562,205100442,51771056,9438,0,53,3,1,13000.0000,True
185,2420563,205138475,51771056,4664,0,54,3,1,35000.0000,True
186,2420564,205175334,51771056,3871,0,55,0,1,10000.0000,True
187,2420565,205205179,51771056,8719,0,56,3,1,11000.0000,True
188,2420566,205256107,51771056,3966,0,57,0,0,8000.0000,True
189,2420567,205337398,51771056,8641,0,58,0,1,26000.0000,True
190,2420568,205386250,51771056,5466,0,59,3,1,33000.0000,True
191,2420569,205410949,51771056,9098,0,60,1,1,10000.0000,True
192,2420570,205439790,51771056,5168,0,61,1,1,12000.0000,True
193,2420571,205460885,51771056,8653,0,62,3,1,17000.0000,True
194,2420572,205492912,51771056,8471,0,63,1,1,9000.0000,True
195,2420573,205551122,51771056,9779,0,64,1,1,21000.0000,True
196,2420574,205678246,51771056,8616,0,65,1,1,16000.0000,True
197,2420575,205713862,51771056,11531,0,66,2,1,14000.0000,True
198,2420576,205741642,51771056,4534,0,67,1,1,20000.0000,True
199,2420577,205769591,51771056,6664,0,68,3,1,12000.0000,True
200,2420578,205798879,51771056,6339,0,69,0,1,14000.0000,True
201,2420579,205864580,51771056,8262,0,70,0,0,7000.0000,True
202,2420580,206264042,51771056,6183,0,71,3,1,31000.0000,True
203,2420581,206319391,51771056,5676,0,72,3,0,5000.0000,True
204,2420582,206421546,51771056,6118,0,73,3,0,26000.0000,True
205,2420583,206505826,51771056,9234,0,74,0,1,35000.0000,True
206,2420584,206536555,51771056,5674,0,75,2,1,27000.0000,True
207,2420585,206583283,51771056,11479,0,76,1,1,7000.0000,True
208,2420586,206658079,51771056,4495,0,77,0,1,17000.0000,True
209,2420587,206724526,51771056,4416,0,78,0,0,15000.0000,True
210,2420588,206776505,51771056,6056,0,79,1,1,15000.0000,True
211,2420589,206861603,51771056,9254,0,80,2,0,18000.0000,True
212,2420590,206920346,51771056,5856,0,82,3,1,23000.0000,True
213,2420591,280367093,51771056,10231,0,83,0,1,9000.0000,True
214,2420592,280367093,51771056,10229,0,83,1,0,9000.0000,True
215,2420593,280367093,51771056,10228,0,83,0,1,9000.0000,True
216,2420594,280367093,51771056,10230,0,83,0,0,9000.0000,True
217,2420595,281539660,51771056,10148,0,84,0,1,41500.0000,True
218,2420596,281539660,51771056,10150,0,84,0,0,41500.0000,True
219,2420597,281539660,51771056,10149,0,84,2,1,41500.0000,True
220,2420598,281539660,51771056,10151,0,84,0,1,41500.0000,True
221,2420599,282638604,51771056,10071,0,85,1,1,26500.0000,True
222,2420600,282638604,51771056,10073,0,85,2,0,26500.0000,True
223,2420601,282638604,51771056,10072,0,85,0,1,26500.0000,True
224,2420602,282638604,51771056,10070,0,85,1,0,26500.0000,True
225,2420603,282950400,51771056,6867,0,86,3,1,23500.0000,True
226,2420604,282950400,51771056,6868,0,86,3,0,23500.0000,True
227,2420605,282950400,51771056,6865,0,86,2,0,23500.0000,True
228,2420606,282950400,51771056,6866,0,86,3,1,23500.0000,True
229,2420607,283146278,51771056,12354,1,87,-1,-1,nan,False
230,2420608,286177331,51771056,7949,1,81,-1,-1,nan,False
231,2420609,286302450,51771056,9254,0,88,0,0,27250.0000,True
232,2420610,286370013,51771056,3966,0,89,2,1,77000.0000,True
233,2420611,286408472,51771056,3599,0,90,1,1,10000.0000,True
234,2420612,402788047,51771056,834,0,91,3,1,21000.0000,False
235,2420613,402976713,51771056,6766,0,92,0,1,17000.0000,True
236,2420614,402976713,51771056,6765,0,92,1,1,17000.0000,True
237,2420615,402976713,51771056,6768,0,92,3,1,17000.0000,True
238,2420616,402976713,51771056,6767,0,92,1,1,17000.0000,True
239,2420617,403174070,51771056,10840,0,93,2,1,32250.0000,True
240,2420618,403174070,51771056,10842,0,93,1,1,32250.0000,True
241,2420619,403174070,51771056,10841,0,93,2,1,32250.0000,True
242,2420620,403174070,51771056,10839,0,93,3,0,32250.0000,True
243,2420621,403351006,51771056,6878,0,94,1,1,28750.0000,True
244,2420622,403351006,51771056,6879,0,94,3,0,28750.0000,True
245,2420623,403351006,51771056,6877,0,94,2,1,28750.0000,True
246,2420624,403351006,51771056,6880,0,94,0,1,28750.0000,True
247,2420625,406525042,51771056,13550,1,95,-1,-1,nan,False
248,2420626,406574702,51771056,11929,0,96,3,1,21750.0000,True
249,2420627,407503932,51771056,1359,0,97,0,0,17000.0000,True
250,2420628,408438229,51771056,1236,0,98,1,0,17000.0000,True
251,2420629,408471581,51771056,923,0,99,0,1,21000.0000,True
252,2420630,408507858,51771056,11943,0,100,0,0,18000.0000,True
253,2420631,408540073,51771056,1147,0,101,0,1,17000.0000,True
254,2420632,408579825,51771056,239,0,102,3,0,14000.0000,True
255,2420633,408630185,51771056,488,0,103,3,1,22000.0000,True
256,2420634,408668004,51771056,12159,0,104,0,1,22000.0000,True
257,2420635,408708084,51771056,375,0,105,3,0,16000.0000,True
258,2420636,408783271,51771056,1362,0,106,1,0,19000.0000,True
259,2420637,408829402,51771056,784,0,107,0,0,17000.0000,True
260,2420638,408859031,51771056,11962,0,108,1,1,19000.0000,True
261,2420639,408891381,51771056,589,0,109,3,1,17000.0000,True
262,2420640,408931594,51771056,296,0,110,0,1,19000.0000,True
263,2420641,408973082,51771056,904,0,111,1,0,17000.0000,True
264,2420642,409003765,51771056,11946,0,112,3,1,17000.0000,True
265,2420643,409029381,51771056,762,0,113,0,0,18000.0000,True
266,2420644,409059982,51771056,704,0,114,1,1,16000.0000,True
267,2420645,409209093,51771056,738,0,115,3,0,20000.0000,True
268,2420646,409243093,51771056,3153,1,116,-1,-1,nan,False
269,2420647,409273363,51771056,738,0,117,3,0,17000.0000,True
270,2420648,409310872,51771056,762,0,118,3,1,17000.0000,True
271,2420649,409373565,51771056,11967,0,119,0,1,18000.0000,True
272,2420650,409429992,51771056,549,0,120,1,1,17000.0000,True
273,2420651,409498881,51771056,1362,0,122,0,1,22000.0000,True
274,2420652,409514401,51771056,254,0,121,0,0,15000.0000,True
275,2420653,409538323,51771056,254,0,123,3,1,23000.0000,True
276,2420654,409582691,51771056,1111,0,124,3,1,18000.0000,True
277,2420655,409613756,51771056,12191,0,125,0,1,16000.0000,True
278,2420656,409644408,51771056,1028,0,126,0,1,16000.0000,True
279,2420657,409683860,51771056,217,0,127,0,1,14000.0000,True
280,2420658,409860664,51771056,853,0,128,1,0,18000.0000,True
281,2420659,409930199,51771056,29544,1,129,-1,-1,nan,False
282,2420660,409951204,51771056,738,0,130,1,1,18000.0000,True
283,2420661,409985177,51771056,853,0,131,1,0,16000.0000,True
284,2420662,410074310,51771056,9489,0,132,3,0,19000.0000,True
285,2420663,410131604,51771056,4465,0,133,1,0,17000.0000,True
286,2420664,410182243,51771056,704,0,134,1,1,26000.0000,True
287,2420665,410347558,51771056,10855,0,135,1,0,19000.0000,True
288,2420666,410347558,51771056,10856,0,135,0,0,19000.0000,True
289,2420667,410347558,51771056,10858,0,135,0,1,19000.0000,True
290,2420668,410347558,51771056,10857,0,135,1,1,19000.0000,True
291,2420669,410413834,51771056,5178,0,136,1,1,32000.0000,True
292,2420670,410451017,51771056,407,0,137,3,1,27000.0000,True
293,2420671,410483442,51771056,8471,0,138,1,1,17000.0000,True
294,2420672,410511892,51771056,423,0,139,1,1,16000.0000,True
295,2420673,410541023,51771056,11479,0,140,1,1,16000.0000,True
296,2420674,410560441,51771056,5626,0,141,1,1,8000.0000,True
297,2420675,410592045,51771056,5593,0,142,0,1,8000.0000,True
298,2420676,410626652,51771056,7981,0,143,1,1,17000.0000,True
299,2420677,410734901,51771056,2257,0,144,0,1,24000.0000,True
300,2420678,410734901,51771056,2258,0,144,3,1,24000.0000,True
301,2420679,410734901,51771056,2259,0,144,2,0,24000.0000,True
302,2420680,410802231,51771056,549,0,145,1,1,23666.0000,True
303,2420681,410843931,51771056,8516,0,146,2,1,21000.0000,True
304,2420682,410869405,51771056,4416,0,147,1,1,13000.0000,True
305,2420683,410905753,51771056,12081,0,148,3,1,4000.0000,True
306,2420684,411746459,51771056,13447,0,149,0,1,20000.0000,True
307,2420685,413120860,51771056,7492,0,150,3,1,9000.0000,True
308,2420686,413120860,51771056,7493,0,150,0,1,9000.0000,True
309,2420687,413120860,51771056,7489,0,150,3,1,9000.0000,True
310,2420688,413120860,51771056,7491,0,150,1,1,9000.0000,True
311,2420689,413120860,51771056,7490,0,150,2,1,9000.0000,True
312,2420690,413251410,51771056,11637,0,151,2,1,67000.0000,True
313,2420691,413251410,51771056,11638,0,151,1,1,67000.0000,True
314,2420692,413251410,51771056,11639,0,151,2,1,67000.0000,True
315,2420693,413511540,51771056,8059,0,152,3,0,38000.0000,True
316,2420694,413511540,51771056,8062,0,152,3,1,38000.0000,True
317,2420695,413511540,51771056,8061,0,152,3,0,38000.0000,True
318,2420696,413511540,51771056,8063,0,152,2,1,38000.0000,True
319,2420697,413511540,51771056,8060,0,152,3,1,38000.0000,True
320,2420698,413707888,51771056,20307,1,153,-1,-1,nan,False
321,2420699,418458385,51771056,7008,0,155,3,1,43400.0000,True
322,2420700,418458385,51771056,7006,0,155,0,1,43400.0000,True
323,2420701,418458385,51771056,7007,0,155,1,1,43400.0000,True
324,2420702,418458385,51771056,7009,0,155,3,1,43400.0000,True
325,2420703,418458385,51771056,7010,0,155,2,1,43400.0000,True
326,2420704,418489418,51771056,1236,0,156,0,1,59200.0000,True
327,2420705,418688177,51771056,11579,0,157,3,1,18000.0000,True
328,2420706,418688177,51771056,11575,0,157,2,1,18000.0000,True
329,2420707,418688177,51771056,11578,0,157,0,1,18000.0000,True
330,2420708,418688177,51771056,11576,0,157,1,1,18000.0000,True
331,2420709,418688177,51771056,11577,0,157,0,1,18000.0000,True
332,2420710,418722756,51771056,1002,0,158,3,1,37800.0000,True
333,2420711,418756653,51771056,12232,0,159,0,1,21000.0000,True
334,2420712,418803760,51771056,1362,0,160,0,1,17000.0000,True
335,2420713,418919118,51771056,10151,0,161,0,1,15000.0000,True
336,2420714,418919118,51771056,10150,0,161,3,1,15000.0000,True
337,2420715,418919118,51771056,10148,0,161,0,1,15000.0000,True
338,2420716,418919118,51771056,10149,0,161,2,1,15000.0000,True
339,2420717,418982359,51771056,6670,0,162,1,0,20500.0000,True
340,2420718,419056405,51771056,239,0,163,3,0,13000.0000,True
341,2420719,419096277,51771056,4585,0,164,0,1,20000.0000,True
342,2420720,419201743,51771056,4908,0,165,0,1,5000.0000,True
343,2420721,419345365,51771056,5268,0,166,3,1,32000.0000,True
344,2420722,419413311,51771056,4100,0,167,0,1,29000.0000,True
345,2420723,419437353,51771056,279,0,168,0,1,2000.0000,True
346,2420724,419510486,51771056,10620,0,169,1,1,14000.0000,True
347,2420725,419574144,51771056,10543,0,170,0,0,23000.0000,True
348,2420726,419636366,51771056,12801,0,171,3,0,27000.0000,True
349,2420727,419677446,51771056,7908,0,172,1,1,21000.0000,True
350,2420728,419773997,51771056,62,0,173,0,1,22000.0000,True
351,2420729,419872589,51771056,165,0,174,3,1,23000.0000,True
352,2420730,420077879,51771056,12227,0,175,3,1,23000.0000,True
353,2420731,420300512,51771056,915,0,176,3,1,16000.0000,True
354,2420732,420496856,51771056,1114,0,177,0,0,27000.0000,True
355,2420733,420669085,51771056,1298,0,178,0,1,16000.0000,True
356,2420734,420771155,51771056,12016,0,179,0,1,16000.0000,True
357,2420735,420878480,51771056,1194,0,180,1,0,18000.0000,True
358,2420736,420936570,51771056,254,0,182,3,1,19000.0000,True
359,2420737,420956017,51771056,1362,0,183,0,1,18000.0000,True
360,2420738,420978214,51771056,1036,0,181,1,0,11000.0000,True
361,2420739,421001883,51771056,1036,0,184,0,1,18000.0000,True
362,2420740,421042492,51771056,1194,0,185,3,1,20000.0000,True
363,2420741,421080114,51771056,1112,0,186,1,1,16000.0000,True
364,2420742,421124510,51771056,12018,0,187,0,0,19000.0000,True
365,2420743,421162640,51771056,12098,0,188,3,1,17000.0000,True
366,2420744,422915805,51771056,13312,0,154,1,0,15000.0000,True
367,2420745,425844751,51771056,12148,0,189,3,1,22000.0000,True
368,2420746,427645631,51771056,2070,0,190,0,1,17000.0000,True
369,2420747,427645631,51771056,2069,0,190,3,0,17000.0000,True
370,2420748,427645631,51771056,2071,0,190,1,1,17000.0000,True
371,2420749,427820667,51771056,2336,0,191,1,1,25333.0000,True
372,2420750,427820667,51771056,2337,0,191,3,1,25333.0000,True
373,2420751,427820667,51771056,2335,0,191,0,1,25333.0000,True
374,2420752,427967929,51771056,1623,0,192,3,1,31666.0000,True
375,2420753,427967929,51771056,1624,0,192,2,1,31666.0000,True

In [68]:
vitrine[(vitrine.user_id == 51771056)]

,id,timestamp,user_id,content_id,content_type_id,answered_correctly,prior_question_elapsed_time,prior_question_had_explanation,part,concept,intention,solving_question,starter,kmean_cluster
50,2420428,0,51771056,10733,0,1,14333.0000,True,4,nan,nan,nan,nan,12
51,2420429,0,51771056,10732,0,0,14333.0000,True,4,nan,nan,nan,nan,12
52,2420430,0,51771056,10731,0,1,14333.0000,True,4,nan,nan,nan,nan,12
53,2420431,147940,51771056,2820,0,1,14333.0000,True,4,nan,nan,nan,nan,12
54,2420432,147940,51771056,2819,0,1,14333.0000,True,4,nan,nan,nan,nan,12
55,2420433,147940,51771056,2818,0,0,14333.0000,True,4,nan,nan,nan,nan,12
56,2420434,301126,51771056,2623,0,1,24000.0000,True,4,nan,nan,nan,nan,12
57,2420435,301126,51771056,2624,0,1,24000.0000,True,4,nan,nan,nan,nan,12
58,2420436,301126,51771056,2625,0,0,24000.0000,True,4,nan,nan,nan,nan,12
59,2420437,468350,51771056,2940,0,0,22666.0000,True,4,nan,nan,nan,nan,6
60,2420438,468350,51771056,2942,0,0,22666.0000,True,4,nan,nan,nan,nan,6
61,2420439,468350,51771056,2941,0,1,22666.0000,True,4,nan,nan,nan,nan,6
62,2420440,782950,51771056,3228,0,1,23666.0000,True,4,nan,nan,nan,nan,6
63,2420441,782950,51771056,3229,0,1,23666.0000,True,4,nan,nan,nan,nan,6
64,2420442,782950,51771056,3230,0,0,23666.0000,True,4,nan,nan,nan,nan,6
65,2420443,29098393,51771056,10857,0,0,16666.0000,True,6,nan,nan,nan,nan,4
66,2420444,29098393,51771056,10858,0,0,16666.0000,True,6,nan,nan,nan,nan,4
67,2420445,29098393,51771056,10855,0,1,16666.0000,True,6,nan,nan,nan,nan,4
68,2420446,29098393,51771056,10856,0,0,16666.0000,True,6,nan,nan,nan,nan,4
69,2420447,75088427,51771056,10834,0,1,53250.0000,True,6,nan,nan,nan,nan,4
70,2420448,75088427,51771056,10833,0,1,53250.0000,True,6,nan,nan,nan,nan,4
71,2420449,75088427,51771056,10831,0,0,53250.0000,True,6,nan,nan,nan,nan,4
72,2420450,75088427,51771056,10832,0,1,53250.0000,True,6,nan,nan,nan,nan,4
73,2420451,75377509,51771056,10282,0,1,32750.0000,True,6,nan,nan,nan,nan,4
74,2420452,75377509,51771056,10281,0,1,32750.0000,True,6,nan,nan,nan,nan,4
75,2420453,75377509,51771056,10280,0,1,32750.0000,True,6,nan,nan,nan,nan,4
76,2420454,75377509,51771056,10283,0,0,32750.0000,True,6,nan,nan,nan,nan,4
77,2420455,76007301,51771056,10272,0,1,37750.0000,True,6,nan,nan,nan,nan,4
78,2420456,76007301,51771056,10273,0,0,37750.0000,True,6,nan,nan,nan,nan,4
79,2420457,76007301,51771056,10274,0,1,37750.0000,True,6,nan,nan,nan,nan,4
80,2420458,76007301,51771056,10275,0,1,37750.0000,True,6,nan,nan,nan,nan,4
81,2420459,76848953,51771056,6803,0,0,24500.0000,True,6,nan,nan,nan,nan,4
82,2420460,76848953,51771056,6801,0,1,24500.0000,True,6,nan,nan,nan,nan,4
83,2420461,76848953,51771056,6804,0,1,24500.0000,True,6,nan,nan,nan,nan,4
84,2420462,76848953,51771056,6802,0,1,24500.0000,True,6,nan,nan,nan,nan,4
85,2420463,77565937,51771056,7148,0,1,66750.0000,True,7,nan,nan,nan,nan,15
86,2420464,77565937,51771056,7147,0,0,66750.0000,True,7,nan,nan,nan,nan,15
87,2420465,77565937,51771056,7145,0,1,66750.0000,True,7,nan,nan,nan,nan,15
88,2420466,77565937,51771056,7149,0,1,66750.0000,True,7,nan,nan,nan,nan,15
89,2420467,77565937,51771056,7146,0,0,66750.0000,True,7,nan,nan,nan,nan,15
90,2420468,78463792,51771056,6962,0,1,87400.0000,True,7,nan,nan,nan,nan,15
91,2420469,78463792,51771056,6963,0,1,87400.0000,True,7,nan,nan,nan,nan,15
92,2420470,78463792,51771056,6964,0,1,87400.0000,True,7,nan,nan,nan,nan,15
93,2420471,78463792,51771056,6961,0,0,87400.0000,True,7,nan,nan,nan,nan,15
94,2420472,78463792,51771056,6965,0,1,87400.0000,True,7,nan,nan,nan,nan,15
95,2420473,79487416,51771056,7390,0,0,105400.0000,True,7,nan,nan,nan,nan,15
96,2420474,79487416,51771056,7388,0,0,105400.0000,True,7,nan,nan,nan,nan,15
97,2420475,79487416,51771056,7389,0,1,105400.0000,True,7,nan,nan,nan,nan,15
98,2420476,79487416,51771056,7386,0,0,105400.0000,True,7,nan,nan,nan,nan,15
99,2420477,79487416,51771056,7387,0,1,105400.0000,True,7,nan,nan,nan,nan,15
100,2420478,85453640,51771056,22711,1,-1,nan,False,6,1.0000,0.0000,0.0000,0.0000,4
101,2420479,85527879,51771056,7981,0,1,123000.0000,True,1,nan,nan,nan,nan,13
102,2420480,85593707,51771056,6,0,0,24000.0000,True,1,nan,nan,nan,nan,13
103,2420481,85664366,51771056,10415,0,1,25000.0000,True,1,nan,nan,nan,nan,0
104,2420482,85710815,51771056,199,0,1,26000.0000,True,2,nan,nan,nan,nan,3
105,2420483,85752474,51771056,1103,0,1,16000.0000,True,2,nan,nan,nan,nan,3
106,2420484,85812854,51771056,981,0,1,19000.0000,True,2,nan,nan,nan,nan,11
107,2420485,85861409,51771056,279,0,1,20000.0000,True,2,nan,nan,nan,nan,11
108,2420486,85904659,51771056,1310,0,1,18000.0000,True,2,nan,nan,nan,nan,3
109,2420487,85944038,51771056,242,0,1,17000.0000,True,2,nan,nan,nan,nan,3
110,2420488,86035097,51771056,10733,0,1,18000.0000,True,4,nan,nan,nan,nan,12
111,2420489,86035097,51771056,10732,0,1,18000.0000,True,4,nan,nan,nan,nan,12
112,2420490,86035097,51771056,10731,0,1,18000.0000,True,4,nan,nan,nan,nan,12
113,2420491,86132187,51771056,2819,0,0,25333.0000,True,4,nan,nan,nan,nan,12
114,2420492,86132187,51771056,2818,0,1,25333.0000,True,4,nan,nan,nan,nan,12
115,2420493,86132187,51771056,2820,0,1,25333.0000,True,4,nan,nan,nan,nan,12
116,2420494,149614692,51771056,1941,0,1,20666.0000,True,3,nan,nan,nan,nan,9
117,2420495,149614692,51771056,1942,0,1,20666.0000,True,3,nan,nan,nan,nan,9
118,2420496,149614692,51771056,1940,0,0,20666.0000,True,3,nan,nan,nan,nan,9
119,2420497,149810235,51771056,2044,0,0,14667.0000,True,3,nan,nan,nan,nan,8
120,2420498,149810235,51771056,2043,0,1,14667.0000,True,3,nan,nan,nan,nan,8
121,2420499,149810235,51771056,2042,0,1,14667.0000,True,3,nan,nan,nan,nan,8
122,2420500,150020296,51771056,2119,0,0,22667.0000,True,3,nan,nan,nan,nan,2
123,2420501,150020296,51771056,2118,0,0,22667.0000,True,3,nan,nan,nan,nan,2
124,2420502,150020296,51771056,2117,0,0,22667.0000,True,3,nan,nan,nan,nan,2
125,2420503,150184468,51771056,2258,0,1,29333.0000,True,3,nan,nan,nan,nan,2
126,2420504,150184468,51771056,2257,0,0,29333.0000,True,3,nan,nan,nan,nan,2
127,2420505,150184468,51771056,2259,0,0,29333.0000,True,3,nan,nan,nan,nan,2
128,2420506,150435720,51771056,1876,0,0,24333.0000,True,3,nan,nan,nan,nan,2
129,2420507,150435720,51771056,1874,0,0,24333.0000,True,3,nan,nan,nan,nan,2
130,2420508,150435720,51771056,1875,0,0,24333.0000,True,3,nan,nan,nan,nan,2
131,2420509,150817666,51771056,23815,1,-1,nan,False,3,1.0000,0.0000,0.0000,0.0000,2
132,2420510,153633437,51771056,7185,0,1,43667.0000,True,7,nan,nan,nan,nan,5
133,2420511,153633437,51771056,7186,0,1,43667.0000,True,7,nan,nan,nan,nan,5
134,2420512,153633437,51771056,7184,0,1,43667.0000,True,7,nan,nan,nan,nan,5
135,2420513,154513160,51771056,7712,0,1,63333.0000,True,7,nan,nan,nan,nan,15
136,2420514,154513160,51771056,7709,0,1,63333.0000,True,7,nan,nan,nan,nan,15
137,2420515,154513160,51771056,7710,0,0,63333.0000,True,7,nan,nan,nan,nan,15
138,2420516,154513160,51771056,7711,0,1,63333.0000,True,7,nan,nan,nan,nan,15
139,2420517,154513160,51771056,7713,0,1,63333.0000,True,7,nan,nan,nan,nan,15
140,2420518,155070820,51771056,7823,0,0,56600.0000,True,7,nan,nan,nan,nan,5
141,2420519,155070820,51771056,7821,0,0,56600.0000,True,7,nan,nan,nan,nan,5
142,2420520,155070820,51771056,7822,0,1,56600.0000,True,7,nan,nan,nan,nan,5
143,2420521,155070820,51771056,7820,0,0,56600.0000,True,7,nan,nan,nan,nan,5
144,2420522,202159396,51771056,1980,0,0,92750.0000,True,3,nan,nan,nan,nan,2
145,2420523,202159396,51771056,1979,0,1,92750.0000,True,3,nan,nan,nan,nan,2
146,2420524,202159396,51771056,1981,0,1,92750.0000,True,3,nan,nan,nan,nan,2
147,2420525,202278675,51771056,1605,0,1,29333.0000,True,3,nan,nan,nan,nan,2
148,2420526,202278675,51771056,1606,0,1,29333.0000,True,3,nan,nan,nan,nan,2
149,2420527,202278675,51771056,1604,0,0,29333.0000,True,3,nan,nan,nan,nan,2
150,2420528,202414052,51771056,1879,0,1,22666.0000,True,3,nan,nan,nan,nan,2
151,2420529,202414052,51771056,1877,0,1,22666.0000,True,3,nan,nan,nan,nan,2
152,2420530,202414052,51771056,1878,0,1,22666.0000,True,3,nan,nan,nan,nan,2
153,2420531,202584924,51771056,2484,0,0,25333.0000,True,3,nan,nan,nan,nan,2
154,2420532,202584924,51771056,2482,0,0,25333.0000,True,3,nan,nan,nan,nan,2
155,2420533,202584924,51771056,2483,0,1,25333.0000,True,3,nan,nan,nan,nan,2
156,2420534,202721519,51771056,2087,0,1,26000.0000,True,3,nan,nan,nan,nan,2
157,2420535,202721519,51771056,2088,0,1,26000.0000,True,3,nan,nan,nan,nan,2
158,2420536,202721519,51771056,2089,0,1,26000.0000,True,3,nan,nan,nan,nan,2
159,2420537,203030959,51771056,10081,0,1,23000.0000,True,6,nan,nan,nan,nan,4
160,2420538,203030959,51771056,10079,0,0,23000.0000,True,6,nan,nan,nan,nan,4
161,2420539,203030959,51771056,10080,0,1,23000.0000,True,6,nan,nan,nan,nan,4
162,2420540,203030959,51771056,10078,0,1,23000.0000,True,6,nan,nan,nan,nan,4
163,2420541,203378000,51771056,6519,0,0,39750.0000,True,6,nan,nan,nan,nan,4
164,2420542,203378000,51771056,6520,0,0,39750.0000,True,6,nan,nan,nan,nan,4
165,2420543,203378000,51771056,6517,0,1,39750.0000,True,6,nan,nan,nan,nan,4
166,2420544,203378000,51771056,6518,0,1,39750.0000,True,6,nan,nan,nan,nan,4
167,2420545,203648168,51771056,11174,0,1,30250.0000,True,6,nan,nan,nan,nan,4
168,2420546,203648168,51771056,11172,0,1,30250.0000,True,6,nan,nan,nan,nan,4
169,2420547,203648168,51771056,11173,0,0,30250.0000,True,6,nan,nan,nan,nan,4
170,2420548,203648168,51771056,11171,0,1,30250.0000,True,6,nan,nan,nan,nan,4
171,2420549,203839649,51771056,10069,0,1,26000.0000,True,6,nan,nan,nan,nan,4
172,2420550,203839649,51771056,10067,0,0,26000.0000,True,6,nan,nan,nan,nan,4
173,2420551,203839649,51771056,10066,0,1,26000.0000,True,6,nan,nan,nan,nan,4
174,2420552,203839649,51771056,10068,0,1,26000.0000,True,6,nan,nan,nan,nan,4
175,2420553,204130046,51771056,32570,1,-1,nan,False,3,0.0000,0.0000,1.0000,0.0000,2
176,2420554,204767306,51771056,9495,0,0,26250.0000,True,5,nan,nan,nan,nan,1
177,2420555,204862856,51771056,5178,0,1,21000.0000,True,5,nan,nan,nan,nan,1
178,2420556,204896107,51771056,6476,0,1,28000.0000,True,5,nan,nan,nan,nan,1
179,2420557,204920867,51771056,5593,0,1,7000.0000,True,5,nan,nan,nan,nan,1
180,2420558,204950525,51771056,9489,0,1,16000.0000,True,5,nan,nan,nan,nan,1
181,2420559,204973982,51771056,4260,0,1,20000.0000,True,5,nan,nan,nan,nan,1
182,2420560,205003162,51771056,8619,0,1,15000.0000,True,5,nan,nan,nan,nan,1
183,2420561,205038458,51771056,4585,0,1,14000.0000,True,5,nan,nan,nan,nan,1
184,2420562,205100442,51771056,9438,0,1,13000.0000,True,5,nan,nan,nan,nan,1
185,2420563,205138475,51771056,4664,0,1,35000.0000,True,5,nan,nan,nan,nan,1
186,2420564,205175334,51771056,3871,0,1,10000.0000,True,5,nan,nan,nan,nan,1
187,2420565,205205179,51771056,8719,0,1,11000.0000,True,5,nan,nan,nan,nan,1
188,2420566,205256107,51771056,3966,0,0,8000.0000,True,5,nan,nan,nan,nan,1
189,2420567,205337398,51771056,8641,0,1,26000.0000,True,5,nan,nan,nan,nan,1
190,2420568,205386250,51771056,5466,0,1,33000.0000,True,5,nan,nan,nan,nan,1
191,2420569,205410949,51771056,9098,0,1,10000.0000,True,5,nan,nan,nan,nan,1
192,2420570,205439790,51771056,5168,0,1,12000.0000,True,5,nan,nan,nan,nan,1
193,2420571,205460885,51771056,8653,0,1,17000.0000,True,5,nan,nan,nan,nan,1
194,2420572,205492912,51771056,8471,0,1,9000.0000,True,5,nan,nan,nan,nan,1
195,2420573,205551122,51771056,9779,0,1,21000.0000,True,5,nan,nan,nan,nan,1
196,2420574,205678246,51771056,8616,0,1,16000.0000,True,5,nan,nan,nan,nan,1
197,2420575,205713862,51771056,11531,0,1,14000.0000,True,5,nan,nan,nan,nan,1
198,2420576,205741642,51771056,4534,0,1,20000.0000,True,5,nan,nan,nan,nan,1
199,2420577,205769591,51771056,6664,0,1,12000.0000,True,5,nan,nan,nan,nan,1
200,2420578,205798879,51771056,6339,0,1,14000.0000,True,5,nan,nan,nan,nan,1
201,2420579,205864580,51771056,8262,0,0,7000.0000,True,5,nan,nan,nan,nan,1
202,2420580,206264042,51771056,6183,0,1,31000.0000,True,5,nan,nan,nan,nan,1
203,2420581,206319391,51771056,5676,0,0,5000.0000,True,5,nan,nan,nan,nan,1
204,2420582,206421546,51771056,6118,0,0,26000.0000,True,5,nan,nan,nan,nan,1
205,2420583,206505826,51771056,9234,0,1,35000.0000,True,5,nan,nan,nan,nan,1
206,2420584,206536555,51771056,5674,0,1,27000.0000,True,5,nan,nan,nan,nan,1
207,2420585,206583283,51771056,11479,0,1,7000.0000,True,5,nan,nan,nan,nan,1
208,2420586,206658079,51771056,4495,0,1,17000.0000,True,5,nan,nan,nan,nan,1
209,2420587,206724526,51771056,4416,0,0,15000.0000,True,5,nan,nan,nan,nan,1
210,2420588,206776505,51771056,6056,0,1,15000.0000,True,5,nan,nan,nan,nan,1
211,2420589,206861603,51771056,9254,0,0,18000.0000,True,5,nan,nan,nan,nan,1
212,2420590,206920346,51771056,5856,0,1,23000.0000,True,5,nan,nan,nan,nan,1
213,2420591,280367093,51771056,10231,0,1,9000.0000,True,6,nan,nan,nan,nan,4
214,2420592,280367093,51771056,10229,0,0,9000.0000,True,6,nan,nan,nan,nan,4
215,2420593,280367093,51771056,10228,0,1,9000.0000,True,6,nan,nan,nan,nan,4
216,2420594,280367093,51771056,10230,0,0,9000.0000,True,6,nan,nan,nan,nan,4
217,2420595,281539660,51771056,10148,0,1,41500.0000,True,6,nan,nan,nan,nan,4
218,2420596,281539660,51771056,10150,0,0,41500.0000,True,6,nan,nan,nan,nan,4
219,2420597,281539660,51771056,10149,0,1,41500.0000,True,6,nan,nan,nan,nan,4
220,2420598,281539660,51771056,10151,0,1,41500.0000,True,6,nan,nan,nan,nan,4
221,2420599,282638604,51771056,10071,0,1,26500.0000,True,6,nan,nan,nan,nan,4
222,2420600,282638604,51771056,10073,0,0,26500.0000,True,6,nan,nan,nan,nan,4
223,2420601,282638604,51771056,10072,0,1,26500.0000,True,6,nan,nan,nan,nan,4
224,2420602,282638604,51771056,10070,0,0,26500.0000,True,6,nan,nan,nan,nan,4
225,2420603,282950400,51771056,6867,0,1,23500.0000,True,6,nan,nan,nan,nan,4
226,2420604,282950400,51771056,6868,0,0,23500.0000,True,6,nan,nan,nan,nan,4
227,2420605,282950400,51771056,6865,0,0,23500.0000,True,6,nan,nan,nan,nan,4
228,2420606,282950400,51771056,6866,0,1,23500.0000,True,6,nan,nan,nan,nan,4
229,2420607,283146278,51771056,12354,1,-1,nan,False,6,1.0000,0.0000,0.0000,0.0000,4
230,2420608,286177331,51771056,7949,1,-1,nan,False,5,1.0000,0.0000,0.0000,0.0000,1
231,2420609,286302450,51771056,9254,0,0,27250.0000,True,5,nan,nan,nan,nan,1
232,2420610,286370013,51771056,3966,0,1,77000.0000,True,5,nan,nan,nan,nan,1
233,2420611,286408472,51771056,3599,0,1,10000.0000,True,5,nan,nan,nan,nan,1
234,2420612,402788047,51771056,834,0,1,21000.0000,False,2,nan,nan,nan,nan,3
235,2420613,402976713,51771056,6766,0,1,17000.0000,True,6,nan,nan,nan,nan,4
236,2420614,402976713,51771056,6765,0,1,17000.0000,True,6,nan,nan,nan,nan,4
237,2420615,402976713,51771056,6768,0,1,17000.0000,True,6,nan,nan,nan,nan,4
238,2420616,402976713,51771056,6767,0,1,17000.0000,True,6,nan,nan,nan,nan,4
239,2420617,403174070,51771056,10840,0,1,32250.0000,True,6,nan,nan,nan,nan,4
240,2420618,403174070,51771056,10842,0,1,32250.0000,True,6,nan,nan,nan,nan,4
241,2420619,403174070,51771056,10841,0,1,32250.0000,True,6,nan,nan,nan,nan,4
242,2420620,403174070,51771056,10839,0,0,32250.0000,True,6,nan,nan,nan,nan,4
243,2420621,403351006,51771056,6878,0,1,28750.0000,True,6,nan,nan,nan,nan,4
244,2420622,403351006,51771056,6879,0,0,28750.0000,True,6,nan,nan,nan,nan,4
245,2420623,403351006,51771056,6877,0,1,28750.0000,True,6,nan,nan,nan,nan,4
246,2420624,403351006,51771056,6880,0,1,28750.0000,True,6,nan,nan,nan,nan,4
247,2420625,406525042,51771056,13550,1,-1,nan,False,6,1.0000,0.0000,0.0000,0.0000,4
248,2420626,406574702,51771056,11929,0,1,21750.0000,True,2,nan,nan,nan,nan,11
249,2420627,407503932,51771056,1359,0,0,17000.0000,True,2,nan,nan,nan,nan,3
250,2420628,408438229,51771056,1236,0,0,17000.0000,True,2,nan,nan,nan,nan,3
251,2420629,408471581,51771056,923,0,1,21000.0000,True,2,nan,nan,nan,nan,3
252,2420630,408507858,51771056,11943,0,0,18000.0000,True,2,nan,nan,nan,nan,3
253,2420631,408540073,51771056,1147,0,1,17000.0000,True,2,nan,nan,nan,nan,3
254,2420632,408579825,51771056,239,0,0,14000.0000,True,2,nan,nan,nan,nan,3
255,2420633,408630185,51771056,488,0,1,22000.0000,True,2,nan,nan,nan,nan,11
256,2420634,408668004,51771056,12159,0,1,22000.0000,True,2,nan,nan,nan,nan,9
257,2420635,408708084,51771056,375,0,0,16000.0000,True,2,nan,nan,nan,nan,3
258,2420636,408783271,51771056,1362,0,0,19000.0000,True,2,nan,nan,nan,nan,10
259,2420637,408829402,51771056,784,0,0,17000.0000,True,2,nan,nan,nan,nan,3
260,2420638,408859031,51771056,11962,0,1,19000.0000,True,2,nan,nan,nan,nan,11
261,2420639,408891381,51771056,589,0,1,17000.0000,True,2,nan,nan,nan,nan,11
262,2420640,408931594,51771056,296,0,1,19000.0000,True,2,nan,nan,nan,nan,9
263,2420641,408973082,51771056,904,0,0,17000.0000,True,2,nan,nan,nan,nan,11
264,2420642,409003765,51771056,11946,0,1,17000.0000,True,2,nan,nan,nan,nan,3
265,2420643,409029381,51771056,762,0,0,18000.0000,True,2,nan,nan,nan,nan,9
266,2420644,409059982,51771056,704,0,1,16000.0000,True,2,nan,nan,nan,nan,11
267,2420645,409209093,51771056,738,0,0,20000.0000,True,2,nan,nan,nan,nan,11
268,2420646,409243093,51771056,3153,1,-1,nan,False,2,0.0000,1.0000,0.0000,0.0000,3
269,2420647,409273363,51771056,738,0,0,17000.0000,True,2,nan,nan,nan,nan,11
270,2420648,409310872,51771056,762,0,1,17000.0000,True,2,nan,nan,nan,nan,9
271,2420649,409373565,51771056,11967,0,1,18000.0000,True,2,nan,nan,nan,nan,11
272,2420650,409429992,51771056,549,0,1,17000.0000,True,2,nan,nan,nan,nan,3
273,2420651,409498881,51771056,1362,0,1,22000.0000,True,2,nan,nan,nan,nan,10
274,2420652,409514401,51771056,254,0,0,15000.0000,True,2,nan,nan,nan,nan,10
275,2420653,409538323,51771056,254,0,1,23000.0000,True,2,nan,nan,nan,nan,10
276,2420654,409582691,51771056,1111,0,1,18000.0000,True,2,nan,nan,nan,nan,3
277,2420655,409613756,51771056,12191,0,1,16000.0000,True,2,nan,nan,nan,nan,3
278,2420656,409644408,51771056,1028,0,1,16000.0000,True,2,nan,nan,nan,nan,10
279,2420657,409683860,51771056,217,0,1,14000.0000,True,2,nan,nan,nan,nan,3
280,2420658,409860664,51771056,853,0,0,18000.0000,True,2,nan,nan,nan,nan,3
281,2420659,409930199,51771056,29544,1,-1,nan,False,2,1.0000,0.0000,0.0000,0.0000,3
282,2420660,409951204,51771056,738,0,1,18000.0000,True,2,nan,nan,nan,nan,11
283,2420661,409985177,51771056,853,0,0,16000.0000,True,2,nan,nan,nan,nan,3
284,2420662,410074310,51771056,9489,0,0,19000.0000,True,5,nan,nan,nan,nan,1
285,2420663,410131604,51771056,4465,0,0,17000.0000,True,5,nan,nan,nan,nan,1
286,2420664,410182243,51771056,704,0,1,26000.0000,True,2,nan,nan,nan,nan,11
287,2420665,410347558,51771056,10855,0,0,19000.0000,True,6,nan,nan,nan,nan,4
288,2420666,410347558,51771056,10856,0,0,19000.0000,True,6,nan,nan,nan,nan,4
289,2420667,410347558,51771056,10858,0,1,19000.0000,True,6,nan,nan,nan,nan,4
290,2420668,410347558,51771056,10857,0,1,19000.0000,True,6,nan,nan,nan,nan,4
291,2420669,410413834,51771056,5178,0,1,32000.0000,True,5,nan,nan,nan,nan,1
292,2420670,410451017,51771056,407,0,1,27000.0000,True,2,nan,nan,nan,nan,10
293,2420671,410483442,51771056,8471,0,1,17000.0000,True,5,nan,nan,nan,nan,1
294,2420672,410511892,51771056,423,0,1,16000.0000,True,2,nan,nan,nan,nan,3
295,2420673,410541023,51771056,11479,0,1,16000.0000,True,5,nan,nan,nan,nan,1
296,2420674,410560441,51771056,5626,0,1,8000.0000,True,5,nan,nan,nan,nan,1
297,2420675,410592045,51771056,5593,0,1,8000.0000,True,5,nan,nan,nan,nan,1
298,2420676,410626652,51771056,7981,0,1,17000.0000,True,1,nan,nan,nan,nan,13
299,2420677,410734901,51771056,2257,0,1,24000.0000,True,3,nan,nan,nan,nan,2
300,2420678,410734901,51771056,2258,0,1,24000.0000,True,3,nan,nan,nan,nan,2
301,2420679,410734901,51771056,2259,0,0,24000.0000,True,3,nan,nan,nan,nan,2
302,2420680,410802231,51771056,549,0,1,23666.0000,True,2,nan,nan,nan,nan,3
303,2420681,410843931,51771056,8516,0,1,21000.0000,True,5,nan,nan,nan,nan,1
304,2420682,410869405,51771056,4416,0,1,13000.0000,True,5,nan,nan,nan,nan,1
305,2420683,410905753,51771056,12081,0,1,4000.0000,True,2,nan,nan,nan,nan,9
306,2420684,411746459,51771056,13447,0,1,20000.0000,True,5,nan,nan,nan,nan,1
307,2420685,413120860,51771056,7492,0,1,9000.0000,True,7,nan,nan,nan,nan,15
308,2420686,413120860,51771056,7493,0,1,9000.0000,True,7,nan,nan,nan,nan,15
309,2420687,413120860,51771056,7489,0,1,9000.0000,True,7,nan,nan,nan,nan,15

In [71]:
vitrine[(vitrine.user_id == 51771056) & (vitrine.content_type_id == 1)]

,id,timestamp,user_id,content_id,content_type_id,answered_correctly,prior_question_elapsed_time,prior_question_had_explanation,part,concept,intention,solving_question,starter,kmean_cluster
100,2420478,85453640,51771056,22711,1,-1,nan,False,6,1.0000,0.0000,0.0000,0.0000,4
131,2420509,150817666,51771056,23815,1,-1,nan,False,3,1.0000,0.0000,0.0000,0.0000,2
175,2420553,204130046,51771056,32570,1,-1,nan,False,3,0.0000,0.0000,1.0000,0.0000,2
229,2420607,283146278,51771056,12354,1,-1,nan,False,6,1.0000,0.0000,0.0000,0.0000,4
230,2420608,286177331,51771056,7949,1,-1,nan,False,5,1.0000,0.0000,0.0000,0.0000,1
247,2420625,406525042,51771056,13550,1,-1,nan,False,6,1.0000,0.0000,0.0000,0.0000,4
268,2420646,409243093,51771056,3153,1,-1,nan,False,2,0.0000,1.0000,0.0000,0.0000,3
281,2420659,409930199,51771056,29544,1,-1,nan,False,2,1.0000,0.0000,0.0000,0.0000,3
320,2420698,413707888,51771056,20307,1,-1,nan,False,6,1.0000,0.0000,0.0000,0.0000,4
421,2420799,505963837,51771056,16363,1,-1,nan,False,6,1.0000,0.0000,0.0000,0.0000,4
451,2420829,519706895,51771056,18239,1,-1,nan,False,5,1.0000,0.0000,0.0000,0.0000,1
550,2420928,539054953,51771056,10354,1,-1,nan,False,6,1.0000,0.0000,0.0000,0.0000,4
560,2420938,539974509,51771056,1144,1,-1,nan,False,5,1.0000,0.0000,0.0000,0.0000,1
582,2420960,545318824,51771056,24402,1,-1,nan,False,1,1.0000,0.0000,0.0000,0.0000,0
586,2420964,545470129,51771056,10540,1,-1,nan,False,1,1.0000,0.0000,0.0000,0.0000,0
615,2420993,546964369,51771056,5588,1,-1,nan,False,6,1.0000,0.0000,0.0000,0.0000,4
695,2421073,630338878,51771056,24985,1,-1,nan,False,5,1.0000,0.0000,0.0000,0.0000,1
772,2421150,664065775,51771056,3937,1,-1,nan,False,6,1.0000,0.0000,0.0000,0.0000,4

In [72]:
vitrine[(vitrine.user_id == 51771056)]['concept'].value_counts()

1.0000    16
0.0000     2
Name: concept, dtype: int64

In [73]:
vitrine[(vitrine.user_id == 51771056) & (vitrine.concept == 1)]['part'].value_counts()

6    8
5    4
1    2
3    1
2    1
Name: part, dtype: int64

# Generate lecture features

In [4]:
def generate_lecture_features(df: pd.DataFrame) -> None:
    type_of_params = [#(field, name)
        "content_type_id",
        "concept",
        "intention",
        "solving_question",
        "starter",
    ]
    aggr_params = [# (aggr_list, name)
        (['user_id', 'part'], "user_part"),
        (['user_id', 'kmean_cluster'], "user_kmean_cluster"),
        (['user_id'], "user"),
    ]
    
    
    for type_of in type_of_params:
        
        type_of_name = ''
        if type_of != "content_type_id":
            type_of_name = f'_{type_of}'
            
        for aggr in aggr_params:
            name = f'lect_{aggr[1]}{type_of_name}'
            
            cum = vitrine.groupby(aggr[0])[type_of].agg(["cumsum"])
            cum.columns = [name]
            try:
                lect_features = pd.concat([lect_features, cum], axis = 1)
            except UnboundLocalError:
                lect_features = cum
    lect_features.fillna(0, inplace = True)
    return lect_features

In [5]:
lect_f = generate_lecture_features(vitrine)

In [7]:
vitrine.shape

(26892, 14)

In [6]:
lect_f.shape

(26892, 15)

In [53]:
vitrine = pd.concat([vitrine, lect_f], axis = 1)

In [54]:
vitrine

,id,timestamp,user_id,content_id,content_type_id,answered_correctly,prior_question_elapsed_time,prior_question_had_explanation,part,concept,intention,solving_question,starter,kmean_cluster,lect_user_part,lect_user_kmean_cluster,lect_user,lect_user_part_concept,lect_user_kmean_cluster_concept,lect_user_concept,lect_user_part_intention,lect_user_kmean_cluster_intention,lect_user_intention,lect_user_part_solving_question,lect_user_kmean_cluster_solving_question,lect_user_solving_question,lect_user_part_starter,lect_user_kmean_cluster_starter,lect_user_starter
0,365541,0,7136928,7900,0,0,nan,NaN,1,nan,nan,nan,nan,0,0,0,0,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000
1,365542,23989,7136928,7876,0,0,21000.0000,False,1,nan,nan,nan,nan,13,0,0,0,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000
2,365543,48079,7136928,175,0,0,20000.0000,False,1,nan,nan,nan,nan,13,0,0,0,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000
3,365544,74835,7136928,1278,0,0,21000.0000,False,2,nan,nan,nan,nan,11,0,0,0,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000
4,365545,192811,7136928,2063,0,0,20000.0000,False,3,nan,nan,nan,nan,9,0,0,0,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
26887,101109066,2313772645,2145262856,9106,0,0,18000.0000,True,5,nan,nan,nan,nan,1,9,9,13,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000
26888,101109067,2313888806,2145262856,4506,0,1,18000.0000,True,5,nan,nan,nan,nan,16,9,0,13,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000
26889,101109068,2314051785,2145262856,3854,0,0,25000.0000,True,5,nan,nan,nan,nan,1,9,9,13,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000
26890,101109069,2314404971,2145262856,4405,0,0,56000.0000,True,5,nan,nan,nan,nan,1,9,9,13,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000
26891,101109070,2314786293,2145262856,8954,0,0,37000.0000,True,5,nan,nan,nan,nan,1,9,9,13,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000

In [56]:
vitrine[vitrine.user_id == 7136928].lect_user.value_counts()

0    30
Name: lect_user, dtype: int64

In [35]:
lect_f

,lect_user_part,lect_user_kmean_cluster,lect_user_part,lect_user_part_concept,lect_user_kmean_cluster_concept,lect_user_part_concept,lect_user_part_intention,lect_user_kmean_cluster_intention,lect_user_part_intention,lect_user_part_solving_question,lect_user_kmean_cluster_solving_question,lect_user_part_solving_question,lect_user_part_starter,lect_user_kmean_cluster_starter,lect_user_part_starter
0,0,0,0,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan
1,0,0,0,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan
2,0,0,0,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan
3,0,0,0,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan
4,0,0,0,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
26887,9,9,9,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan
26888,9,0,9,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan
26889,9,9,9,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan
26890,9,9,9,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan
26891,9,9,9,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan

In [25]:
cum = []
param = [("content_type_id", 'lect')]

cum = vitrine.groupby(['user_id', 'part'])["content_type_id"].agg(["cumsum"])
vitrine = pd.concat([vitrine, cum], axis = 1)

In [27]:
vitrine[(vitrine.user_id == 51771056)]

,id,timestamp,user_id,content_id,content_type_id,answered_correctly,prior_question_elapsed_time,prior_question_had_explanation,part,concept,intention,solving_question,starter,kmean_cluster,cumsum,cumsum
50,2420428,0,51771056,10733,0,1,14333.0000,True,4,nan,nan,nan,nan,12,0,0
51,2420429,0,51771056,10732,0,0,14333.0000,True,4,nan,nan,nan,nan,12,0,0
52,2420430,0,51771056,10731,0,1,14333.0000,True,4,nan,nan,nan,nan,12,0,0
53,2420431,147940,51771056,2820,0,1,14333.0000,True,4,nan,nan,nan,nan,12,0,0
54,2420432,147940,51771056,2819,0,1,14333.0000,True,4,nan,nan,nan,nan,12,0,0
55,2420433,147940,51771056,2818,0,0,14333.0000,True,4,nan,nan,nan,nan,12,0,0
56,2420434,301126,51771056,2623,0,1,24000.0000,True,4,nan,nan,nan,nan,12,0,0
57,2420435,301126,51771056,2624,0,1,24000.0000,True,4,nan,nan,nan,nan,12,0,0
58,2420436,301126,51771056,2625,0,0,24000.0000,True,4,nan,nan,nan,nan,12,0,0
59,2420437,468350,51771056,2940,0,0,22666.0000,True,4,nan,nan,nan,nan,6,0,0
60,2420438,468350,51771056,2942,0,0,22666.0000,True,4,nan,nan,nan,nan,6,0,0
61,2420439,468350,51771056,2941,0,1,22666.0000,True,4,nan,nan,nan,nan,6,0,0
62,2420440,782950,51771056,3228,0,1,23666.0000,True,4,nan,nan,nan,nan,6,0,0
63,2420441,782950,51771056,3229,0,1,23666.0000,True,4,nan,nan,nan,nan,6,0,0
64,2420442,782950,51771056,3230,0,0,23666.0000,True,4,nan,nan,nan,nan,6,0,0
65,2420443,29098393,51771056,10857,0,0,16666.0000,True,6,nan,nan,nan,nan,4,0,0
66,2420444,29098393,51771056,10858,0,0,16666.0000,True,6,nan,nan,nan,nan,4,0,0
67,2420445,29098393,51771056,10855,0,1,16666.0000,True,6,nan,nan,nan,nan,4,0,0
68,2420446,29098393,51771056,10856,0,0,16666.0000,True,6,nan,nan,nan,nan,4,0,0
69,2420447,75088427,51771056,10834,0,1,53250.0000,True,6,nan,nan,nan,nan,4,0,0
70,2420448,75088427,51771056,10833,0,1,53250.0000,True,6,nan,nan,nan,nan,4,0,0
71,2420449,75088427,51771056,10831,0,0,53250.0000,True,6,nan,nan,nan,nan,4,0,0
72,2420450,75088427,51771056,10832,0,1,53250.0000,True,6,nan,nan,nan,nan,4,0,0
73,2420451,75377509,51771056,10282,0,1,32750.0000,True,6,nan,nan,nan,nan,4,0,0
74,2420452,75377509,51771056,10281,0,1,32750.0000,True,6,nan,nan,nan,nan,4,0,0
75,2420453,75377509,51771056,10280,0,1,32750.0000,True,6,nan,nan,nan,nan,4,0,0
76,2420454,75377509,51771056,10283,0,0,32750.0000,True,6,nan,nan,nan,nan,4,0,0
77,2420455,76007301,51771056,10272,0,1,37750.0000,True,6,nan,nan,nan,nan,4,0,0
78,2420456,76007301,51771056,10273,0,0,37750.0000,True,6,nan,nan,nan,nan,4,0,0
79,2420457,76007301,51771056,10274,0,1,37750.0000,True,6,nan,nan,nan,nan,4,0,0
80,2420458,76007301,51771056,10275,0,1,37750.0000,True,6,nan,nan,nan,nan,4,0,0
81,2420459,76848953,51771056,6803,0,0,24500.0000,True,6,nan,nan,nan,nan,4,0,0
82,2420460,76848953,51771056,6801,0,1,24500.0000,True,6,nan,nan,nan,nan,4,0,0
83,2420461,76848953,51771056,6804,0,1,24500.0000,True,6,nan,nan,nan,nan,4,0,0
84,2420462,76848953,51771056,6802,0,1,24500.0000,True,6,nan,nan,nan,nan,4,0,0
85,2420463,77565937,51771056,7148,0,1,66750.0000,True,7,nan,nan,nan,nan,15,0,0
86,2420464,77565937,51771056,7147,0,0,66750.0000,True,7,nan,nan,nan,nan,15,0,0
87,2420465,77565937,51771056,7145,0,1,66750.0000,True,7,nan,nan,nan,nan,15,0,0
88,2420466,77565937,51771056,7149,0,1,66750.0000,True,7,nan,nan,nan,nan,15,0,0
89,2420467,77565937,51771056,7146,0,0,66750.0000,True,7,nan,nan,nan,nan,15,0,0
90,2420468,78463792,51771056,6962,0,1,87400.0000,True,7,nan,nan,nan,nan,15,0,0
91,2420469,78463792,51771056,6963,0,1,87400.0000,True,7,nan,nan,nan,nan,15,0,0
92,2420470,78463792,51771056,6964,0,1,87400.0000,True,7,nan,nan,nan,nan,15,0,0
93,2420471,78463792,51771056,6961,0,0,87400.0000,True,7,nan,nan,nan,nan,15,0,0
94,2420472,78463792,51771056,6965,0,1,87400.0000,True,7,nan,nan,nan,nan,15,0,0
95,2420473,79487416,51771056,7390,0,0,105400.0000,True,7,nan,nan,nan,nan,15,0,0
96,2420474,79487416,51771056,7388,0,0,105400.0000,True,7,nan,nan,nan,nan,15,0,0
97,2420475,79487416,51771056,7389,0,1,105400.0000,True,7,nan,nan,nan,nan,15,0,0
98,2420476,79487416,51771056,7386,0,0,105400.0000,True,7,nan,nan,nan,nan,15,0,0
99,2420477,79487416,51771056,7387,0,1,105400.0000,True,7,nan,nan,nan,nan,15,0,0
100,2420478,85453640,51771056,22711,1,-1,nan,False,6,1.0000,0.0000,0.0000,0.0000,4,1,1
101,2420479,85527879,51771056,7981,0,1,123000.0000,True,1,nan,nan,nan,nan,13,1,0
102,2420480,85593707,51771056,6,0,0,24000.0000,True,1,nan,nan,nan,nan,13,1,0
103,2420481,85664366,51771056,10415,0,1,25000.0000,True,1,nan,nan,nan,nan,0,1,0
104,2420482,85710815,51771056,199,0,1,26000.0000,True,2,nan,nan,nan,nan,3,1,0
105,2420483,85752474,51771056,1103,0,1,16000.0000,True,2,nan,nan,nan,nan,3,1,0
106,2420484,85812854,51771056,981,0,1,19000.0000,True,2,nan,nan,nan,nan,11,1,0
107,2420485,85861409,51771056,279,0,1,20000.0000,True,2,nan,nan,nan,nan,11,1,0
108,2420486,85904659,51771056,1310,0,1,18000.0000,True,2,nan,nan,nan,nan,3,1,0
109,2420487,85944038,51771056,242,0,1,17000.0000,True,2,nan,nan,nan,nan,3,1,0
110,2420488,86035097,51771056,10733,0,1,18000.0000,True,4,nan,nan,nan,nan,12,1,0
111,2420489,86035097,51771056,10732,0,1,18000.0000,True,4,nan,nan,nan,nan,12,1,0
112,2420490,86035097,51771056,10731,0,1,18000.0000,True,4,nan,nan,nan,nan,12,1,0
113,2420491,86132187,51771056,2819,0,0,25333.0000,True,4,nan,nan,nan,nan,12,1,0
114,2420492,86132187,51771056,2818,0,1,25333.0000,True,4,nan,nan,nan,nan,12,1,0
115,2420493,86132187,51771056,2820,0,1,25333.0000,True,4,nan,nan,nan,nan,12,1,0
116,2420494,149614692,51771056,1941,0,1,20666.0000,True,3,nan,nan,nan,nan,9,1,0
117,2420495,149614692,51771056,1942,0,1,20666.0000,True,3,nan,nan,nan,nan,9,1,0
118,2420496,149614692,51771056,1940,0,0,20666.0000,True,3,nan,nan,nan,nan,9,1,0
119,2420497,149810235,51771056,2044,0,0,14667.0000,True,3,nan,nan,nan,nan,8,1,0
120,2420498,149810235,51771056,2043,0,1,14667.0000,True,3,nan,nan,nan,nan,8,1,0
121,2420499,149810235,51771056,2042,0,1,14667.0000,True,3,nan,nan,nan,nan,8,1,0
122,2420500,150020296,51771056,2119,0,0,22667.0000,True,3,nan,nan,nan,nan,2,1,0
123,2420501,150020296,51771056,2118,0,0,22667.0000,True,3,nan,nan,nan,nan,2,1,0
124,2420502,150020296,51771056,2117,0,0,22667.0000,True,3,nan,nan,nan,nan,2,1,0
125,2420503,150184468,51771056,2258,0,1,29333.0000,True,3,nan,nan,nan,nan,2,1,0
126,2420504,150184468,51771056,2257,0,0,29333.0000,True,3,nan,nan,nan,nan,2,1,0
127,2420505,150184468,51771056,2259,0,0,29333.0000,True,3,nan,nan,nan,nan,2,1,0
128,2420506,150435720,51771056,1876,0,0,24333.0000,True,3,nan,nan,nan,nan,2,1,0
129,2420507,150435720,51771056,1874,0,0,24333.0000,True,3,nan,nan,nan,nan,2,1,0
130,2420508,150435720,51771056,1875,0,0,24333.0000,True,3,nan,nan,nan,nan,2,1,0
131,2420509,150817666,51771056,23815,1,-1,nan,False,3,1.0000,0.0000,0.0000,0.0000,2,2,1
132,2420510,153633437,51771056,7185,0,1,43667.0000,True,7,nan,nan,nan,nan,5,2,0
133,2420511,153633437,51771056,7186,0,1,43667.0000,True,7,nan,nan,nan,nan,5,2,0
134,2420512,153633437,51771056,7184,0,1,43667.0000,True,7,nan,nan,nan,nan,5,2,0
135,2420513,154513160,51771056,7712,0,1,63333.0000,True,7,nan,nan,nan,nan,15,2,0
136,2420514,154513160,51771056,7709,0,1,63333.0000,True,7,nan,nan,nan,nan,15,2,0
137,2420515,154513160,51771056,7710,0,0,63333.0000,True,7,nan,nan,nan,nan,15,2,0
138,2420516,154513160,51771056,7711,0,1,63333.0000,True,7,nan,nan,nan,nan,15,2,0
139,2420517,154513160,51771056,7713,0,1,63333.0000,True,7,nan,nan,nan,nan,15,2,0
140,2420518,155070820,51771056,7823,0,0,56600.0000,True,7,nan,nan,nan,nan,5,2,0
141,2420519,155070820,51771056,7821,0,0,56600.0000,True,7,nan,nan,nan,nan,5,2,0
142,2420520,155070820,51771056,7822,0,1,56600.0000,True,7,nan,nan,nan,nan,5,2,0
143,2420521,155070820,51771056,7820,0,0,56600.0000,True,7,nan,nan,nan,nan,5,2,0
144,2420522,202159396,51771056,1980,0,0,92750.0000,True,3,nan,nan,nan,nan,2,2,1
145,2420523,202159396,51771056,1979,0,1,92750.0000,True,3,nan,nan,nan,nan,2,2,1
146,2420524,202159396,51771056,1981,0,1,92750.0000,True,3,nan,nan,nan,nan,2,2,1
147,2420525,202278675,51771056,1605,0,1,29333.0000,True,3,nan,nan,nan,nan,2,2,1
148,2420526,202278675,51771056,1606,0,1,29333.0000,True,3,nan,nan,nan,nan,2,2,1
149,2420527,202278675,51771056,1604,0,0,29333.0000,True,3,nan,nan,nan,nan,2,2,1
150,2420528,202414052,51771056,1879,0,1,22666.0000,True,3,nan,nan,nan,nan,2,2,1
151,2420529,202414052,51771056,1877,0,1,22666.0000,True,3,nan,nan,nan,nan,2,2,1
152,2420530,202414052,51771056,1878,0,1,22666.0000,True,3,nan,nan,nan,nan,2,2,1
153,2420531,202584924,51771056,2484,0,0,25333.0000,True,3,nan,nan,nan,nan,2,2,1
154,2420532,202584924,51771056,2482,0,0,25333.0000,True,3,nan,nan,nan,nan,2,2,1
155,2420533,202584924,51771056,2483,0,1,25333.0000,True,3,nan,nan,nan,nan,2,2,1
156,2420534,202721519,51771056,2087,0,1,26000.0000,True,3,nan,nan,nan,nan,2,2,1
157,2420535,202721519,51771056,2088,0,1,26000.0000,True,3,nan,nan,nan,nan,2,2,1
158,2420536,202721519,51771056,2089,0,1,26000.0000,True,3,nan,nan,nan,nan,2,2,1
159,2420537,203030959,51771056,10081,0,1,23000.0000,True,6,nan,nan,nan,nan,4,2,1
160,2420538,203030959,51771056,10079,0,0,23000.0000,True,6,nan,nan,nan,nan,4,2,1
161,2420539,203030959,51771056,10080,0,1,23000.0000,True,6,nan,nan,nan,nan,4,2,1
162,2420540,203030959,51771056,10078,0,1,23000.0000,True,6,nan,nan,nan,nan,4,2,1
163,2420541,203378000,51771056,6519,0,0,39750.0000,True,6,nan,nan,nan,nan,4,2,1
164,2420542,203378000,51771056,6520,0,0,39750.0000,True,6,nan,nan,nan,nan,4,2,1
165,2420543,203378000,51771056,6517,0,1,39750.0000,True,6,nan,nan,nan,nan,4,2,1
166,2420544,203378000,51771056,6518,0,1,39750.0000,True,6,nan,nan,nan,nan,4,2,1
167,2420545,203648168,51771056,11174,0,1,30250.0000,True,6,nan,nan,nan,nan,4,2,1
168,2420546,203648168,51771056,11172,0,1,30250.0000,True,6,nan,nan,nan,nan,4,2,1
169,2420547,203648168,51771056,11173,0,0,30250.0000,True,6,nan,nan,nan,nan,4,2,1
170,2420548,203648168,51771056,11171,0,1,30250.0000,True,6,nan,nan,nan,nan,4,2,1
171,2420549,203839649,51771056,10069,0,1,26000.0000,True,6,nan,nan,nan,nan,4,2,1
172,2420550,203839649,51771056,10067,0,0,26000.0000,True,6,nan,nan,nan,nan,4,2,1
173,2420551,203839649,51771056,10066,0,1,26000.0000,True,6,nan,nan,nan,nan,4,2,1
174,2420552,203839649,51771056,10068,0,1,26000.0000,True,6,nan,nan,nan,nan,4,2,1
175,2420553,204130046,51771056,32570,1,-1,nan,False,3,0.0000,0.0000,1.0000,0.0000,2,3,2
176,2420554,204767306,51771056,9495,0,0,26250.0000,True,5,nan,nan,nan,nan,1,3,0
177,2420555,204862856,51771056,5178,0,1,21000.0000,True,5,nan,nan,nan,nan,1,3,0
178,2420556,204896107,51771056,6476,0,1,28000.0000,True,5,nan,nan,nan,nan,1,3,0
179,2420557,204920867,51771056,5593,0,1,7000.0000,True,5,nan,nan,nan,nan,1,3,0
180,2420558,204950525,51771056,9489,0,1,16000.0000,True,5,nan,nan,nan,nan,1,3,0
181,2420559,204973982,51771056,4260,0,1,20000.0000,True,5,nan,nan,nan,nan,1,3,0
182,2420560,205003162,51771056,8619,0,1,15000.0000,True,5,nan,nan,nan,nan,1,3,0
183,2420561,205038458,51771056,4585,0,1,14000.0000,True,5,nan,nan,nan,nan,1,3,0
184,2420562,205100442,51771056,9438,0,1,13000.0000,True,5,nan,nan,nan,nan,1,3,0
185,2420563,205138475,51771056,4664,0,1,35000.0000,True,5,nan,nan,nan,nan,1,3,0
186,2420564,205175334,51771056,3871,0,1,10000.0000,True,5,nan,nan,nan,nan,1,3,0
187,2420565,205205179,51771056,8719,0,1,11000.0000,True,5,nan,nan,nan,nan,1,3,0
188,2420566,205256107,51771056,3966,0,0,8000.0000,True,5,nan,nan,nan,nan,1,3,0
189,2420567,205337398,51771056,8641,0,1,26000.0000,True,5,nan,nan,nan,nan,1,3,0
190,2420568,205386250,51771056,5466,0,1,33000.0000,True,5,nan,nan,nan,nan,1,3,0
191,2420569,205410949,51771056,9098,0,1,10000.0000,True,5,nan,nan,nan,nan,1,3,0
192,2420570,205439790,51771056,5168,0,1,12000.0000,True,5,nan,nan,nan,nan,1,3,0
193,2420571,205460885,51771056,8653,0,1,17000.0000,True,5,nan,nan,nan,nan,1,3,0
194,2420572,205492912,51771056,8471,0,1,9000.0000,True,5,nan,nan,nan,nan,1,3,0
195,2420573,205551122,51771056,9779,0,1,21000.0000,True,5,nan,nan,nan,nan,1,3,0
196,2420574,205678246,51771056,8616,0,1,16000.0000,True,5,nan,nan,nan,nan,1,3,0
197,2420575,205713862,51771056,11531,0,1,14000.0000,True,5,nan,nan,nan,nan,1,3,0
198,2420576,205741642,51771056,4534,0,1,20000.0000,True,5,nan,nan,nan,nan,1,3,0
199,2420577,205769591,51771056,6664,0,1,12000.0000,True,5,nan,nan,nan,nan,1,3,0
200,2420578,205798879,51771056,6339,0,1,14000.0000,True,5,nan,nan,nan,nan,1,3,0
201,2420579,205864580,51771056,8262,0,0,7000.0000,True,5,nan,nan,nan,nan,1,3,0
202,2420580,206264042,51771056,6183,0,1,31000.0000,True,5,nan,nan,nan,nan,1,3,0
203,2420581,206319391,51771056,5676,0,0,5000.0000,True,5,nan,nan,nan,nan,1,3,0
204,2420582,206421546,51771056,6118,0,0,26000.0000,True,5,nan,nan,nan,nan,1,3,0
205,2420583,206505826,51771056,9234,0,1,35000.0000,True,5,nan,nan,nan,nan,1,3,0
206,2420584,206536555,51771056,5674,0,1,27000.0000,True,5,nan,nan,nan,nan,1,3,0
207,2420585,206583283,51771056,11479,0,1,7000.0000,True,5,nan,nan,nan,nan,1,3,0
208,2420586,206658079,51771056,4495,0,1,17000.0000,True,5,nan,nan,nan,nan,1,3,0
209,2420587,206724526,51771056,4416,0,0,15000.0000,True,5,nan,nan,nan,nan,1,3,0
210,2420588,206776505,51771056,6056,0,1,15000.0000,True,5,nan,nan,nan,nan,1,3,0
211,2420589,206861603,51771056,9254,0,0,18000.0000,True,5,nan,nan,nan,nan,1,3,0
212,2420590,206920346,51771056,5856,0,1,23000.0000,True,5,nan,nan,nan,nan,1,3,0
213,2420591,280367093,51771056,10231,0,1,9000.0000,True,6,nan,nan,nan,nan,4,3,1
214,2420592,280367093,51771056,10229,0,0,9000.0000,True,6,nan,nan,nan,nan,4,3,1
215,2420593,280367093,51771056,10228,0,1,9000.0000,True,6,nan,nan,nan,nan,4,3,1
216,2420594,280367093,51771056,10230,0,0,9000.0000,True,6,nan,nan,nan,nan,4,3,1
217,2420595,281539660,51771056,10148,0,1,41500.0000,True,6,nan,nan,nan,nan,4,3,1
218,2420596,281539660,51771056,10150,0,0,41500.0000,True,6,nan,nan,nan,nan,4,3,1
219,2420597,281539660,51771056,10149,0,1,41500.0000,True,6,nan,nan,nan,nan,4,3,1
220,2420598,281539660,51771056,10151,0,1,41500.0000,True,6,nan,nan,nan,nan,4,3,1
221,2420599,282638604,51771056,10071,0,1,26500.0000,True,6,nan,nan,nan,nan,4,3,1
222,2420600,282638604,51771056,10073,0,0,26500.0000,True,6,nan,nan,nan,nan,4,3,1
223,2420601,282638604,51771056,10072,0,1,26500.0000,True,6,nan,nan,nan,nan,4,3,1
224,2420602,282638604,51771056,10070,0,0,26500.0000,True,6,nan,nan,nan,nan,4,3,1
225,2420603,282950400,51771056,6867,0,1,23500.0000,True,6,nan,nan,nan,nan,4,3,1
226,2420604,282950400,51771056,6868,0,0,23500.0000,True,6,nan,nan,nan,nan,4,3,1
227,2420605,282950400,51771056,6865,0,0,23500.0000,True,6,nan,nan,nan,nan,4,3,1
228,2420606,282950400,51771056,6866,0,1,23500.0000,True,6,nan,nan,nan,nan,4,3,1
229,2420607,283146278,51771056,12354,1,-1,nan,False,6,1.0000,0.0000,0.0000,0.0000,4,4,2
230,2420608,286177331,51771056,7949,1,-1,nan,False,5,1.0000,0.0000,0.0000,0.0000,1,5,1
231,2420609,286302450,51771056,9254,0,0,27250.0000,True,5,nan,nan,nan,nan,1,5,1
232,2420610,286370013,51771056,3966,0,1,77000.0000,True,5,nan,nan,nan,nan,1,5,1
233,2420611,286408472,51771056,3599,0,1,10000.0000,True,5,nan,nan,nan,nan,1,5,1
234,2420612,402788047,51771056,834,0,1,21000.0000,False,2,nan,nan,nan,nan,3,5,0
235,2420613,402976713,51771056,6766,0,1,17000.0000,True,6,nan,nan,nan,nan,4,5,2
236,2420614,402976713,51771056,6765,0,1,17000.0000,True,6,nan,nan,nan,nan,4,5,2
237,2420615,402976713,51771056,6768,0,1,17000.0000,True,6,nan,nan,nan,nan,4,5,2
238,2420616,402976713,51771056,6767,0,1,17000.0000,True,6,nan,nan,nan,nan,4,5,2
239,2420617,403174070,51771056,10840,0,1,32250.0000,True,6,nan,nan,nan,nan,4,5,2
240,2420618,403174070,51771056,10842,0,1,32250.0000,True,6,nan,nan,nan,nan,4,5,2
241,2420619,403174070,51771056,10841,0,1,32250.0000,True,6,nan,nan,nan,nan,4,5,2
242,2420620,403174070,51771056,10839,0,0,32250.0000,True,6,nan,nan,nan,nan,4,5,2
243,2420621,403351006,51771056,6878,0,1,28750.0000,True,6,nan,nan,nan,nan,4,5,2
244,2420622,403351006,51771056,6879,0,0,28750.0000,True,6,nan,nan,nan,nan,4,5,2
245,2420623,403351006,51771056,6877,0,1,28750.0000,True,6,nan,nan,nan,nan,4,5,2
246,2420624,403351006,51771056,6880,0,1,28750.0000,True,6,nan,nan,nan,nan,4,5,2
247,2420625,406525042,51771056,13550,1,-1,nan,False,6,1.0000,0.0000,0.0000,0.0000,4,6,3
248,2420626,406574702,51771056,11929,0,1,21750.0000,True,2,nan,nan,nan,nan,11,6,0
249,2420627,407503932,51771056,1359,0,0,17000.0000,True,2,nan,nan,nan,nan,3,6,0
250,2420628,408438229,51771056,1236,0,0,17000.0000,True,2,nan,nan,nan,nan,3,6,0
251,2420629,408471581,51771056,923,0,1,21000.0000,True,2,nan,nan,nan,nan,3,6,0
252,2420630,408507858,51771056,11943,0,0,18000.0000,True,2,nan,nan,nan,nan,3,6,0
253,2420631,408540073,51771056,1147,0,1,17000.0000,True,2,nan,nan,nan,nan,3,6,0
254,2420632,408579825,51771056,239,0,0,14000.0000,True,2,nan,nan,nan,nan,3,6,0
255,2420633,408630185,51771056,488,0,1,22000.0000,True,2,nan,nan,nan,nan,11,6,0
256,2420634,408668004,51771056,12159,0,1,22000.0000,True,2,nan,nan,nan,nan,9,6,0
257,2420635,408708084,51771056,375,0,0,16000.0000,True,2,nan,nan,nan,nan,3,6,0
258,2420636,408783271,51771056,1362,0,0,19000.0000,True,2,nan,nan,nan,nan,10,6,0
259,2420637,408829402,51771056,784,0,0,17000.0000,True,2,nan,nan,nan,nan,3,6,0
260,2420638,408859031,51771056,11962,0,1,19000.0000,True,2,nan,nan,nan,nan,11,6,0
261,2420639,408891381,51771056,589,0,1,17000.0000,True,2,nan,nan,nan,nan,11,6,0
262,2420640,408931594,51771056,296,0,1,19000.0000,True,2,nan,nan,nan,nan,9,6,0
263,2420641,408973082,51771056,904,0,0,17000.0000,True,2,nan,nan,nan,nan,11,6,0
264,2420642,409003765,51771056,11946,0,1,17000.0000,True,2,nan,nan,nan,nan,3,6,0
265,2420643,409029381,51771056,762,0,0,18000.0000,True,2,nan,nan,nan,nan,9,6,0
266,2420644,409059982,51771056,704,0,1,16000.0000,True,2,nan,nan,nan,nan,11,6,0
267,2420645,409209093,51771056,738,0,0,20000.0000,True,2,nan,nan,nan,nan,11,6,0
268,2420646,409243093,51771056,3153,1,-1,nan,False,2,0.0000,1.0000,0.0000,0.0000,3,7,1
269,2420647,409273363,51771056,738,0,0,17000.0000,True,2,nan,nan,nan,nan,11,7,1
270,2420648,409310872,51771056,762,0,1,17000.0000,True,2,nan,nan,nan,nan,9,7,1
271,2420649,409373565,51771056,11967,0,1,18000.0000,True,2,nan,nan,nan,nan,11,7,1
272,2420650,409429992,51771056,549,0,1,17000.0000,True,2,nan,nan,nan,nan,3,7,1
273,2420651,409498881,51771056,1362,0,1,22000.0000,True,2,nan,nan,nan,nan,10,7,1
274,2420652,409514401,51771056,254,0,0,15000.0000,True,2,nan,nan,nan,nan,10,7,1
275,2420653,409538323,51771056,254,0,1,23000.0000,True,2,nan,nan,nan,nan,10,7,1
276,2420654,409582691,51771056,1111,0,1,18000.0000,True,2,nan,nan,nan,nan,3,7,1
277,2420655,409613756,51771056,12191,0,1,16000.0000,True,2,nan,nan,nan,nan,3,7,1
278,2420656,409644408,51771056,1028,0,1,16000.0000,True,2,nan,nan,nan,nan,10,7,1
279,2420657,409683860,51771056,217,0,1,14000.0000,True,2,nan,nan,nan,nan,3,7,1
280,2420658,409860664,51771056,853,0,0,18000.0000,True,2,nan,nan,nan,nan,3,7,1
281,2420659,409930199,51771056,29544,1,-1,nan,False,2,1.0000,0.0000,0.0000,0.0000,3,8,2
282,2420660,409951204,51771056,738,0,1,18000.0000,True,2,nan,nan,nan,nan,11,8,2
283,2420661,409985177,51771056,853,0,0,16000.0000,True,2,nan,nan,nan,nan,3,8,2
284,2420662,410074310,51771056,9489,0,0,19000.0000,True,5,nan,nan,nan,nan,1,8,1
285,2420663,410131604,51771056,4465,0,0,17000.0000,True,5,nan,nan,nan,nan,1,8,1
286,2420664,410182243,51771056,704,0,1,26000.0000,True,2,nan,nan,nan,nan,11,8,2
287,2420665,410347558,51771056,10855,0,0,19000.0000,True,6,nan,nan,nan,nan,4,8,3
288,2420666,410347558,51771056,10856,0,0,19000.0000,True,6,nan,nan,nan,nan,4,8,3
289,2420667,410347558,51771056,10858,0,1,19000.0000,True,6,nan,nan,nan,nan,4,8,3
290,2420668,410347558,51771056,10857,0,1,19000.0000,True,6,nan,nan,nan,nan,4,8,3
291,2420669,410413834,51771056,5178,0,1,32000.0000,True,5,nan,nan,nan,nan,1,8,1
292,2420670,410451017,51771056,407,0,1,27000.0000,True,2,nan,nan,nan,nan,10,8,2
293,2420671,410483442,51771056,8471,0,1,17000.0000,True,5,nan,nan,nan,nan,1,8,1
294,2420672,410511892,51771056,423,0,1,16000.0000,True,2,nan,nan,nan,nan,3,8,2
295,2420673,410541023,51771056,11479,0,1,16000.0000,True,5,nan,nan,nan,nan,1,8,1
296,2420674,410560441,51771056,5626,0,1,8000.0000,True,5,nan,nan,nan,nan,1,8,1

In [47]:
vitrine[(vitrine.user_id == 51771056)]

          id   timestamp   user_id  content_id  content_type_id  \
50   2420428           0  51771056       10733                0
51   2420429           0  51771056       10732                0
52   2420430           0  51771056       10731                0
53   2420431      147940  51771056        2820                0
54   2420432      147940  51771056        2819                0
55   2420433      147940  51771056        2818                0
56   2420434      301126  51771056        2623                0
57   2420435      301126  51771056        2624                0
58   2420436      301126  51771056        2625                0
59   2420437      468350  51771056        2940                0
60   2420438      468350  51771056        2942                0
61   2420439      468350  51771056        2941                0
62   2420440      782950  51771056        3228                0
63   2420441      782950  51771056        3229                0
64   2420442      782950  51771056        3230                0
65   2420443    29098393  51771056       10857                0
66   2420444    29098393  51771056       10858                0
67   2420445    29098393  51771056       10855                0
68   2420446    29098393  51771056       10856                0
69   2420447    75088427  51771056       10834                0
70   2420448    75088427  51771056       10833                0
71   2420449    75088427  51771056       10831                0
72   2420450    75088427  51771056       10832                0
73   2420451    75377509  51771056       10282                0
74   2420452    75377509  51771056       10281                0
75   2420453    75377509  51771056       10280                0
76   2420454    75377509  51771056       10283                0
77   2420455    76007301  51771056       10272                0
78   2420456    76007301  51771056       10273                0
79   2420457    76007301  51771056       10274                0
80   2420458    76007301  51771056       10275                0
81   2420459    76848953  51771056        6803                0
82   2420460    76848953  51771056        6801                0
83   2420461    76848953  51771056        6804                0
84   2420462    76848953  51771056        6802                0
85   2420463    77565937  51771056        7148                0
86   2420464    77565937  51771056        7147                0
87   2420465    77565937  51771056        7145                0
88   2420466    77565937  51771056        7149                0
89   2420467    77565937  51771056        7146                0
90   2420468    78463792  51771056        6962                0
91   2420469    78463792  51771056        6963                0
92   2420470    78463792  51771056        6964                0
93   2420471    78463792  51771056        6961                0
94   2420472    78463792  51771056        6965                0
95   2420473    79487416  51771056        7390                0
96   2420474    79487416  51771056        7388                0
97   2420475    79487416  51771056        7389                0
98   2420476    79487416  51771056        7386                0
99   2420477    79487416  51771056        7387                0
100  2420478    85453640  51771056       22711                1
101  2420479    85527879  51771056        7981                0
102  2420480    85593707  51771056           6                0
103  2420481    85664366  51771056       10415                0
104  2420482    85710815  51771056         199                0
105  2420483    85752474  51771056        1103                0
106  2420484    85812854  51771056         981                0
107  2420485    85861409  51771056         279                0
108  2420486    85904659  51771056        1310                0
109  2420487    85944038  51771056         242                0
110  2420488    86035097  51771056       10733                0
111  2420489    86035097  51771056       10732                0
112  2420490    86035097  51771056       10731                0
113  2420491    86132187  51771056        2819                0
114  2420492    86132187  51771056        2818                0
115  2420493    86132187  51771056        2820                0
116  2420494   149614692  51771056        1941                0
117  2420495   149614692  51771056        1942                0
118  2420496   149614692  51771056        1940                0
119  2420497   149810235  51771056        2044                0
120  2420498   149810235  51771056        2043                0
121  2420499   149810235  51771056        2042                0
122  2420500   150020296  51771056        2119                0
123  2420501   150020296  51771056        2118                0
124  2420502   150020296  51771056        2117                0
125  2420503   150184468  51771056        2258                0
126  2420504   150184468  51771056        2257                0
127  2420505   150184468  51771056        2259                0
128  2420506   150435720  51771056        1876                0
129  2420507   150435720  51771056        1874                0
130  2420508   150435720  51771056        1875                0
131  2420509   150817666  51771056       23815                1
132  2420510   153633437  51771056        7185                0
133  2420511   153633437  51771056        7186                0
134  2420512   153633437  51771056        7184                0
135  2420513   154513160  51771056        7712                0
136  2420514   154513160  51771056        7709                0
137  2420515   154513160  51771056        7710                0
138  2420516   154513160  51771056        7711                0
139  2420517   154513160  51771056        7713                0
140  2420518   155070820  51771056        7823                0
141  2420519   155070820  51771056        7821                0
142  2420520   155070820  51771056        7822                0
143  2420521   155070820  51771056        7820                0
144  2420522   202159396  51771056        1980                0
145  2420523   202159396  51771056        1979                0
146  2420524   202159396  51771056        1981                0
147  2420525   202278675  51771056        1605                0
148  2420526   202278675  51771056        1606                0
149  2420527   202278675  51771056        1604                0
150  2420528   202414052  51771056        1879                0
151  2420529   202414052  51771056        1877                0
152  2420530   202414052  51771056        1878                0
153  2420531   202584924  51771056        2484                0
154  2420532   202584924  51771056        2482                0
155  2420533   202584924  51771056        2483                0
156  2420534   202721519  51771056        2087                0
157  2420535   202721519  51771056        2088                0
158  2420536   202721519  51771056        2089                0
159  2420537   203030959  51771056       10081                0
160  2420538   203030959  51771056       10079                0
161  2420539   203030959  51771056       10080                0
162  2420540   203030959  51771056       10078                0
163  2420541   203378000  51771056        6519                0
164  2420542   203378000  51771056        6520                0
165  2420543   203378000  51771056        6517                0
166  2420544   203378000  51771056        6518                0
167  2420545   203648168  51771056       11174                0
168  2420546   203648168  51771056       11172                0
169  2420547   203648168  51771056       11173                0
170  2420548   203648168  51771056       11171                0
171  2420549   203839649  51771056       10069                0
172  2420550   203839649  51771056       10067                0
173  2420551   203839649  51771056       10066                0
174  2420552   203839649  51771056       10068                0
175  2420553   204130046  51771056       32570                1
176  2420554   204767306  51771056        9495                0
177  2420555   204862856  51771056        5178                0
178  2420556   204896107  51771056        6476                0
179  2420557   204920867  51771056        5593                0
180  2420558   204950525  51771056        9489                0
181  2420559   204973982  51771056        4260                0
182  2420560   205003162  51771056        8619                0
183  2420561   205038458  51771056        4585                0
184  2420562   205100442  51771056        9438                0
185  2420563   205138475  51771056        4664                0
186  2420564   205175334  51771056        3871                0
187  2420565   205205179  51771056        8719                0
188  2420566   205256107  51771056        3966                0
189  2420567   205337398  51771056        8641                0
190  2420568   205386250  51771056        5466                0
191  2420569   205410949  51771056        9098                0
192  2420570   205439790  51771056        5168                0
193  2420571   205460885  51771056        8653                0
194  2420572   205492912  51771056        8471                0
195  2420573   205551122  51771056        9779                0
196  2420574   205678246  51771056        8616                0
197  2420575   205713862  51771056       11531                0
198  2420576   205741642  51771056        4534                0
199  2420577   205769591  51771056        6664                0
200  2420578   205798879  51771056        6339                0
201  2420579   205864580  51771056        8262                0
202  2420580   206264042  51771056        6183                0
203  2420581   206319391  51771056        5676                0
204  2420582   206421546  51771056        6118                0
205  2420583   206505826  51771056        9234                0
206  2420584   206536555  51771056        5674                0
207  2420585   206583283  51771056       11479                0
208  2420586   206658079  51771056        4495                0
209  2420587   206724526  51771056        4416                0
210  2420588   206776505  51771056        6056                0
211  2420589   206861603  51771056        9254                0
212  2420590   206920346  51771056        5856                0
213  2420591   280367093  51771056       10231                0
214  2420592   280367093  51771056       10229                0
215  2420593   280367093  51771056       10228                0
216  2420594   280367093  51771056       10230                0
217  2420595   281539660  51771056       10148                0
218  2420596   281539660  51771056       10150                0
219  2420597   281539660  51771056       10149                0
220  2420598   281539660  51771056       10151                0
221  2420599   282638604  51771056       10071                0
222  2420600   282638604  51771056       10073                0
223  2420601   282638604  51771056       10072                0
224  2420602   282638604  51771056       10070                0
225  2420603   282950400  51771056        6867                0
226  2420604   282950400  51771056        6868                0
227  2420605   282950400  51771056        6865                0
228  2420606   282950400  51771056        6866                0
229  2420607   283146278  51771056       12354                1
230  2420608   286177331  51771056        7949                1
231  2420609   286302450  51771056        9254                0
232  2420610   286370013  51771056        3966                0
233  2420611   286408472  51771056        3599                0
234  2420612   402788047  51771056         834                0
235  2420613   402976713  51771056        6766                0
236  2420614   402976713  51771056        6765                0
237  2420615   402976713  51771056        6768                0
238  2420616   402976713  51771056        6767                0
239  2420617   403174070  51771056       10840                0
240  2420618   403174070  51771056       10842                0
241  2420619   403174070  51771056       10841                0
242  2420620   403174070  51771056       10839                0
243  2420621   403351006  51771056        6878                0
244  2420622   403351006  51771056        6879                0
245  2420623   403351006  51771056        6877                0
246  2420624   403351006  51771056        6880                0
247  2420625   406525042  51771056       13550                1
248  2420626   406574702  51771056       11929                0
249  2420627   407503932  51771056        1359                0
250  2420628   408438229  51771056        1236                0
251  2420629   408471581  51771056         923                0
252  2420630   408507858  51771056       11943                0
253  2420631   408540073  51771056        1147                0
254  2420632   408579825  51771056         239                0
255  2420633   408630185  51771056         488                0
256  2420634   408668004  51771056       12159                0
257  2420635   408708084  51771056         375                0
258  2420636   408783271  51771056        1362                0
259  2420637   408829402  51771056         784                0
260  2420638   408859031  51771056       11962                0
261  2420639   408891381  51771056         589                0
262  2420640   408931594  51771056         296                0
263  2420641   408973082  51771056         904                0
264  2420642   409003765  51771056       11946                0
265  2420643   409029381  51771056         762                0
266  2420644   409059982  51771056         704                0
267  2420645   409209093  51771056         738                0
268  2420646   409243093  51771056        3153                1
269  2420647   409273363  51771056         738                0
270  2420648   409310872  51771056         762                0
271  2420649   409373565  51771056       11967                0
272  2420650   409429992  51771056         549                0
273  2420651   409498881  51771056        1362                0
274  2420652   409514401  51771056         254                0
275  2420653   409538323  51771056         254                0
276  2420654   409582691  51771056        1111                0
277  2420655   409613756  51771056       12191                0
278  2420656   409644408  51771056        1028                0
279  2420657   409683860  51771056         217                0
280  2420658   409860664  51771056         853                0
281  2420659   409930199  51771056       29544                1
282  2420660   409951204  51771056         738                0
283  2420661   409985177  51771056         853                0
284  2420662   410074310  51771056        9489                0
285  2420663   410131604  51771056        4465                0
286  2420664   410182243  51771056         704                0
287  2420665   410347558  51771056       10855                0
288  2420666   410347558  51771056       10856                0
289  2420667   410347558  51771056       10858                0
290  2420668   410347558  51771056       10857                0
291  2420669   410413834  51771056        5178                0
292  2420670   410451017  51771056         407                0
293  2420671   410483442  51771056        8471                0
294  2420672   410511892  51771056         423                0
295  2420673   410541023  51771056       11479                0
296  2420674   410560441  51771056        5626                0
297  2420675   410592045  51771056        5593                0
298  2420676   410626652  51771056        7981                0
299  2420677   410734901  51771056        2257                0
300  2420678   410734901  51771056        2258                0
301  2420679   410734901  51771056        2259                0
302  2420680   410802231  51771056         549                0
303  2420681   410843931  51771056        8516                0
304  2420682   410869405  51771056        4416                0
305  2420683   410905753  51771056       12081                0
306  2420684   411746459  51771056       13447                0
307  2420685   413120860  51771056        7492                0
308  2420686   413120860  51771056        7493                0
309  2420687   413120860  51771056        7489                0
310  2420688   413120860  51771056        7491                0
311  2420689   413120860  51771056        7490                0
312  2420690   413251410  51771056       11637                0
313  2420691   413251410  51771056       11638                0
314  2420692   413251410  51771056       11639                0
315  2420693   413511540  51771056        8059                0
316  2420694   413511540  51771056        8062                0
317  2420695   413511540  51771056        8061                0
318  2420696   413511540  51771056        8063                0
319  2420697   413511540  51771056        8060                0
320  2420698   413707888  51771056       20307                1
321  2420699   418458385  51771056        7008                0
322  2420700   418458385  51771056        7006                0
323  2420701   418458385  51771056        7007                0
324  2420702   418458385  51771056        7009                0
325  2420703   418458385  51771056        7010                0
326  2420704   418489418  51771056        1236                0
327  2420705   418688177  51771056       11579                0
328  2420706   418688177  51771056       11575                0
329  2420707   418688177  51771056       11578                0
330  2420708   418688177  51771056       11576                0
331  2420709   418688177  51771056       11577                0
332  2420710   418722756  51771056        1002                0
333  2420711   418756653  51771056       12232                0
334  2420712   418803760  51771056        1362                0
335  2420713   418919118  51771056       10151                0
336  2420714   418919118  51771056       10150                0
337  2420715   418919118  51771056       10148                0
338  2420716   418919118  51771056       10149                0
339  2420717   418982359  51771056        6670                0
340  2420718   419056405  51771056         239                0
341  2420719   419096277  51771056        4585                0
342  2420720   419201743  51771056        4908                0
343  2420721   419345365  51771056        5268                0
344  2420722   419413311  51771056        4100                0
345  2420723   419437353  51771056         279                0
346  2420724   419510486  51771056       10620                0
347  2420725   419574144  51771056       10543                0
348  2420726   419636366  51771056       12801                0
349  2420727   419677446  51771056        7908                0
350  2420728   419773997  51771056          62                0
351  2420729   419872589  51771056         165                0
352  2420730   420077879  51771056       12227                0
353  2420731   420300512  51771056         915                0
354  2420732   420496856  51771056        1114                0
355  2420733   420669085  51771056        1298                0
356  2420734   420771155  51771056       12016                0
357  2420735   420878480  51771056        1194                0
358  2420736   420936570  51771056         254                0
359  2420737   420956017  51771056        1362                0
360  2420738   420978214  51771056        1036                0