In [1]:
import pandas as pd
from typing import List, Dict, Tuple

In [2]:
%%time
vitrine = pd.read_csv('../data/vitrine.csv')

CPU times: user 1min 5s, sys: 33.2 s, total: 1min 38s
Wall time: 1min 57s

In [3]:
vitrine.head()

,id,timestamp,user_id,content_id,answered_correctly,prior_question_elapsed_time,prior_question_had_explanation,question_id,part,kmean_cluster
0,0,0,115,5692,1,NaN,NaN,5692,5,1
1,1,56943,115,5716,1,37000.0,False,5716,5,1
2,2,118363,115,128,1,55000.0,False,128,1,0
3,3,131167,115,7860,1,19000.0,False,7860,1,0
4,4,137965,115,7922,1,11000.0,False,7922,1,0

In [4]:
vitrine.shape

(99271300, 10)

In [5]:
vitrine[vitrine.user_id == 124]

,id,timestamp,user_id,content_id,answered_correctly,prior_question_elapsed_time,prior_question_had_explanation,question_id,part,kmean_cluster
46,46,0,124,7900,1,NaN,NaN,7900,1,0
47,47,32683,124,7876,0,26000.0,False,7876,1,13
48,48,62000,124,175,1,29000.0,False,175,1,13
49,49,83632,124,1278,0,26000.0,False,1278,2,11
50,50,189483,124,2064,0,18000.0,False,2064,3,9
51,51,189483,124,2063,0,18000.0,False,2063,3,9
52,52,189483,124,2065,1,18000.0,False,2065,3,9
53,53,258793,124,3364,0,33333.0,False,3364,4,6
54,54,258793,124,3365,0,33333.0,False,3365,4,6
55,55,258793,124,3363,0,33333.0,False,3363,4,6
56,56,330528,124,2948,0,21000.0,False,2948,4,6
57,57,330528,124,2947,1,21000.0,False,2947,4,6
58,58,330528,124,2946,0,21000.0,False,2946,4,6
59,59,382790,124,2595,1,21666.0,False,2595,4,6
60,60,382790,124,2593,0,21666.0,False,2593,4,6
61,61,382790,124,2594,0,21666.0,False,2594,4,6
62,62,419266,124,4492,0,15000.0,False,4492,5,1
63,63,445527,124,4120,0,32000.0,False,4120,5,1
64,64,475421,124,4696,0,23000.0,False,4696,5,1
65,65,492328,124,6116,1,27000.0,False,6116,5,1
66,66,513206,124,6173,0,14000.0,False,6173,5,1
67,67,523644,124,6370,0,17000.0,False,6370,5,1
68,68,554504,124,6909,1,7000.0,False,6909,6,4
69,69,554504,124,6910,0,7000.0,False,6910,6,4
70,70,554504,124,6908,0,7000.0,False,6908,6,4
71,71,554504,124,6911,0,7000.0,False,6911,6,4
72,72,571323,124,7218,0,6500.0,False,7218,7,5
73,73,571323,124,7216,0,6500.0,False,7216,7,5
74,74,571323,124,7217,0,6500.0,False,7217,7,5
75,75,571323,124,7219,0,6500.0,False,7219,7,5

In [31]:
vitrine['prior_question_had_explanation'].fillna(False, inplace = True)

In [32]:
vitrine[vitrine.user_id == 124]

,id,timestamp,user_id,content_id,answered_correctly,prior_question_elapsed_time,prior_question_had_explanation,question_id,part,kmean_cluster,lag_user,lag_user_part,lag_user_clu
46,46,0,124,7900,1,NaN,False,7900,1,0,NaN,NaN,NaN
47,47,32683,124,7876,0,26000.0,False,7876,1,13,1.0,1.0,NaN
48,48,62000,124,175,1,29000.0,False,175,1,13,0.0,0.0,0.0
49,49,83632,124,1278,0,26000.0,False,1278,2,11,1.0,NaN,NaN
50,50,189483,124,2064,0,18000.0,False,2064,3,9,0.0,NaN,NaN
51,51,189483,124,2063,0,18000.0,False,2063,3,9,0.0,0.0,0.0
52,52,189483,124,2065,1,18000.0,False,2065,3,9,0.0,0.0,0.0
53,53,258793,124,3364,0,33333.0,False,3364,4,6,1.0,NaN,NaN
54,54,258793,124,3365,0,33333.0,False,3365,4,6,0.0,0.0,0.0
55,55,258793,124,3363,0,33333.0,False,3363,4,6,0.0,0.0,0.0
56,56,330528,124,2948,0,21000.0,False,2948,4,6,0.0,0.0,0.0
57,57,330528,124,2947,1,21000.0,False,2947,4,6,0.0,0.0,0.0
58,58,330528,124,2946,0,21000.0,False,2946,4,6,1.0,1.0,1.0
59,59,382790,124,2595,1,21666.0,False,2595,4,6,0.0,0.0,0.0
60,60,382790,124,2593,0,21666.0,False,2593,4,6,1.0,1.0,1.0
61,61,382790,124,2594,0,21666.0,False,2594,4,6,0.0,0.0,0.0
62,62,419266,124,4492,0,15000.0,False,4492,5,1,0.0,NaN,NaN
63,63,445527,124,4120,0,32000.0,False,4120,5,1,0.0,0.0,0.0
64,64,475421,124,4696,0,23000.0,False,4696,5,1,0.0,0.0,0.0
65,65,492328,124,6116,1,27000.0,False,6116,5,1,0.0,0.0,0.0
66,66,513206,124,6173,0,14000.0,False,6173,5,1,1.0,1.0,1.0
67,67,523644,124,6370,0,17000.0,False,6370,5,1,0.0,0.0,0.0
68,68,554504,124,6909,1,7000.0,False,6909,6,4,0.0,NaN,NaN
69,69,554504,124,6910,0,7000.0,False,6910,6,4,1.0,1.0,1.0
70,70,554504,124,6908,0,7000.0,False,6908,6,4,0.0,0.0,0.0
71,71,554504,124,6911,0,7000.0,False,6911,6,4,0.0,0.0,0.0
72,72,571323,124,7218,0,6500.0,False,7218,7,5,0.0,NaN,NaN
73,73,571323,124,7216,0,6500.0,False,7216,7,5,0.0,0.0,0.0
74,74,571323,124,7217,0,6500.0,False,7217,7,5,0.0,0.0,0.0
75,75,571323,124,7219,0,6500.0,False,7219,7,5,0.0,0.0,0.0

In [6]:
vitrine['lag_user'] = vitrine.groupby('user_id')['answered_correctly'].shift()
vitrine['lag_user_part'] = vitrine.groupby(['user_id', 'part'])['answered_correctly'].shift()
vitrine['lag_user_clu'] = vitrine.groupby(['user_id', 'kmean_cluster'])['answered_correctly'].shift()

In [49]:
def ema_window(df_sub: pd.DataFrame, subfield: str = 'lag'):
    N = len(df_sub)
    alpha = 2 / (N + 1)
    df_sub['exp'] = df_sub[subfield].ewm(alpha=alpha).mean()
    return df_sub





def compute_cumulative_features(
    df: pd.DataFrame, 
    agg_fields: List[str],
    target: str = 'answered_correctly',
    prename: str = 'user',
    fl_lag: bool = True
):
    if fl_lag:
        df['lag'] = df.groupby(agg_fields)[target].shift()
    else:
        df['lag'] = df[target]
    
    cum = df.groupby(agg_fields)['lag'].agg(['cumsum', 'cumcount'])
    if not fl_lag:
        cum['cumcount'] += 1
    cum['mean'] = cum['cumsum'] / cum['cumcount']
    cum.columns = [
        f'{prename}_sum_{target}', 
        f'{prename}_count_{target}', 
        f'{prename}_mean_{target}', 
    ]
    
    df = df.groupby(agg_fields).apply(ema_window)
    cum[f'{prename}_ema_{target}'] = df['exp']
    df = df.drop(['lag', 'exp'], axis = 1)
    return cum

def cumcount_unique(df):
    series = df['lag']
    l = list(series)

    already_l = []
    count_unique = 0
    res = []

    for el in l:
        if not el in already_l and el == el:
            count_unique += 1
            already_l.append(el)
            res.append(count_unique)

        elif not el in already_l:
            already_l.append(el)
            res.append(count_unique)

        else:
            res.append(count_unique)
    return pd.DataFrame(data = {'col': res})

def compute_cumulative_count_features(
    df: pd.DataFrame, 
    agg_fields: List[str],
    target: str = 'answered_correctly',
    prename: str = 'user',
    fl_lag: bool = True
):
    if fl_lag:
        df['lag'] = df.groupby(agg_fields)[target].shift()
    else:
        df['lag'] = df[target]
    
    cum = df.groupby(agg_fields).apply(cumcount_unique).reset_index(drop = True)
    cum.index = df.index
    cum.columns = [f'{prename}_ucount_{target}']
    
    return cum

In [50]:
user_correctly = compute_cumulative_features(
    vitrine[vitrine.user_id == 124], 
    ['user_id'],
    target = 'answered_correctly',
    prename = 'user'
)

user_he_correctly = compute_cumulative_features(
    vitrine[vitrine.user_id == 124], 
    ['user_id', 'prior_question_had_explanation'],
    target = 'answered_correctly',
    prename = 'user_he'
)

user_time = compute_cumulative_features(
    vitrine[vitrine.user_id == 124], 
    ['user_id'],
    target = 'prior_question_elapsed_time',
    prename = 'user',
    fl_lag = False
)

user_he_time = compute_cumulative_features(
    vitrine[vitrine.user_id == 124], 
    ['user_id', 'prior_question_had_explanation'],
    target = 'prior_question_elapsed_time',
    prename = 'user_he',
    fl_lag = False
)

<ipython-input-49-7c115ab522bc>:19: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['lag'] = df.groupby(agg_fields)[target].shift()
<ipython-input-49-7c115ab522bc>:21: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['lag'] = df[target]

In [51]:
user_content_1 = compute_cumulative_count_features(
    vitrine[vitrine.user_id == 124],
    agg_fields = ['user_id'],
    prename = 'user',
    target = 'part'
)

user_content_2 = compute_cumulative_count_features(
    vitrine[vitrine.user_id == 124],
    agg_fields = ['user_id'],
    prename = 'user',
    target = 'kmean_cluster'
)

user_content_3 = compute_cumulative_count_features(
    vitrine[vitrine.user_id == 124],
    agg_fields = ['user_id', 'prior_question_had_explanation'],
    prename = 'user',
    target = 'part'
)

user_content_4 = compute_cumulative_count_features(
    vitrine[vitrine.user_id == 124],
    agg_fields = ['user_id', 'prior_question_had_explanation'],
    prename = 'user',
    target = 'kmean_cluster'
)

<ipython-input-49-7c115ab522bc>:68: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['lag'] = df.groupby(agg_fields)[target].shift()

In [53]:
vitrine[vitrine.user_id == 124]

,id,timestamp,user_id,content_id,answered_correctly,prior_question_elapsed_time,prior_question_had_explanation,question_id,part,kmean_cluster,lag_user,lag_user_part,lag_user_clu
46,46,0,124,7900,1,NaN,False,7900,1,0,NaN,NaN,NaN
47,47,32683,124,7876,0,26000.0,False,7876,1,13,1.0,1.0,NaN
48,48,62000,124,175,1,29000.0,False,175,1,13,0.0,0.0,0.0
49,49,83632,124,1278,0,26000.0,False,1278,2,11,1.0,NaN,NaN
50,50,189483,124,2064,0,18000.0,False,2064,3,9,0.0,NaN,NaN
51,51,189483,124,2063,0,18000.0,False,2063,3,9,0.0,0.0,0.0
52,52,189483,124,2065,1,18000.0,False,2065,3,9,0.0,0.0,0.0
53,53,258793,124,3364,0,33333.0,False,3364,4,6,1.0,NaN,NaN
54,54,258793,124,3365,0,33333.0,False,3365,4,6,0.0,0.0,0.0
55,55,258793,124,3363,0,33333.0,False,3363,4,6,0.0,0.0,0.0
56,56,330528,124,2948,0,21000.0,False,2948,4,6,0.0,0.0,0.0
57,57,330528,124,2947,1,21000.0,False,2947,4,6,0.0,0.0,0.0
58,58,330528,124,2946,0,21000.0,False,2946,4,6,1.0,1.0,1.0
59,59,382790,124,2595,1,21666.0,False,2595,4,6,0.0,0.0,0.0
60,60,382790,124,2593,0,21666.0,False,2593,4,6,1.0,1.0,1.0
61,61,382790,124,2594,0,21666.0,False,2594,4,6,0.0,0.0,0.0
62,62,419266,124,4492,0,15000.0,False,4492,5,1,0.0,NaN,NaN
63,63,445527,124,4120,0,32000.0,False,4120,5,1,0.0,0.0,0.0
64,64,475421,124,4696,0,23000.0,False,4696,5,1,0.0,0.0,0.0
65,65,492328,124,6116,1,27000.0,False,6116,5,1,0.0,0.0,0.0
66,66,513206,124,6173,0,14000.0,False,6173,5,1,1.0,1.0,1.0
67,67,523644,124,6370,0,17000.0,False,6370,5,1,0.0,0.0,0.0
68,68,554504,124,6909,1,7000.0,False,6909,6,4,0.0,NaN,NaN
69,69,554504,124,6910,0,7000.0,False,6910,6,4,1.0,1.0,1.0
70,70,554504,124,6908,0,7000.0,False,6908,6,4,0.0,0.0,0.0
71,71,554504,124,6911,0,7000.0,False,6911,6,4,0.0,0.0,0.0
72,72,571323,124,7218,0,6500.0,False,7218,7,5,0.0,NaN,NaN
73,73,571323,124,7216,0,6500.0,False,7216,7,5,0.0,0.0,0.0
74,74,571323,124,7217,0,6500.0,False,7217,7,5,0.0,0.0,0.0
75,75,571323,124,7219,0,6500.0,False,7219,7,5,0.0,0.0,0.0

In [54]:
pd.concat([vitrine[vitrine.user_id == 124], user_correctly, user_he_correctly,
           user_time, user_he_time, user_content_1, user_content_2, user_content_3, user_content_4
          ], axis = 1)

,id,timestamp,user_id,content_id,answered_correctly,prior_question_elapsed_time,prior_question_had_explanation,question_id,part,kmean_cluster,...,user_mean_prior_question_elapsed_time,user_ema_prior_question_elapsed_time,user_he_sum_prior_question_elapsed_time,user_he_count_prior_question_elapsed_time,user_he_mean_prior_question_elapsed_time,user_he_ema_prior_question_elapsed_time,user_ucount_part,user_ucount_kmean_cluster,user_ucount_part,user_ucount_kmean_cluster
46,46,0,124,7900,1,NaN,False,7900,1,0,...,NaN,NaN,NaN,1,NaN,NaN,0,0,0,0
47,47,32683,124,7876,0,26000.0,False,7876,1,13,...,13000.000000,26000.000000,26000.0,2,13000.000000,26000.000000,1,1,1,1
48,48,62000,124,175,1,29000.0,False,175,1,13,...,18333.333333,27550.000000,55000.0,3,18333.333333,27550.000000,1,2,1,2
49,49,83632,124,1278,0,26000.0,False,1278,2,11,...,20250.000000,26998.519067,81000.0,4,20250.000000,26998.519067,1,2,1,2
50,50,189483,124,2064,0,18000.0,False,2064,3,9,...,19800.000000,24519.099149,99000.0,5,19800.000000,24519.099149,2,3,2,3
51,51,189483,124,2063,0,18000.0,False,2063,3,9,...,19500.000000,23035.846259,117000.0,6,19500.000000,23035.846259,3,4,3,4
52,52,189483,124,2065,1,18000.0,False,2065,3,9,...,19285.714286,22050.662265,135000.0,7,19285.714286,22050.662265,3,4,3,4
53,53,258793,124,3364,0,33333.0,False,3364,4,6,...,21041.625000,24002.016078,168333.0,8,21041.625000,24002.016078,3,4,3,4
54,54,258793,124,3365,0,33333.0,False,3365,4,6,...,22407.333333,25457.984734,201666.0,9,22407.333333,25457.984734,4,5,4,5
55,55,258793,124,3363,0,33333.0,False,3363,4,6,...,23499.900000,26583.741004,234999.0,10,23499.900000,26583.741004,4,5,4,5
56,56,330528,124,2948,0,21000.0,False,2948,4,6,...,23272.636364,25843.584519,255999.0,11,23272.636364,25843.584519,4,5,4,5
57,57,330528,124,2947,1,21000.0,False,2947,4,6,...,23083.250000,25242.441460,276999.0,12,23083.250000,25242.441460,4,5,4,5
58,58,330528,124,2946,0,21000.0,False,2946,4,6,...,22923.000000,24745.520992,297999.0,13,22923.000000,24745.520992,4,5,4,5
59,59,382790,124,2595,1,21666.0,False,2595,4,6,...,22833.214286,24402.844125,319665.0,14,22833.214286,24402.844125,4,5,4,5
60,60,382790,124,2593,0,21666.0,False,2593,4,6,...,22755.400000,24111.903342,341331.0,15,22755.400000,24111.903342,4,5,4,5
61,61,382790,124,2594,0,21666.0,False,2594,4,6,...,22687.312500,23862.320899,362997.0,16,22687.312500,23862.320899,4,5,4,5
62,62,419266,124,4492,0,15000.0,False,4492,5,1,...,22235.117647,22990.707912,377997.0,17,22235.117647,22990.707912,4,5,4,5
63,63,445527,124,4120,0,32000.0,False,4120,5,1,...,22777.611111,23847.777244,409997.0,18,22777.611111,23847.777244,5,6,5,6
64,64,475421,124,4696,0,23000.0,False,4696,5,1,...,22789.315789,23769.522560,432997.0,19,22789.315789,23769.522560,5,6,5,6
65,65,492328,124,6116,1,27000.0,False,6116,5,1,...,22999.850000,24059.651523,459997.0,20,22999.850000,24059.651523,5,6,5,6
66,66,513206,124,6173,0,14000.0,False,6173,5,1,...,22571.285714,23178.482996,473997.0,21,22571.285714,23178.482996,5,6,5,6
67,67,523644,124,6370,0,17000.0,False,6370,5,1,...,22318.045455,22649.491049,490997.0,22,22318.045455,22649.491049,5,6,5,6
68,68,554504,124,6909,1,7000.0,False,6909,6,4,...,21652.043478,21337.296671,497997.0,23,21652.043478,21337.296671,5,6,5,6
69,69,554504,124,6910,0,7000.0,False,6910,6,4,...,21041.541667,20157.929073,504997.0,24,21041.541667,20157.929073,6,7,6,7
70,70,554504,124,6908,0,7000.0,False,6908,6,4,...,20479.880000,19094.443718,511997.0,25,20479.880000,19094.443718,6,7,6,7
71,71,554504,124,6911,0,7000.0,False,6911,6,4,...,19961.423077,18132.600488,518997.0,26,19961.423077,18132.600488,6,7,6,7
72,72,571323,124,7218,0,6500.0,False,7218,7,5,...,19462.851852,17221.168605,525497.0,27,19462.851852,17221.168605,6,7,6,7
73,73,571323,124,7216,0,6500.0,False,7216,7,5,...,18999.892857,16392.612191,531997.0,28,18999.892857,16392.612191,7,8,7,8
74,74,571323,124,7217,0,6500.0,False,7217,7,5,...,18568.862069,15637.725511,538497.0,29,18568.862069,15637.725511,7,8,7,8
75,75,571323,124,7219,0,6500.0,False,7219,7,5,...,18166.566667,14948.569345,544997.0,30,18166.566667,14948.569345,7,8,7,8

In [ ]:
cum_user = vitrine.groupby('user_id')['lag'].agg(['cumsum', 'cumcount'])
cum_user_part = vitrine.groupby(['user_id', 'part'])['lag_user_part'].agg(['cumsum', 'cumcount'])

In [12]:
cum

          cumsum  cumcount
0            NaN         0
1            1.0         1
2            2.0         2
3            3.0         3
4            4.0         4
...          ...       ...
99271295    11.0        22
99271296    12.0        23
99271297    13.0        24
99271298    14.0        25
99271299    14.0        26

[99271300 rows x 2 columns]

In [13]:
vitrine = pd.concat([vitrine, cum], axis = 1)

In [34]:
def divide_two_cols(df_sub):
    df_sub['divs'] = df_sub['cumsum'] / df_sub['cumcount']
    return df_sub

vitrine[vitrine.user_id == 124].groupby('user_id').apply(divide_two_cols)

,id,timestamp,user_id,content_id,answered_correctly,prior_question_elapsed_time,prior_question_had_explanation,question_id,part,kmean_cluster,lag,cumsum,cumcount,divs
46,46,0,124,7900,1,NaN,NaN,7900,1,0,NaN,NaN,0,NaN
47,47,32683,124,7876,0,26000.0,False,7876,1,13,1.0,1.0,1,1.000000
48,48,62000,124,175,1,29000.0,False,175,1,13,0.0,1.0,2,0.500000
49,49,83632,124,1278,0,26000.0,False,1278,2,11,1.0,2.0,3,0.666667
50,50,189483,124,2064,0,18000.0,False,2064,3,9,0.0,2.0,4,0.500000
51,51,189483,124,2063,0,18000.0,False,2063,3,9,0.0,2.0,5,0.400000
52,52,189483,124,2065,1,18000.0,False,2065,3,9,0.0,2.0,6,0.333333
53,53,258793,124,3364,0,33333.0,False,3364,4,6,1.0,3.0,7,0.428571
54,54,258793,124,3365,0,33333.0,False,3365,4,6,0.0,3.0,8,0.375000
55,55,258793,124,3363,0,33333.0,False,3363,4,6,0.0,3.0,9,0.333333
56,56,330528,124,2948,0,21000.0,False,2948,4,6,0.0,3.0,10,0.300000
57,57,330528,124,2947,1,21000.0,False,2947,4,6,0.0,3.0,11,0.272727
58,58,330528,124,2946,0,21000.0,False,2946,4,6,1.0,4.0,12,0.333333
59,59,382790,124,2595,1,21666.0,False,2595,4,6,0.0,4.0,13,0.307692
60,60,382790,124,2593,0,21666.0,False,2593,4,6,1.0,5.0,14,0.357143
61,61,382790,124,2594,0,21666.0,False,2594,4,6,0.0,5.0,15,0.333333
62,62,419266,124,4492,0,15000.0,False,4492,5,1,0.0,5.0,16,0.312500
63,63,445527,124,4120,0,32000.0,False,4120,5,1,0.0,5.0,17,0.294118
64,64,475421,124,4696,0,23000.0,False,4696,5,1,0.0,5.0,18,0.277778
65,65,492328,124,6116,1,27000.0,False,6116,5,1,0.0,5.0,19,0.263158
66,66,513206,124,6173,0,14000.0,False,6173,5,1,1.0,6.0,20,0.300000
67,67,523644,124,6370,0,17000.0,False,6370,5,1,0.0,6.0,21,0.285714
68,68,554504,124,6909,1,7000.0,False,6909,6,4,0.0,6.0,22,0.272727
69,69,554504,124,6910,0,7000.0,False,6910,6,4,1.0,7.0,23,0.304348
70,70,554504,124,6908,0,7000.0,False,6908,6,4,0.0,7.0,24,0.291667
71,71,554504,124,6911,0,7000.0,False,6911,6,4,0.0,7.0,25,0.280000
72,72,571323,124,7218,0,6500.0,False,7218,7,5,0.0,7.0,26,0.269231
73,73,571323,124,7216,0,6500.0,False,7216,7,5,0.0,7.0,27,0.259259
74,74,571323,124,7217,0,6500.0,False,7217,7,5,0.0,7.0,28,0.250000
75,75,571323,124,7219,0,6500.0,False,7219,7,5,0.0,7.0,29,0.241379

In [36]:
vitrine[vitrine.user_id == 124].groupby(['user_id', 'part']).apply(divide_two_cols)

,id,timestamp,user_id,content_id,answered_correctly,prior_question_elapsed_time,prior_question_had_explanation,question_id,part,kmean_cluster,lag,cumsum,cumcount,divs
46,46,0,124,7900,1,NaN,NaN,7900,1,0,NaN,NaN,0,NaN
47,47,32683,124,7876,0,26000.0,False,7876,1,13,1.0,1.0,1,1.000000
48,48,62000,124,175,1,29000.0,False,175,1,13,0.0,1.0,2,0.500000
49,49,83632,124,1278,0,26000.0,False,1278,2,11,1.0,2.0,3,0.666667
50,50,189483,124,2064,0,18000.0,False,2064,3,9,0.0,2.0,4,0.500000
51,51,189483,124,2063,0,18000.0,False,2063,3,9,0.0,2.0,5,0.400000
52,52,189483,124,2065,1,18000.0,False,2065,3,9,0.0,2.0,6,0.333333
53,53,258793,124,3364,0,33333.0,False,3364,4,6,1.0,3.0,7,0.428571
54,54,258793,124,3365,0,33333.0,False,3365,4,6,0.0,3.0,8,0.375000
55,55,258793,124,3363,0,33333.0,False,3363,4,6,0.0,3.0,9,0.333333
56,56,330528,124,2948,0,21000.0,False,2948,4,6,0.0,3.0,10,0.300000
57,57,330528,124,2947,1,21000.0,False,2947,4,6,0.0,3.0,11,0.272727
58,58,330528,124,2946,0,21000.0,False,2946,4,6,1.0,4.0,12,0.333333
59,59,382790,124,2595,1,21666.0,False,2595,4,6,0.0,4.0,13,0.307692
60,60,382790,124,2593,0,21666.0,False,2593,4,6,1.0,5.0,14,0.357143
61,61,382790,124,2594,0,21666.0,False,2594,4,6,0.0,5.0,15,0.333333
62,62,419266,124,4492,0,15000.0,False,4492,5,1,0.0,5.0,16,0.312500
63,63,445527,124,4120,0,32000.0,False,4120,5,1,0.0,5.0,17,0.294118
64,64,475421,124,4696,0,23000.0,False,4696,5,1,0.0,5.0,18,0.277778
65,65,492328,124,6116,1,27000.0,False,6116,5,1,0.0,5.0,19,0.263158
66,66,513206,124,6173,0,14000.0,False,6173,5,1,1.0,6.0,20,0.300000
67,67,523644,124,6370,0,17000.0,False,6370,5,1,0.0,6.0,21,0.285714
68,68,554504,124,6909,1,7000.0,False,6909,6,4,0.0,6.0,22,0.272727
69,69,554504,124,6910,0,7000.0,False,6910,6,4,1.0,7.0,23,0.304348
70,70,554504,124,6908,0,7000.0,False,6908,6,4,0.0,7.0,24,0.291667
71,71,554504,124,6911,0,7000.0,False,6911,6,4,0.0,7.0,25,0.280000
72,72,571323,124,7218,0,6500.0,False,7218,7,5,0.0,7.0,26,0.269231
73,73,571323,124,7216,0,6500.0,False,7216,7,5,0.0,7.0,27,0.259259
74,74,571323,124,7217,0,6500.0,False,7217,7,5,0.0,7.0,28,0.250000
75,75,571323,124,7219,0,6500.0,False,7219,7,5,0.0,7.0,29,0.241379

In [35]:
vitrine[vitrine.user_id == 124]

,id,timestamp,user_id,content_id,answered_correctly,prior_question_elapsed_time,prior_question_had_explanation,question_id,part,kmean_cluster,lag,cumsum,cumcount
46,46,0,124,7900,1,NaN,NaN,7900,1,0,NaN,NaN,0
47,47,32683,124,7876,0,26000.0,False,7876,1,13,1.0,1.0,1
48,48,62000,124,175,1,29000.0,False,175,1,13,0.0,1.0,2
49,49,83632,124,1278,0,26000.0,False,1278,2,11,1.0,2.0,3
50,50,189483,124,2064,0,18000.0,False,2064,3,9,0.0,2.0,4
51,51,189483,124,2063,0,18000.0,False,2063,3,9,0.0,2.0,5
52,52,189483,124,2065,1,18000.0,False,2065,3,9,0.0,2.0,6
53,53,258793,124,3364,0,33333.0,False,3364,4,6,1.0,3.0,7
54,54,258793,124,3365,0,33333.0,False,3365,4,6,0.0,3.0,8
55,55,258793,124,3363,0,33333.0,False,3363,4,6,0.0,3.0,9
56,56,330528,124,2948,0,21000.0,False,2948,4,6,0.0,3.0,10
57,57,330528,124,2947,1,21000.0,False,2947,4,6,0.0,3.0,11
58,58,330528,124,2946,0,21000.0,False,2946,4,6,1.0,4.0,12
59,59,382790,124,2595,1,21666.0,False,2595,4,6,0.0,4.0,13
60,60,382790,124,2593,0,21666.0,False,2593,4,6,1.0,5.0,14
61,61,382790,124,2594,0,21666.0,False,2594,4,6,0.0,5.0,15
62,62,419266,124,4492,0,15000.0,False,4492,5,1,0.0,5.0,16
63,63,445527,124,4120,0,32000.0,False,4120,5,1,0.0,5.0,17
64,64,475421,124,4696,0,23000.0,False,4696,5,1,0.0,5.0,18
65,65,492328,124,6116,1,27000.0,False,6116,5,1,0.0,5.0,19
66,66,513206,124,6173,0,14000.0,False,6173,5,1,1.0,6.0,20
67,67,523644,124,6370,0,17000.0,False,6370,5,1,0.0,6.0,21
68,68,554504,124,6909,1,7000.0,False,6909,6,4,0.0,6.0,22
69,69,554504,124,6910,0,7000.0,False,6910,6,4,1.0,7.0,23
70,70,554504,124,6908,0,7000.0,False,6908,6,4,0.0,7.0,24
71,71,554504,124,6911,0,7000.0,False,6911,6,4,0.0,7.0,25
72,72,571323,124,7218,0,6500.0,False,7218,7,5,0.0,7.0,26
73,73,571323,124,7216,0,6500.0,False,7216,7,5,0.0,7.0,27
74,74,571323,124,7217,0,6500.0,False,7217,7,5,0.0,7.0,28
75,75,571323,124,7219,0,6500.0,False,7219,7,5,0.0,7.0,29